import Mathlib
import Nodes.«erdos-1094--h3--h1--h2».Context

open scoped Nat

/-! Hole `h_odd` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3__h1__h2 : ∃ (K₂ : ℕ),
  ∀ (n k : ℕ),
    K₂ < k →
      (2 : ℕ) * k ≤ n →
        n < k * k → k % (2 : ℕ) = (1 : ℕ) → n % (2 : ℕ) = (1 : ℕ) → ∃ (p : ℕ), Nat.Prime p ∧ p ≤ k ∧ n % p < k % p := by
  sorry
