import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-402--h3-v2--h1--h1--h1--h2--h1`, `erdos-402--h3-v2--h1--h1--h1--h2--h2`, `erdos-402--h3-v2--h1--h1--h1--h2--h3`. -/

open Filter

/-! Hole `hs1` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1__h1__h1__h2__h1 : ∀ (n : ℕ),
  (10 : ℕ) ≤ n →
    n ≤ (228 : ℕ) →
      ∃ (p : ℕ),
        Nat.Prime p ∧
          n < p ∧
            p < (2 : ℕ) * n ∧
              (2 : ℕ) * ((2 : ℕ) * n - p) ≤ n + (2 : ℕ) ∧
                ∀ α < n,
                  p < α + n →
                    (∃ (q : ℕ), Nat.Prime q ∧ n ≤ (3 : ℕ) * q ∧ q ∣ α * (p - α)) ∨
                      ∀ (x y : ℕ), x < y → x * y ∣ α → n * x ≤ α * y := by
  sorry


open Filter

/-! Hole `hs2` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1__h1__h1__h2__h2 : ∀ (n : ℕ),
  (229 : ℕ) ≤ n →
    n ≤ (200014 : ℕ) →
      ∃ (p : ℕ),
        Nat.Prime p ∧
          n < p ∧
            p < (2 : ℕ) * n ∧
              (2 : ℕ) * ((2 : ℕ) * n - p) ≤ n + (2 : ℕ) ∧
                ∀ α < n,
                  p < α + n →
                    (∃ (q : ℕ), Nat.Prime q ∧ n ≤ (3 : ℕ) * q ∧ q ∣ α * (p - α)) ∨
                      ∀ (x y : ℕ), x < y → x * y ∣ α → n * x ≤ α * y := by
  sorry


open Filter

/-! Hole `hlarge` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1__h1__h1__h2__h3 : ∀ (B : Finset ℕ),
  (0 : ℕ) ∉ B →
    B.Nonempty →
      B.gcd id = (1 : ℕ) →
        ¬Nat.Prime B.card →
          (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
            (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
              (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                (200014 : ℕ) < B.card →
                  (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                    ∃ (p : ℕ),
                      Nat.Prime p ∧
                        B.card < p ∧
                          p < (2 : ℕ) * B.card ∧
                            (2 : ℕ) * ((2 : ℕ) * B.card - p) ≤ B.card + (2 : ℕ) ∧
                              ∀ α < B.card,
                                p < α + B.card →
                                  (∃ (q : ℕ), Nat.Prime q ∧ B.card ≤ (3 : ℕ) * q ∧ q ∣ α * (p - α)) ∨
                                    ∀ (x y : ℕ), x < y → x * y ∣ α → B.card * x ≤ α * y := by
  sorry
