import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1050--h1-v2--h2--h1`. -/

/-! Hole `numerator_integral` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h2__h1 : ∃ (a : ℕ → ℤ),
  ∀ (n : ℕ),
    (1 : ℕ) ≤ n →
      (↑(a n) : ℝ) =
        (9 : ℝ) ^ n *
            (((↑(n - (2 : ℕ)).factorial : ℝ) * ∏ k ∈ Finset.Icc (1 : ℕ) n, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) *
              ∏ k ∈ Finset.Icc ((n + (1 : ℕ)) / (2 : ℕ)) n, ((1 : ℝ) - (2 : ℝ) ^ k)) *
          (∑ k ∈ Finset.Icc (1 : ℕ) n,
              ((-∏ t ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) /
                  ∏ l ∈ (Finset.Icc (1 : ℕ) n).erase k, ((1 : ℝ) - (2 : ℝ) ^ ((↑l : ℤ) - (↑k : ℤ)))) *
                ∑ i ∈ Finset.Icc (1 : ℕ) k, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ -
            ∑ i ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)),
              (∑ k ∈ Finset.Icc (1 : ℕ) n,
                  ((-∏ t ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) /
                      ∏ l ∈ (Finset.Icc (1 : ℕ) n).erase k, ((1 : ℝ) - (2 : ℝ) ^ ((↑l : ℤ) - (↑k : ℤ)))) *
                    (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) /
                ((2 : ℝ) ^ i - (1 : ℝ))) := by
  sorry
