import Mathlib
import Nodes.«erdos-1050--h1-v2--h2».Context

/-! Hole `integrality` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h2 : ∃ (a : ℕ → ℤ) (b : ℕ → ℤ),
  ∀ (n : ℕ),
    (1 : ℕ) ≤ n →
      (↑(b n) : ℝ) * ∑' (j : ℕ), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + (1 : ℕ)))⁻¹ - (↑(a n) : ℝ) =
        (9 : ℝ) ^ n *
            (((↑(n - (2 : ℕ)).factorial : ℝ) * ∏ k ∈ Finset.Icc (1 : ℕ) n, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) *
              ∏ k ∈ Finset.Icc ((n + (1 : ℕ)) / (2 : ℕ)) n, ((1 : ℝ) - (2 : ℝ) ^ k)) *
          ∑' (j : ℕ),
            -((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑(n + j) : ℤ) + (↑n : ℤ)))⁻¹ *
              ∏ k ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)),
                ((1 : ℝ) - (2 : ℝ) ^ ((↑k : ℤ) - (↑(n + j) : ℤ))) *
                  ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑k : ℤ) + (↑(n + j) : ℤ)))⁻¹ := by
  -- E(n) = beta0(n) * z - alpha0(n) by partial fractions in x = 2^m (proved below, via Lagrange
  -- interpolation); b(n) = 9^n W(n) beta0(n) is an integer (proved below); a(n) = 9^n W(n) alpha0(n)
  -- is the one hole. Informal argument: annex 959e0d5b10994049b5f27ad77d9d2d8535be9f817bf4de69d747a1e05b9db44b on this node.
  -- Borwein Lemma 3 (numerator integrality): the one hole.
  have hsumZ : ∀ (s : Finset ℕ) (g : ℕ → ℝ), (∀ i ∈ s, ∃ z : ℤ, (z : ℝ) = g i) → ∃ z : ℤ, (z : ℝ) = ∑ i ∈ s, g i := by
    intro s g
    induction s using Finset.induction_on with
    | empty => intro _; exact ⟨0, by simp⟩
    | insert a s ha ih =>
      intro h
      obtain ⟨za, hza⟩ := h a (Finset.mem_insert_self a s)
      obtain ⟨zs, hzs⟩ := ih (fun i hi => h i (Finset.mem_insert_of_mem hi))
      exact ⟨za + zs, by rw [Finset.sum_insert ha]; push_cast; rw [hza, hzs]⟩
  -- (L0) the Lagrange basis sums to 1: the degree-0 case
  have h0 : ∀ s : Finset ℕ, s.Nonempty → ∑ k ∈ s, (1 : ℝ) / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) = 1 := by
    intro s hs
    have hv : Set.InjOn (fun k : ℕ => ((2 : ℝ) ^ k)⁻¹) (s : Set ℕ) := by
      intro a _ b _ hab
      exact pow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) (inv_injective hab)
    have hsum := congrArg (Polynomial.eval (0 : ℝ)) (Lagrange.sum_basis hv hs)
    rw [Polynomial.eval_finset_sum, Polynomial.eval_one] at hsum
    refine Eq.trans (Finset.sum_congr rfl (fun k hk => ?_)) hsum
    unfold Lagrange.basis
    rw [Polynomial.eval_prod, one_div, ← Finset.prod_inv_distrib]
    refine Finset.prod_congr rfl (fun l hl => ?_)
    have ha : (2 : ℝ) ^ k ≠ 0 := by positivity
    have hb : (2 : ℝ) ^ l ≠ 0 := by positivity
    simp only [Lagrange.basisDivisor, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_sub, Polynomial.eval_X]
    rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast,
      show ((2 : ℝ) ^ k)⁻¹ - ((2 : ℝ) ^ l)⁻¹ = (1 - (2 : ℝ) ^ l / (2 : ℝ) ^ k) * (-((2 : ℝ) ^ l)⁻¹) by field_simp; ring,
      mul_inv, zero_sub, mul_assoc, inv_mul_cancel₀ (neg_ne_zero.mpr (inv_ne_zero hb)), mul_one]
  -- the recursion h_e(s) = h_e(s minus a) + y_a h_(e-1)(s), for any weight f
  have hrec : ∀ (s : Finset ℕ) (a : ℕ) (f : ℕ → ℝ), a ∈ s → ∑ k ∈ s, (2 : ℝ) ^ k * f k / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) = ∑ k ∈ s.erase a, (2 : ℝ) ^ k * f k / ∏ l ∈ (s.erase a).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) + (2 : ℝ) ^ a * ∑ k ∈ s, f k / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := by
    intro s a f ha
    rw [← Finset.add_sum_erase s (fun k => f k / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) ha, ← Finset.add_sum_erase s (fun k => (2 : ℝ) ^ k * f k / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) ha, mul_add, Finset.mul_sum, add_left_comm, ← Finset.sum_add_distrib]
    congr 1
    · ring
    · refine Finset.sum_congr rfl (fun k hk => ?_)
      have hka : k ≠ a := Finset.ne_of_mem_erase hk
      have hmem : a ∈ s.erase k := Finset.mem_erase.mpr ⟨Ne.symm hka, ha⟩
      have hsplit := Finset.mul_prod_erase (s.erase k) (fun l => (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) hmem
      rw [Finset.erase_right_comm] at hsplit
      rw [← hsplit]
      have hρ : (1 - (2 : ℝ) ^ ((a : ℤ) - (k : ℤ))) ≠ 0 := by
        intro h1
        have h2 : (2 : ℝ) ^ ((a : ℤ) - (k : ℤ)) = 2 ^ (0 : ℤ) := by rw [zpow_zero]; linarith
        have h3 := zpow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) h2
        omega
      have hq : (1 - (2 : ℝ) ^ ((a : ℤ) - (k : ℤ))) * (1 - (2 : ℝ) ^ ((a : ℤ) - (k : ℤ)))⁻¹ = 1 := mul_inv_cancel₀ hρ
      have hak : (2 : ℝ) ^ a = (2 : ℝ) ^ ((a : ℤ) - (k : ℤ)) * 2 ^ k := by
        rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast]
        field_simp
      simp only [div_eq_mul_inv, mul_inv]
      rw [hak]
      linear_combination ((2 : ℝ) ^ k * f k * (∏ l ∈ (s.erase a).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))))⁻¹) * hq
  -- (L) complete homogeneous sums at the nodes 2^k are integers
  have hW : ∀ N : ℕ, ∀ (s : Finset ℕ) (e : ℕ), s.card + e = N → ∃ z : ℤ, (z : ℝ) = ∑ k ∈ s, ((2 : ℝ) ^ k) ^ e / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := by
    intro N
    induction N with
    | zero =>
      intro s e h
      have hs : s = ∅ := Finset.card_eq_zero.mp (by omega)
      subst hs
      exact ⟨0, by simp⟩
    | succ N ih =>
      intro s e h
      rcases s.eq_empty_or_nonempty with rfl | hs
      · exact ⟨0, by simp⟩
      rcases Nat.eq_zero_or_pos e with rfl | he
      · exact ⟨1, by rw [Int.cast_one]; exact (h0 s hs).symm.trans (Finset.sum_congr rfl (fun k _ => by rw [pow_zero]))⟩
      obtain ⟨e', rfl⟩ : ∃ e', e = e' + 1 := ⟨e - 1, by omega⟩
      obtain ⟨a, ha⟩ := hs
      obtain ⟨z1, hz1⟩ := ih (s.erase a) (e' + 1) (by rw [Finset.card_erase_of_mem ha]; have := Finset.card_pos.mpr ⟨a, ha⟩; omega)
      obtain ⟨z2, hz2⟩ := ih s e' (by omega)
      refine ⟨z1 + 2 ^ a * z2, ?_⟩
      have hr := hrec s a (fun k => ((2 : ℝ) ^ k) ^ e') ha
      simp only [← pow_succ'] at hr
      push_cast
      rw [hz1, hz2]
      exact hr.symm
  -- (L-) and they vanish in negative degree above minus the number of nodes
  have hV : ∀ m : ℕ, ∀ s : Finset ℕ, m + 1 < s.card → ∑ k ∈ s, (((2 : ℝ) ^ k) ^ (m + 1))⁻¹ / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) = 0 := by
    intro m
    induction m with
    | zero =>
      intro s hs
      obtain ⟨a, ha⟩ : s.Nonempty := Finset.card_pos.mp (by omega)
      have hne : (s.erase a).Nonempty := Finset.card_pos.mp (by rw [Finset.card_erase_of_mem ha]; omega)
      have h := hrec s a (fun k => (((2 : ℝ) ^ k) ^ (0 + 1))⁻¹) ha
      have e : ∀ k : ℕ, (2 : ℝ) ^ k * (((2 : ℝ) ^ k) ^ (0 + 1))⁻¹ = 1 := fun k => by
        rw [zero_add, pow_one]; exact mul_inv_cancel₀ (by positivity)
      simp only [e] at h
      rw [h0 s ⟨a, ha⟩, h0 _ hne] at h
      have h2a : (2 : ℝ) ^ a ≠ 0 := by positivity
      rcases mul_eq_zero.mp (show (2 : ℝ) ^ a * (∑ k ∈ s, (((2 : ℝ) ^ k) ^ (0 + 1))⁻¹ / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) = 0 by linarith) with h5 | h5
      · exact absurd h5 h2a
      · exact h5
    | succ m ih =>
      intro s hs
      obtain ⟨a, ha⟩ : s.Nonempty := Finset.card_pos.mp (by omega)
      have h := hrec s a (fun k => (((2 : ℝ) ^ k) ^ (m + 1 + 1))⁻¹) ha
      have e : ∀ k : ℕ, (2 : ℝ) ^ k * (((2 : ℝ) ^ k) ^ (m + 1 + 1))⁻¹ = (((2 : ℝ) ^ k) ^ (m + 1))⁻¹ := fun k => by
        rw [pow_succ' _ (m + 1), mul_inv, ← mul_assoc, mul_inv_cancel₀ (by positivity), one_mul]
      simp only [e] at h
      rw [ih s (by omega), ih (s.erase a) (by rw [Finset.card_erase_of_mem ha]; omega)] at h
      have h2a : (2 : ℝ) ^ a ≠ 0 := by positivity
      rcases mul_eq_zero.mp (show (2 : ℝ) ^ a * (∑ k ∈ s, (((2 : ℝ) ^ k) ^ (m + 1 + 1))⁻¹ / ∏ l ∈ s.erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) = 0 by linarith) with h5 | h5
      · exact absurd h5 h2a
      · exact h5
  -- geometric sums in 2^(-m)
  have hgeo : ∀ m : ℕ, 1 ≤ m → ∀ k : ℕ, ∑ i ∈ Finset.Icc 1 k, (((2 : ℝ) ^ i)⁻¹) ^ m = (1 - (((2 : ℝ) ^ k) ^ m)⁻¹) / ((2 : ℝ) ^ m - 1) := by
    intro m hm k
    have hB : (2 : ℝ) ^ m - 1 ≠ 0 := by
      have : (2 : ℝ) ≤ 2 ^ m := by
        calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ m := pow_le_pow_right₀ (by norm_num) hm
      linarith
    induction k with
    | zero => simp
    | succ k ih =>
      rw [Finset.sum_Icc_succ_top (by omega), ih, inv_pow, pow_succ, mul_pow]
      have hX : ((2 : ℝ) ^ k) ^ m ≠ 0 := by positivity
      have hY : (2 : ℝ) ^ m ≠ 0 := by positivity
      generalize ((2 : ℝ) ^ k) ^ m = X at hX ⊢
      generalize (2 : ℝ) ^ m = Y at hY hB ⊢
      field_simp
      ring
  have hdvd : ∀ n i : ℕ, 1 ≤ i → i ≤ n - 1 → ((2 : ℤ) ^ i - 1) ∣ ∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℤ) - 2 ^ k) := by
    intro n i hi1 hi2
    obtain ⟨k0, hk0⟩ : ∃ k0, k0 = i * (n / i) := ⟨_, rfl⟩
    have hle : k0 ≤ n := by rw [hk0, mul_comm]; exact Nat.div_mul_le_self n i
    have hlt : n < k0 + i := by rw [hk0]; have := Nat.lt_mul_div_succ n (by omega : 0 < i); linarith
    have hge : i ≤ k0 := by rw [hk0]; exact Nat.le_mul_of_pos_right i (Nat.div_pos (by omega) (by omega))
    have hmem : k0 ∈ Finset.Icc ((n + 1) / 2) n := Finset.mem_Icc.mpr ⟨by omega, hle⟩
    have h1 : ((2 : ℤ) ^ i - 1) ∣ (2 : ℤ) ^ k0 - 1 := by
      have := sub_dvd_pow_sub_pow ((2 : ℤ) ^ i) 1 (n / i)
      rw [one_pow, ← pow_mul, ← hk0] at this
      exact this
    have h2 : ((2 : ℤ) ^ i - 1) ∣ (1 : ℤ) - 2 ^ k0 := by
      have : (1 : ℤ) - 2 ^ k0 = -((2 : ℤ) ^ k0 - 1) := by ring
      rw [this]; exact (dvd_neg).mpr h1
    exact h2.trans (Finset.dvd_prod_of_mem (fun k => (1 : ℤ) - 2 ^ k) hmem)
  have hpoly : ∀ n : ℕ, 1 ≤ n → ∃ α : ℕ → ℤ, ∀ y : ℝ, ∏ t ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ t * y) = ∑ j ∈ Finset.range n, (α j : ℝ) * y ^ j := by
    intro n hn
    refine ⟨fun j => (∏ t ∈ Finset.Icc 1 (n - 1), (1 - Polynomial.C ((2 : ℤ) ^ t) * Polynomial.X)).coeff j, fun y => ?_⟩
    have hdeg : (Polynomial.map (Int.castRingHom ℝ) (∏ t ∈ Finset.Icc 1 (n - 1), (1 - Polynomial.C ((2 : ℤ) ^ t) * Polynomial.X))).natDegree < n := by
      refine lt_of_le_of_lt (Polynomial.natDegree_map_le) ?_
      refine lt_of_le_of_lt (Polynomial.natDegree_prod_le _ _) ?_
      refine lt_of_le_of_lt (Finset.sum_le_sum (g := fun _ => 1) (fun t _ => ?_)) ?_
      · compute_degree
      · simp only [Finset.sum_const, smul_eq_mul, mul_one, Nat.card_Icc]; omega
    have hev := Polynomial.eval_eq_sum_range' hdeg y
    have hev2 : ∏ t ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ t * y) = Polynomial.eval y (Polynomial.map (Int.castRingHom ℝ) (∏ t ∈ Finset.Icc 1 (n - 1), (1 - Polynomial.C ((2 : ℤ) ^ t) * Polynomial.X))) := by
      rw [Polynomial.map_prod, Polynomial.eval_prod]
      refine Finset.prod_congr rfl (fun t _ => ?_)
      simp
    rw [hev2, hev]
    refine Finset.sum_congr rfl (fun j _ => ?_)
    rw [Polynomial.coeff_map]
    rfl
  -- alpha0 = S1 - S2. The S2 part (the 1/(2^i - 1) terms) is `hmer` below. The S1 part (`head_integral`) is assembled
  -- from two holes by partial fractions in the parameter c = 8/3: S1 = (polynomial part) + sum_i b_i / (1 - c 2^i), where
  -- b_i = sum_(k >= i) A_k(2^-i) is the residue. Informal argument: annex
  -- a03db62f0576f792454c3f95d14fb02d193662242ec562819da63116009d326b on this node.
  have numerator_integral : ∃ a : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (a n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) - ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := by
    have residue_integral : ∀ n i : ℕ, 1 ≤ i → i ≤ n → ∃ z : ℤ, (z : ℝ) = (∑ k ∈ Finset.Icc i n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - ((2 : ℝ) ^ i)⁻¹ * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := by
      have hQne : ∀ m : ℕ, (∏ s ∈ Finset.Icc 1 m, ((1 : ℤ) - 2 ^ s)) ≠ 0 := by
        intro m
        refine Finset.prod_ne_zero_iff.mpr (fun s hs => ?_)
        have h1 := (Finset.mem_Icc.mp hs).1
        have h2 : (2 : ℤ) ≤ 2 ^ s := by
          calc (2 : ℤ) = 2 ^ 1 := by norm_num
            _ ≤ 2 ^ s := pow_le_pow_right₀ (by norm_num) h1
        omega
      have hG : ∀ N a b : ℕ, a + b = N → ∃ z : ℤ, (∏ s ∈ Finset.Icc 1 (a + b), ((1 : ℤ) - 2 ^ s)) = z * ((∏ s ∈ Finset.Icc 1 a, ((1 : ℤ) - 2 ^ s)) * (∏ s ∈ Finset.Icc 1 b, ((1 : ℤ) - 2 ^ s))) := by
        intro N
        induction N with
        | zero =>
          intro a b h
          obtain ⟨rfl, rfl⟩ : a = 0 ∧ b = 0 := by omega
          exact ⟨1, by simp⟩
        | succ N ih =>
          intro a b h
          rcases Nat.eq_zero_or_pos a with rfl | ha
          · exact ⟨1, by simp⟩
          rcases Nat.eq_zero_or_pos b with rfl | hb
          · exact ⟨1, by simp⟩
          obtain ⟨a', rfl⟩ : ∃ a', a = a' + 1 := ⟨a - 1, by omega⟩
          obtain ⟨b', rfl⟩ : ∃ b', b = b' + 1 := ⟨b - 1, by omega⟩
          obtain ⟨z1, h1⟩ := ih a' (b' + 1) (by omega)
          obtain ⟨z2, h2⟩ := ih (a' + 1) b' (by omega)
          refine ⟨2 ^ (b' + 1) * z1 + z2, ?_⟩
          have e1 : a' + 1 + (b' + 1) = (a' + (b' + 1)) + 1 := by omega
          have e2 : a' + 1 + b' = a' + (b' + 1) := by omega
          have hA := Finset.prod_Icc_succ_top (show 1 ≤ a' + 1 by omega) (fun s => (1 : ℤ) - 2 ^ s)
          have hB := Finset.prod_Icc_succ_top (show 1 ≤ b' + 1 by omega) (fun s => (1 : ℤ) - 2 ^ s)
          have hC := Finset.prod_Icc_succ_top (show 1 ≤ a' + (b' + 1) + 1 by omega) (fun s => (1 : ℤ) - 2 ^ s)
          beta_reduce at hA hB hC
          rw [e2, hA] at h2
          rw [hB] at h1
          rw [e1, hC, hA, hB]
          linear_combination (2 ^ (b' + 1) * (1 - 2 ^ (a' + 1))) * h1 + (1 - 2 ^ (b' + 1)) * h2
      have hN : ∀ m d : ℕ, (∏ s ∈ Finset.Icc 1 d, ((1 : ℤ) - 2 ^ s)) * (∏ t ∈ Finset.Icc 1 m, ((1 : ℤ) - 2 ^ (t + d))) = ∏ s ∈ Finset.Icc 1 (d + m), ((1 : ℤ) - 2 ^ s) := by
        intro m d
        induction m with
        | zero => simp
        | succ m ih =>
          rw [Finset.prod_Icc_succ_top (by omega), show d + (m + 1) = (d + m) + 1 by omega, Finset.prod_Icc_succ_top (by omega), ← mul_assoc, ih,
            show m + 1 + d = d + m + 1 by omega]
      have hsumZ : ∀ (s : Finset ℕ) (g : ℕ → ℝ), (∀ i ∈ s, ∃ z : ℤ, (z : ℝ) = g i) → ∃ z : ℤ, (z : ℝ) = ∑ i ∈ s, g i := by
        intro s g
        induction s using Finset.induction_on with
        | empty => intro _; exact ⟨0, by simp⟩
        | insert a s ha ih =>
          intro h
          obtain ⟨za, hza⟩ := h a (Finset.mem_insert_self a s)
          obtain ⟨zs, hzs⟩ := ih (fun i hi => h i (Finset.mem_insert_of_mem hi))
          exact ⟨za + zs, by rw [Finset.sum_insert ha]; push_cast; rw [hza, hzs]⟩
      intro n i hi hin
      refine hsumZ _ _ (fun k hk => ?_)
      have hk' := Finset.mem_Icc.mp hk
      obtain ⟨d, rfl⟩ : ∃ d, k = i + d := ⟨k - i, by omega⟩
      -- numerator
      have hNr : ∏ t ∈ Finset.Icc 1 (n - 1), (1 - ((2 : ℝ) ^ i)⁻¹ * (2 : ℝ) ^ (t + (i + d))) = ((∏ t ∈ Finset.Icc 1 (n - 1), ((1 : ℤ) - 2 ^ (t + d)) : ℤ) : ℝ) := by
        push_cast
        refine Finset.prod_congr rfl (fun t _ => ?_)
        have h2i : (2 : ℝ) ^ i ≠ 0 := by positivity
        rw [show t + (i + d) = i + (t + d) by omega, pow_add, ← mul_assoc, inv_mul_cancel₀ h2i, one_mul]
      -- denominator
      have hset : (Finset.Icc 1 n).erase (i + d) = Finset.Icc 1 (i + d - 1) ∪ Finset.Icc (i + d + 1) n := by
        ext l
        simp only [Finset.mem_erase, Finset.mem_Icc, Finset.mem_union]
        omega
      have hdisj : Disjoint (Finset.Icc 1 (i + d - 1)) (Finset.Icc (i + d + 1) n) := by
        rw [Finset.disjoint_left]
        intro l h1 h2
        simp only [Finset.mem_Icc] at h1 h2
        omega
      have hD1 : (∏ l ∈ Finset.Icc 1 (i + d - 1), (1 - (2 : ℝ) ^ ((l : ℤ) - ((i + d : ℕ) : ℤ)))) * ((∏ s ∈ Finset.Icc 1 (i + d - 1), (-(2 : ℤ) ^ s) : ℤ) : ℝ) = ((∏ s ∈ Finset.Icc 1 (i + d - 1), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) := by
        have hrefl : ∏ l ∈ Finset.Icc 1 (i + d - 1), (1 - (2 : ℝ) ^ ((l : ℤ) - ((i + d : ℕ) : ℤ))) = ∏ s ∈ Finset.Icc 1 (i + d - 1), (1 - ((2 : ℝ) ^ s)⁻¹) := by
          refine Finset.prod_nbij' (fun l => i + d - l) (fun s => i + d - s) ?_ ?_ ?_ ?_ ?_
          · intro l hl; simp only [Finset.mem_Icc] at hl ⊢; omega
          · intro l hl; simp only [Finset.mem_Icc] at hl ⊢; omega
          · intro l hl; simp only [Finset.mem_Icc] at hl; omega
          · intro l hl; simp only [Finset.mem_Icc] at hl; omega
          · intro l hl
            simp only [Finset.mem_Icc] at hl
            rw [← zpow_natCast, ← zpow_neg]
            congr 2
            push_cast [Nat.cast_sub (show l ≤ i + d by omega)]
            ring
        rw [hrefl]
        push_cast
        rw [← Finset.prod_mul_distrib]
        refine Finset.prod_congr rfl (fun s _ => ?_)
        have h2s : (2 : ℝ) ^ s ≠ 0 := by positivity
        field_simp
        ring
      have hD2 : ∏ l ∈ Finset.Icc (i + d + 1) n, (1 - (2 : ℝ) ^ ((l : ℤ) - ((i + d : ℕ) : ℤ))) = ((∏ s ∈ Finset.Icc 1 (n - (i + d)), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) := by
        push_cast
        refine Finset.prod_nbij' (fun l => l - (i + d)) (fun s => s + (i + d)) ?_ ?_ ?_ ?_ ?_
        · intro l hl; simp only [Finset.mem_Icc] at hl ⊢; omega
        · intro l hl; simp only [Finset.mem_Icc] at hl ⊢; omega
        · intro l hl; simp only [Finset.mem_Icc] at hl; omega
        · intro l hl; simp only [Finset.mem_Icc] at hl; omega
        · intro l hl
          simp only [Finset.mem_Icc] at hl
          rw [← zpow_natCast]
          congr 2
          push_cast [Nat.cast_sub (show i + d ≤ l by omega)]
          ring
      obtain ⟨z1, hz1⟩ := hG _ d (n - 1) rfl
      obtain ⟨z2, hz2⟩ := hG _ (i + d - 1) (n - (i + d)) rfl
      rw [show i + d - 1 + (n - (i + d)) = n - 1 by omega] at hz2
      have hNZ : (∏ t ∈ Finset.Icc 1 (n - 1), ((1 : ℤ) - 2 ^ (t + d))) = z1 * z2 * ((∏ s ∈ Finset.Icc 1 (i + d - 1), ((1 : ℤ) - 2 ^ s)) * (∏ s ∈ Finset.Icc 1 (n - (i + d)), ((1 : ℤ) - 2 ^ s))) := by
        apply mul_left_cancel₀ (hQne d)
        rw [hN (n - 1) d, hz1, hz2]
        ring
      have hNZ' : ((∏ t ∈ Finset.Icc 1 (n - 1), ((1 : ℤ) - 2 ^ (t + d)) : ℤ) : ℝ) = (z1 : ℝ) * z2 * (((∏ s ∈ Finset.Icc 1 (i + d - 1), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) * ((∏ s ∈ Finset.Icc 1 (n - (i + d)), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ)) := by
        exact_mod_cast hNZ
      have hQ1 : ((∏ s ∈ Finset.Icc 1 (i + d - 1), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) ≠ 0 := by exact_mod_cast hQne _
      have hQ2 : ((∏ s ∈ Finset.Icc 1 (n - (i + d)), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) ≠ 0 := by exact_mod_cast hQne _
      have hDr : (∏ l ∈ (Finset.Icc 1 n).erase (i + d), (1 - (2 : ℝ) ^ ((l : ℤ) - ((i + d : ℕ) : ℤ)))) * ((∏ s ∈ Finset.Icc 1 (i + d - 1), (-(2 : ℤ) ^ s) : ℤ) : ℝ) = ((∏ s ∈ Finset.Icc 1 (i + d - 1), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) * ((∏ s ∈ Finset.Icc 1 (n - (i + d)), ((1 : ℤ) - 2 ^ s) : ℤ) : ℝ) := by
        rw [hset, Finset.prod_union hdisj, hD2, ← hD1]
        ring
      have hDne : (∏ l ∈ (Finset.Icc 1 n).erase (i + d), (1 - (2 : ℝ) ^ ((l : ℤ) - ((i + d : ℕ) : ℤ)))) ≠ 0 := by
        intro h0
        rw [h0, zero_mul] at hDr
        exact mul_ne_zero hQ1 hQ2 hDr.symm
      refine ⟨-(z1 * z2 * (∏ s ∈ Finset.Icc 1 (i + d - 1), (-(2 : ℤ) ^ s))), ?_⟩
      rw [hNr, eq_div_iff hDne, hNZ']
      rw [Int.cast_neg, Int.cast_mul, Int.cast_mul]
      linear_combination (-((z1 : ℝ) * z2)) * hDr
    have polypart_integral : ∀ n : ℕ, 1 ≤ n → ∃ z : ℤ, (z : ℝ) = (3 : ℝ) ^ n * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k)) * ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) - (∑ i ∈ Finset.Icc 1 n, (∑ k ∈ Finset.Icc i n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - ((2 : ℝ) ^ i)⁻¹ * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) := by
      intro n hn
      obtain ⟨α, hα⟩ := hpoly n hn
      obtain ⟨D, hD⟩ : ∃ D : ℕ → ℝ, ∀ k, D k = ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := ⟨fun k => _, fun k => rfl⟩
      have hA : ∀ (x : ℝ) (k : ℕ), ∏ t ∈ Finset.Icc 1 (n - 1), (1 - x * (2 : ℝ) ^ (t + k)) = ∑ j ∈ Finset.range n, (α j : ℝ) * (x * 2 ^ k) ^ j := by
        intro x k
        rw [← hα]
        refine Finset.prod_congr rfl (fun t _ => ?_)
        rw [pow_add]; ring
      simp only [← hD, hA]
      -- (a) one double sum
      have hswap : ∑ i ∈ Finset.Icc 1 n, (∑ k ∈ Finset.Icc i n, -(∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j) / D k) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = ∑ k ∈ Finset.Icc 1 n, ∑ i ∈ Finset.Icc 1 k, (-(∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j) / D k) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ := by
        simp only [Finset.sum_mul]
        refine Finset.sum_comm' (fun i k => ?_)
        simp only [Finset.mem_Icc]
        omega
      rw [hswap]
      simp only [Finset.mul_sum]
      rw [← Finset.sum_sub_distrib]
      simp only [← Finset.sum_sub_distrib, ← sub_mul]
      -- (b) per (k, i)
      have hb : ∀ (k i : ℕ), 1 ≤ i → (-(∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) / D k - -(∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j) / D k) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = (∑ j ∈ Finset.range n, ∑ s ∈ Finset.range j, (α j : ℝ) * ((2 : ℝ) ^ k) ^ j * ((8 / 3 : ℝ) ^ s * (((2 : ℝ) ^ i)⁻¹) ^ (j - s))) / D k := by
        intro k i hi
        have h2i : (2 : ℝ) ^ i ≠ 0 := by positivity
        have hne : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i) ≠ 0 := by
          have : (2 : ℝ) ≤ 2 ^ i := by
            calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
              _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi
          intro h0
          linarith
        have hch : (((2 : ℝ) ^ i)⁻¹ - (8 / 3 : ℝ)) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = ((2 : ℝ) ^ i)⁻¹ := by
          rw [show (((2 : ℝ) ^ i)⁻¹ - (8 / 3 : ℝ)) = ((2 : ℝ) ^ i)⁻¹ * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i) by field_simp, mul_assoc, mul_inv_cancel₀ hne, mul_one]
        have hj : ∀ j : ℕ, ((((2 : ℝ) ^ i)⁻¹) ^ j - (8 / 3 : ℝ) ^ j) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = ∑ s ∈ Finset.range j, (8 / 3 : ℝ) ^ s * (((2 : ℝ) ^ i)⁻¹) ^ (j - s) := by
          intro j
          have hg := geom_sum₂_mul (8 / 3 : ℝ) (((2 : ℝ) ^ i)⁻¹) j
          have hg' : (((2 : ℝ) ^ i)⁻¹) ^ j - (8 / 3 : ℝ) ^ j = (∑ s ∈ Finset.range j, (8 / 3 : ℝ) ^ s * (((2 : ℝ) ^ i)⁻¹) ^ (j - 1 - s)) * (((2 : ℝ) ^ i)⁻¹ - (8 / 3 : ℝ)) := by
            linear_combination hg
          rw [hg', mul_assoc, hch, Finset.sum_mul]
          refine Finset.sum_congr rfl (fun s hs => ?_)
          have hs' := Finset.mem_range.mp hs
          rw [mul_assoc, ← pow_succ, show j - 1 - s + 1 = j - s by omega]
        have e1 : (-(∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) / D k - -(∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j) / D k) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = ((∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j - ∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹) / D k := by
          ring
        rw [e1, ← Finset.sum_sub_distrib, Finset.sum_mul]
        congr 1
        refine Finset.sum_congr rfl (fun j _ => ?_)
        rw [← Finset.mul_sum, ← hj j, mul_pow, mul_pow]
        ring
      -- (c) sum over i
      have hc : ∀ k : ℕ, ∑ i ∈ Finset.Icc 1 k, (-(∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) / D k - -(∑ j ∈ Finset.range n, (α j : ℝ) * (((2 : ℝ) ^ i)⁻¹ * 2 ^ k) ^ j) / D k) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ = ∑ j ∈ Finset.range n, ∑ s ∈ Finset.range j, (α j : ℝ) * (8 / 3 : ℝ) ^ s * ((((2 : ℝ) ^ k) ^ j - ((2 : ℝ) ^ k) ^ s) / D k) / ((2 : ℝ) ^ (j - s) - 1) := by
        intro k
        rw [Finset.sum_congr rfl (fun i hi => hb k i (Finset.mem_Icc.mp hi).1), ← Finset.sum_div, Finset.sum_comm, Finset.sum_div]
        refine Finset.sum_congr rfl (fun j _ => ?_)
        rw [Finset.sum_comm, Finset.sum_div]
        refine Finset.sum_congr rfl (fun s hs => ?_)
        have hs' := Finset.mem_range.mp hs
        rw [Finset.sum_congr rfl (fun i _ => (mul_assoc _ _ _).symm), ← Finset.mul_sum, hgeo (j - s) (by omega) k]
        have hjs : ((2 : ℝ) ^ k) ^ j = ((2 : ℝ) ^ k) ^ s * ((2 : ℝ) ^ k) ^ (j - s) := by
          rw [← pow_add]; congr 1; omega
        have hZ : ((2 : ℝ) ^ k) ^ (j - s) * (((2 : ℝ) ^ k) ^ (j - s))⁻¹ = 1 := mul_inv_cancel₀ (by positivity)
        rw [hjs]
        linear_combination (-((α j : ℝ) * ((2 : ℝ) ^ k) ^ s * (8 / 3 : ℝ) ^ s / ((2 : ℝ) ^ (j - s) - 1) / D k)) * hZ
      rw [Finset.sum_congr rfl (fun k _ => hc k), Finset.sum_comm, Finset.mul_sum]
      refine hsumZ _ _ (fun j hj => ?_)
      rw [Finset.sum_comm, Finset.mul_sum]
      refine hsumZ _ _ (fun s hs => ?_)
      have hj' := Finset.mem_range.mp hj
      have hs' := Finset.mem_range.mp hs
      obtain ⟨wj, hwj⟩ := hW _ (Finset.Icc 1 n) j rfl
      obtain ⟨ws, hws⟩ := hW _ (Finset.Icc 1 n) s rfl
      obtain ⟨q, hq⟩ := hdvd n (j - s) (by omega) (by omega)
      have hqR : ∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℝ) - 2 ^ k) = ((2 : ℝ) ^ (j - s) - 1) * q := by exact_mod_cast hq
      have hB : (2 : ℝ) ^ (j - s) - 1 ≠ 0 := by
        have : (2 : ℝ) ≤ 2 ^ (j - s) := by
          calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
            _ ≤ 2 ^ (j - s) := pow_le_pow_right₀ (by norm_num) (by omega)
        linarith
      have h3 : (3 : ℝ) ^ n = 3 ^ (n - s) * 3 ^ s := by rw [← pow_add]; congr 1; omega
      have h83 : (8 / 3 : ℝ) ^ s * 3 ^ s = 8 ^ s := by rw [← mul_pow]; norm_num
      refine ⟨3 ^ (n - s) * 8 ^ s * q * α j * (wj - ws), ?_⟩
      simp only [← hD] at hwj hws
      push_cast
      rw [hwj, hws, hqR, h3, ← h83, ← Finset.sum_sub_distrib]
      rw [Finset.mul_sum, Finset.mul_sum]
      refine Finset.sum_congr rfl (fun k _ => ?_)
      field_simp
    have head_integral : ∃ a₁ : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (a₁ n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) := by
      have hsumZ0 : ∀ (s : Finset ℕ) (g : ℕ → ℝ), (∀ i ∈ s, ∃ z : ℤ, (z : ℝ) = g i) → ∃ z : ℤ, (z : ℝ) = ∑ i ∈ s, g i := by
        intro s g
        induction s using Finset.induction_on with
        | empty => intro _; exact ⟨0, by simp⟩
        | insert a s ha ih =>
          intro h
          obtain ⟨za, hza⟩ := h a (Finset.mem_insert_self a s)
          obtain ⟨zs, hzs⟩ := ih (fun i hi => h i (Finset.mem_insert_of_mem hi))
          exact ⟨za + zs, by rw [Finset.sum_insert ha]; push_cast; rw [hza, hzs]⟩
      have hn : ∀ n : ℕ, 1 ≤ n → ∃ z : ℤ, (z : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) := by
        intro n hn
        obtain ⟨zE, hzE⟩ := polypart_integral n hn
        have hR : ∃ zR : ℤ, (zR : ℝ) = (3 : ℝ) ^ n * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∑ i ∈ Finset.Icc 1 n, (∑ k ∈ Finset.Icc i n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - ((2 : ℝ) ^ i)⁻¹ * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹) := by
          rw [Finset.mul_sum]
          refine hsumZ0 _ _ (fun i hi => ?_)
          have hi' := Finset.mem_Icc.mp hi
          obtain ⟨zb, hzb⟩ := residue_integral n i hi'.1 hi'.2
          refine ⟨zb * (3 * ∏ j ∈ (Finset.Icc 1 n).erase i, ((3 : ℤ) - 8 * 2 ^ j)), ?_⟩
          have hne : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i) ≠ 0 := by
            have : (2 : ℝ) ≤ 2 ^ i := by
              calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
                _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi'.1
            intro h0
            linarith
          have hsplit : (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) = (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i) * ∏ k ∈ (Finset.Icc 1 n).erase i, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) :=
            (Finset.mul_prod_erase _ (fun k => (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) hi).symm
          have he : ∏ k ∈ (Finset.Icc 1 n).erase i, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = (∏ k ∈ (Finset.Icc 1 n).erase i, ((3 : ℝ) - 8 * 2 ^ k)) * ((3 : ℝ) ^ (n - 1))⁻¹ := by
            rw [Finset.prod_congr rfl (fun k _ => (by ring : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = ((3 : ℝ) - 8 * 2 ^ k) * (3 : ℝ)⁻¹)),
              Finset.prod_mul_distrib, Finset.prod_const, Finset.card_erase_of_mem hi, Nat.card_Icc, Nat.add_sub_cancel, inv_pow]
          have h3 : (3 : ℝ) ^ n = 3 * 3 ^ (n - 1) := by
            rw [← pow_succ']; congr 1; omega
          have h3ne : (3 : ℝ) ^ (n - 1) ≠ 0 := by positivity
          obtain ⟨b, hb⟩ : ∃ b : ℝ, b = (∑ k ∈ Finset.Icc i n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - ((2 : ℝ) ^ i)⁻¹ * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := ⟨_, rfl⟩
          rw [← hb] at hzb ⊢
          push_cast
          rw [hzb, hsplit, he, h3]
          have hne' : (3 : ℝ) - 8 * 2 ^ i ≠ 0 := by
            intro h0
            apply hne
            linear_combination (1 / 3 : ℝ) * h0
          field_simp
        obtain ⟨zR, hzR⟩ := hR
        have hPZ : ∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k) = (3 : ℝ) ^ n * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) := by
          rw [Finset.prod_congr rfl (fun k _ => (by ring : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = ((3 : ℝ) - 8 * 2 ^ k) * (3 : ℝ)⁻¹)),
            Finset.prod_mul_distrib, Finset.prod_const, Nat.card_Icc, Nat.add_sub_cancel, inv_pow]
          have h3n : (3 : ℝ) ^ n ≠ 0 := by positivity
          field_simp
        have h9 : (9 : ℝ) ^ n = 3 ^ n * 3 ^ n := by
          rw [show (9 : ℝ) = 3 * 3 by norm_num, mul_pow]
        refine ⟨(Nat.factorial (n - 2) : ℤ) * ((∏ k ∈ Finset.Icc 1 n, ((3 : ℤ) - 8 * 2 ^ k)) * zE + 3 ^ n * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℤ) - 2 ^ k)) * zR), ?_⟩
        push_cast
        rw [hzE, hzR, hPZ, h9]
        ring
      refine ⟨fun n => if h : 1 ≤ n then Classical.choose (hn n h) else 0, fun n hn' => ?_⟩
      simp only [dif_pos hn']
      exact Classical.choose_spec (hn n hn')
    obtain ⟨a₁, h₁⟩ := head_integral
    have hmer : ∃ a₂ : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (a₂ n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := by
      have key : ∀ n : ℕ, 1 ≤ n → ∀ i : ℕ, 1 ≤ i → i ≤ n - 1 → ∃ z : ℤ, (z : ℝ) = (3 : ℝ) ^ (n - 1 - i) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) := by
        intro n hn i hi1 hi2
        obtain ⟨α, hα⟩ := hpoly n hn
        have hA : ∀ k : ℕ, ∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k)) = ∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j := by
          intro k
          rw [← hα]
          refine Finset.prod_congr rfl (fun t _ => ?_)
          rw [pow_add]; ring
        simp only [hA]
        have e1 : ∑ k ∈ Finset.Icc 1 n, (-(∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) = ∑ j ∈ Finset.range n, ∑ k ∈ Finset.Icc 1 n, (-(α j : ℝ)) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) := by
          rw [Finset.sum_comm]
          refine Finset.sum_congr rfl (fun k _ => ?_)
          rw [neg_div, neg_mul, Finset.sum_div, Finset.sum_mul, ← Finset.sum_neg_distrib]
          refine Finset.sum_congr rfl (fun j _ => ?_)
          ring
        rw [e1, Finset.mul_sum]
        refine hsumZ _ _ (fun j hj => ?_)
        have hj' := Finset.mem_range.mp hj
        rw [← Finset.mul_sum]
        have hcX : ∀ k : ℕ, ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ≠ 0 := fun k => by positivity
        rcases lt_or_ge j i with hji | hji
        · refine ⟨0, ?_⟩
          have hvan : ∑ k ∈ Finset.Icc 1 n, (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) = ((8 / 3 : ℝ) ^ (i - j))⁻¹ * ∑ k ∈ Finset.Icc 1 n, (((2 : ℝ) ^ k) ^ (i - j - 1 + 1))⁻¹ / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := by
            rw [Finset.mul_sum]
            refine Finset.sum_congr rfl (fun k _ => ?_)
            have hk : ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) = ((8 / 3 : ℝ) ^ (i - j))⁻¹ * (((2 : ℝ) ^ k) ^ (i - j))⁻¹ := by
              rw [show ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i = ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ (i - j) from by rw [← pow_add]; congr 1; omega,
                mul_inv, ← mul_assoc, mul_inv_cancel₀ (pow_ne_zero _ (hcX k)), one_mul, mul_pow, mul_inv]
            rw [hk, mul_div_assoc, show i - j - 1 + 1 = i - j by omega]
          rw [hvan, hV (i - j - 1) (Finset.Icc 1 n) (by rw [Nat.card_Icc]; omega)]
          simp
        · obtain ⟨w, hw⟩ := hW _ (Finset.Icc 1 n) (j - i) rfl
          refine ⟨-(α j) * 3 ^ (n - 1 - j) * 8 ^ (j - i) * w, ?_⟩
          have hpos : ∑ k ∈ Finset.Icc 1 n, (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) = (8 / 3 : ℝ) ^ (j - i) * ∑ k ∈ Finset.Icc 1 n, ((2 : ℝ) ^ k) ^ (j - i) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := by
            rw [Finset.mul_sum]
            refine Finset.sum_congr rfl (fun k _ => ?_)
            have hk : ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j * ((((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) = (8 / 3 : ℝ) ^ (j - i) * ((2 : ℝ) ^ k) ^ (j - i) := by
              rw [show ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j = ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ (j - i) * ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i from by rw [← pow_add]; congr 1; omega,
                mul_assoc, mul_inv_cancel₀ (pow_ne_zero _ (hcX k)), mul_one, mul_pow]
            rw [hk, mul_div_assoc]
          have h3 : (3 : ℝ) ^ (n - 1 - i) = 3 ^ (n - 1 - j) * 3 ^ (j - i) := by rw [← pow_add]; congr 1; omega
          have h83 : (8 / 3 : ℝ) ^ (j - i) * 3 ^ (j - i) = 8 ^ (j - i) := by rw [← mul_pow]; norm_num
          push_cast
          rw [hpos, hw, h3, ← h83]
          ring
      have hW3 : ∀ n : ℕ, ∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = (∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k)) * ((3 : ℝ) ^ n)⁻¹ := by
        intro n
        rw [Finset.prod_congr rfl (fun k _ => (by ring : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = ((3 : ℝ) - 8 * 2 ^ k) * (3 : ℝ)⁻¹)),
          Finset.prod_mul_distrib, Finset.prod_const, Nat.card_Icc, Nat.add_sub_cancel, inv_pow]
      have hdvd : ∀ n i : ℕ, 1 ≤ i → i ≤ n - 1 → ((2 : ℤ) ^ i - 1) ∣ ∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℤ) - 2 ^ k) := by
        intro n i hi1 hi2
        obtain ⟨k0, hk0⟩ : ∃ k0, k0 = i * (n / i) := ⟨_, rfl⟩
        have hle : k0 ≤ n := by rw [hk0, mul_comm]; exact Nat.div_mul_le_self n i
        have hlt : n < k0 + i := by rw [hk0]; have := Nat.lt_mul_div_succ n (by omega : 0 < i); linarith
        have hge : i ≤ k0 := by rw [hk0]; exact Nat.le_mul_of_pos_right i (Nat.div_pos (by omega) (by omega))
        have hmem : k0 ∈ Finset.Icc ((n + 1) / 2) n := Finset.mem_Icc.mpr ⟨by omega, hle⟩
        have h1 : ((2 : ℤ) ^ i - 1) ∣ (2 : ℤ) ^ k0 - 1 := by
          have := sub_dvd_pow_sub_pow ((2 : ℤ) ^ i) 1 (n / i)
          rw [one_pow, ← pow_mul, ← hk0] at this
          exact this
        have h2 : ((2 : ℤ) ^ i - 1) ∣ (1 : ℤ) - 2 ^ k0 := by
          have : (1 : ℤ) - 2 ^ k0 = -((2 : ℤ) ^ k0 - 1) := by ring
          rw [this]; exact (dvd_neg).mpr h1
        exact h2.trans (Finset.dvd_prod_of_mem (fun k => (1 : ℤ) - 2 ^ k) hmem)
      have hsumZ : ∀ (s : Finset ℕ) (g : ℕ → ℝ), (∀ i ∈ s, ∃ z : ℤ, (z : ℝ) = g i) → ∃ z : ℤ, (z : ℝ) = ∑ i ∈ s, g i := by
        intro s g
        induction s using Finset.induction_on with
        | empty => intro _; exact ⟨0, by simp⟩
        | insert a s ha ih =>
          intro h
          obtain ⟨za, hza⟩ := h a (Finset.mem_insert_self a s)
          obtain ⟨zs, hzs⟩ := ih (fun i hi => h i (Finset.mem_insert_of_mem hi))
          exact ⟨za + zs, by rw [Finset.sum_insert ha]; push_cast; rw [hza, hzs]⟩
      have hn : ∀ n : ℕ, 1 ≤ n → ∃ z : ℤ, (z : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := by
        intro n hn
        rw [Finset.mul_sum]
        refine hsumZ _ _ (fun i hi => ?_)
        have hi' := Finset.mem_Icc.mp hi
        obtain ⟨z1, hz1⟩ := key n hn i hi'.1 hi'.2
        obtain ⟨q, hq⟩ := hdvd n i hi'.1 hi'.2
        have hqR : ∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℝ) - 2 ^ k) = ((2 : ℝ) ^ i - 1) * q := by exact_mod_cast hq
        have h2i : (2 : ℝ) ^ i - 1 ≠ 0 := by
          have : (2 : ℝ) ≤ 2 ^ i := by
            calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
              _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi'.1
          linarith
        have h9 : (9 : ℝ) ^ n = 3 ^ (i + 1) * 3 ^ (n - 1 - i) * 3 ^ n := by
          rw [show (9 : ℝ) = 3 * 3 by norm_num, mul_pow]
          congr 1
          rw [← pow_add]
          congr 1
          omega
        refine ⟨3 ^ (i + 1) * (Nat.factorial (n - 2) : ℤ) * (∏ k ∈ Finset.Icc 1 n, ((3 : ℤ) - 8 * 2 ^ k)) * q * z1, ?_⟩
        push_cast
        rw [hz1, hW3 n, hqR, h9]
        have h3n : (3 : ℝ) ^ n ≠ 0 := by positivity
        field_simp
      refine ⟨fun n => if h : 1 ≤ n then Classical.choose (hn n h) else 0, fun n hn' => ?_⟩
      simp only [dif_pos hn']
      exact Classical.choose_spec (hn n hn')
    obtain ⟨a₂, h₂⟩ := hmer
    refine ⟨fun n => a₁ n - a₂ n, fun n hn => ?_⟩
    push_cast
    rw [h₁ n hn, h₂ n hn]
    ring
  obtain ⟨a, ha⟩ := numerator_integral
  -- Denominator integrality (proved): 3^(n-1) beta0(n) is a coefficient of an integer polynomial.
  have hden : ∃ b : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (b n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := by
    have key : ∀ n : ℕ, 1 ≤ n → ∃ z : ℤ, (z : ℝ) = (3 : ℝ) ^ (n - 1) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := by
      intro n hn
      obtain ⟨α, hα⟩ := hpoly n hn
      have hA : ∀ k : ℕ, ∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k)) = ∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j := by
        intro k
        rw [← hα]
        refine Finset.prod_congr rfl (fun t _ => ?_)
        rw [pow_add]; ring
      simp only [hA]
      have e1 : ∑ k ∈ Finset.Icc 1 n, (-(∑ j ∈ Finset.range n, (α j : ℝ) * ((8 / 3 : ℝ) * 2 ^ k) ^ j) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) = ∑ j ∈ Finset.range n, ∑ k ∈ Finset.Icc 1 n, (-(α j : ℝ)) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ)))) := by
        rw [Finset.sum_comm]
        refine Finset.sum_congr rfl (fun k _ => ?_)
        rw [neg_div, Finset.sum_div, ← Finset.sum_neg_distrib]
        refine Finset.sum_congr rfl (fun j _ => ?_)
        ring
      rw [e1, Finset.mul_sum]
      refine hsumZ _ _ (fun j hj => ?_)
      have hj' := Finset.mem_range.mp hj
      rw [← Finset.mul_sum]
      obtain ⟨w, hw⟩ := hW _ (Finset.Icc 1 n) j rfl
      refine ⟨-(α j) * 3 ^ (n - 1 - j) * 8 ^ j * w, ?_⟩
      have hpos : ∑ k ∈ Finset.Icc 1 n, ((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ j / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) = (8 / 3 : ℝ) ^ j * ∑ k ∈ Finset.Icc 1 n, ((2 : ℝ) ^ k) ^ j / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))) := by
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl (fun k _ => ?_)
        rw [mul_pow, mul_div_assoc]
      have h3 : (3 : ℝ) ^ (n - 1) = 3 ^ (n - 1 - j) * 3 ^ j := by rw [← pow_add]; congr 1; omega
      have h83 : (8 / 3 : ℝ) ^ j * 3 ^ j = 8 ^ j := by rw [← mul_pow]; norm_num
      push_cast
      rw [hpos, hw, h3, ← h83]
      ring
    have hW3 : ∀ n : ℕ, ∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = (∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k)) * ((3 : ℝ) ^ n)⁻¹ := by
      intro n
      rw [Finset.prod_congr rfl (fun k _ => (by ring : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = ((3 : ℝ) - 8 * 2 ^ k) * (3 : ℝ)⁻¹)),
        Finset.prod_mul_distrib, Finset.prod_const, Nat.card_Icc, Nat.add_sub_cancel, inv_pow]
    refine ⟨fun n => if h : 1 ≤ n then 3 * (Nat.factorial (n - 2) : ℤ) * (∏ k ∈ Finset.Icc 1 n, ((3 : ℤ) - 8 * 2 ^ k)) *
        (∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℤ) - 2 ^ k)) * Classical.choose (key n h) else 0, fun n hn => ?_⟩
    simp only [dif_pos hn]
    push_cast
    rw [Classical.choose_spec (key n hn), hW3 n]
    have h9 : (9 : ℝ) ^ n = 3 * (3 : ℝ) ^ (n - 1) * (3 : ℝ) ^ n := by
      rw [show (9 : ℝ) = 3 * 3 by norm_num, mul_pow, mul_comm (3 : ℝ) _, ← pow_succ, Nat.sub_add_cancel hn]
    have h3 : ((3 : ℝ) ^ n)⁻¹ * (3 : ℝ) ^ n = 1 := inv_mul_cancel₀ (by positivity)
    rw [h9]
    linear_combination (-(3 : ℝ) * (Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k)) *
        (∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℝ) - 2 ^ k)) * ((3 : ℝ) ^ (n - 1) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))))) * h3
  obtain ⟨b, hb⟩ := hden
  -- The partial-fraction identity at x = 2^m (proved).
  have hpf : ∀ n : ℕ, 1 ≤ n → ∀ m : ℕ, 1 ≤ m → (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) := by
    intro n hn m hm
    -- General partial fractions, from Mathlib's Lagrange interpolation.
    have lag : ∀ (s : Finset ℕ) (p : ℕ → ℝ) (Q : Polynomial ℝ), (∀ k ∈ s, p k ≠ 0) → Set.InjOn p s →
      Q.degree < s.card → ∀ x : ℝ, (∀ k ∈ s, 1 - p k * x ≠ 0) →
      Q.eval x * ∏ k ∈ s, (1 - p k * x)⁻¹ =
        ∑ k ∈ s, Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (1 - p j / p k))⁻¹ * (1 - p k * x)⁻¹ := by
      intro s p Q hp hinj hdeg x hx
      have hinj' : Set.InjOn (fun k => (p k)⁻¹) s := by
        intro a ha b hb hab
        exact hinj ha hb (inv_injective hab)
      have hxv : ∀ k ∈ s, x ≠ (p k)⁻¹ := by
        intro k hk hxk
        apply hx k hk
        rw [hxk, mul_inv_cancel₀ (hp k hk), sub_self]
      have hQ := Lagrange.eq_interpolate hinj' hdeg
      have hev := Lagrange.eval_interpolate_not_at_node (s := s) (v := fun k => (p k)⁻¹) (fun i => Q.eval (p i)⁻¹) hxv
      rw [← hQ, Lagrange.eval_nodal] at hev
      have hfac : ∀ k ∈ s, (1 - p k * x)⁻¹ = (x - (p k)⁻¹)⁻¹ * (-(p k)⁻¹) := by
        intro k hk
        have h1 := hp k hk
        have h3 : (x - (p k)⁻¹) * (-(p k)) = 1 - p k * x := by
          rw [sub_mul, mul_neg, mul_neg, inv_mul_cancel₀ h1]; ring
        rw [← h3, mul_inv, inv_neg]
      rw [Finset.prod_congr rfl hfac, Finset.prod_mul_distrib, hev]
      have hne : ∏ i ∈ s, (x - (p i)⁻¹) ≠ 0 := Finset.prod_ne_zero_iff.mpr (fun i hi => sub_ne_zero.mpr (hxv i hi))
      rw [Finset.prod_inv_distrib, mul_assoc, ← mul_assoc (∑ i ∈ s, _), mul_comm (∑ i ∈ s, _), ← mul_assoc, ← mul_assoc,
        mul_inv_cancel₀ hne, one_mul, Finset.sum_mul]
      refine Finset.sum_congr rfl (fun k hk => ?_)
      rw [Lagrange.nodalWeight, ← Finset.mul_prod_erase s (fun i => -(p i)⁻¹) hk]
      have hj : ∀ j ∈ s.erase k, ((p k)⁻¹ - (p j)⁻¹)⁻¹ * -(p j)⁻¹ = (1 - p j / p k)⁻¹ := by
        intro j hj
        have hjs := Finset.mem_of_mem_erase hj
        have hjk := Finset.ne_of_mem_erase hj
        have hpj := hp j hjs
        have hpk := hp k hk
        have hne : p j ≠ p k := fun h => hjk (hinj hjs hk h)
        have hsub : p k - p j ≠ 0 := sub_ne_zero.mpr (Ne.symm hne)
        field_simp
        ring
      calc (∏ j ∈ s.erase k, ((p k)⁻¹ - (p j)⁻¹)⁻¹) * (x - (p k)⁻¹)⁻¹ * Q.eval (p k)⁻¹ *
            (-(p k)⁻¹ * ∏ j ∈ s.erase k, -(p j)⁻¹)
          = Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (((p k)⁻¹ - (p j)⁻¹)⁻¹ * -(p j)⁻¹)) * ((x - (p k)⁻¹)⁻¹ * -(p k)⁻¹) := by
            rw [Finset.prod_mul_distrib]; ring
        _ = Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (1 - p j / p k))⁻¹ * (1 - p k * x)⁻¹ := by
            rw [Finset.prod_congr rfl hj, ← Finset.prod_inv_distrib, hfac k hk]
    have hx2 : (2 : ℝ) ≤ (2 : ℝ) ^ m := by
      calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
        _ ≤ 2 ^ m := pow_le_pow_right₀ (by norm_num) hm
    have hx0 : (2 : ℝ) ^ m ≠ 0 := by positivity
    have hp0 : ∀ k : ℕ, (8 / 3 : ℝ) * 2 ^ k ≠ 0 := fun k => by positivity
    have hpx : ∀ k : ℕ, 1 - (8 / 3 : ℝ) * 2 ^ k * 2 ^ m ≠ 0 := by
      intro k
      have h1 : (1 : ℝ) ≤ 2 ^ k := one_le_pow₀ (by norm_num)
      nlinarith
    have hinj : Set.InjOn (fun k : ℕ => (8 / 3 : ℝ) * 2 ^ k) (Finset.Icc 1 n : Set ℕ) := by
      intro a _ b _ hab
      have h : (2 : ℝ) ^ a = 2 ^ b := by
        have := hab; simp only at this
        exact mul_left_cancel₀ (by norm_num : (8 / 3 : ℝ) ≠ 0) this
      exact pow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) h
    have hdeg : (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).degree < ((Finset.Icc 1 n).card : WithBot ℕ) := by
      rw [Polynomial.degree_neg, Polynomial.degree_prod]
      simp only [Polynomial.degree_X_sub_C, Finset.sum_const, Nat.card_Icc]
      rw [show n - 1 + 1 - 1 = n - 1 by omega, show n + 1 - 1 = n by omega, nsmul_one]
      exact_mod_cast (by omega : n - 1 < n)
    have hL := lag (Finset.Icc 1 n) (fun k => (8 / 3 : ℝ) * 2 ^ k) (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.X - Polynomial.C ((2 : ℝ) ^ t)))
      (fun k _ => hp0 k) hinj hdeg ((2 : ℝ) ^ m) (fun k _ => hpx k)
    simp only [Polynomial.eval_neg, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C] at hL
    have hcard : (Finset.Icc 1 (n - 1)).card = n - 1 := by rw [Nat.card_Icc]; omega
    -- geometric sums
    have hgeo : ∀ u : ℝ, u ≠ 0 → 1 - u ≠ 0 → ∀ N : ℕ, (1 - u)⁻¹ + ∑ i ∈ Finset.Icc 1 N, (u ^ i)⁻¹ = (u ^ N)⁻¹ * (1 - u)⁻¹ := by
      intro u hu hu1 N
      induction N with
      | zero => simp
      | succ N ih =>
        rw [Finset.sum_Icc_succ_top (by omega), ← add_assoc, ih]
        have hN : u ^ N ≠ 0 := pow_ne_zero _ hu
        field_simp
        ring
    -- the left side, in terms of the Lagrange data
    have hz1 : ∀ k : ℕ, (2 : ℝ) ^ ((k : ℤ) - (m : ℤ)) = 2 ^ k * ((2 : ℝ) ^ m)⁻¹ := fun k => by
      rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast, div_eq_mul_inv]
    have hz2 : ∀ k : ℕ, (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℤ)) = ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m := fun k => by
      rw [zpow_add₀ two_ne_zero, zpow_natCast, zpow_natCast, mul_assoc]
    have hz3 : (8 / 3 : ℝ) * (2 : ℝ) ^ ((m : ℤ) + (n : ℤ)) = ((8 / 3 : ℝ) * 2 ^ n) * (2 : ℝ) ^ m := by
      rw [zpow_add₀ two_ne_zero, zpow_natCast, zpow_natCast, mul_comm ((2 : ℝ) ^ m), mul_assoc]
    have hsplit : ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹ = (∏ k ∈ Finset.Icc 1 (n - 1), (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) * (1 - ((8 / 3 : ℝ) * 2 ^ n) * (2 : ℝ) ^ m)⁻¹ := by
      have hn' : n = n - 1 + 1 := by omega
      conv_lhs => rw [hn']
      rw [Finset.prod_Icc_succ_top (by omega), ← hn']
    have hfac : ∀ k : ℕ, 1 - 2 ^ k * ((2 : ℝ) ^ m)⁻¹ = ((2 : ℝ) ^ m)⁻¹ * ((2 : ℝ) ^ m - (2 : ℝ) ^ k) := fun k => by
      rw [mul_sub, inv_mul_cancel₀ hx0]; ring
    have hLHS : (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * ((-∏ t ∈ Finset.Icc 1 (n - 1), ((2 : ℝ) ^ m - (2 : ℝ) ^ t)) * ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
      simp only [hz1, hz2, hz3]
      rw [Finset.prod_mul_distrib, hsplit, Finset.prod_congr rfl (fun k _ => hfac k), Finset.prod_mul_distrib,
        Finset.prod_const, hcard, inv_pow]
      ring
    -- the right side
    have hpk : ∀ k : ℕ, (8 / 3 : ℝ) * 2 ^ (k + m) = ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m := fun k => by rw [pow_add, mul_assoc]
    have hswap : ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹ = ∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ∑ i ∈ Finset.Icc 1 (n - 1), ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ i)⁻¹ := by
      simp only [Finset.sum_mul, Finset.mul_sum]
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl (fun k _ => Finset.sum_congr rfl (fun i _ => ?_))
      rw [mul_pow, mul_inv]; ring
    have hRHS : ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
      simp only [hpk]
      rw [hswap, ← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl (fun k hk => ?_)
      rw [← mul_add, hgeo _ (mul_ne_zero (hp0 k) hx0) (hpx k) (n - 1)]
      ring
    -- matching the coefficients
    have hcoef : ∀ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * 2 ^ k) ^ (n - 1))⁻¹ = (-∏ t ∈ Finset.Icc 1 (n - 1), (((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t)) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k)))⁻¹ := by
      intro k hk
      have hq : ∀ t : ℕ, ((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t = ((8 / 3 : ℝ) * 2 ^ k)⁻¹ * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k)) := fun t => by
        rw [mul_sub, mul_one, pow_add, show ((8 / 3 : ℝ) * 2 ^ k)⁻¹ * ((8 / 3 : ℝ) * (2 ^ t * 2 ^ k)) = 2 ^ t * (((8 / 3 : ℝ) * 2 ^ k)⁻¹ * ((8 / 3 : ℝ) * 2 ^ k)) by ring,
          inv_mul_cancel₀ (hp0 k), mul_one]
      have hw : ∀ j : ℕ, ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k) = (2 : ℝ) ^ ((j : ℤ) - (k : ℤ)) := fun j => by
        rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast]
        field_simp
      rw [Finset.prod_congr rfl (fun t _ => hq t), Finset.prod_mul_distrib, Finset.prod_const, hcard, inv_pow]
      simp only [hw]
      ring
    calc (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * ((-∏ t ∈ Finset.Icc 1 (n - 1), ((2 : ℝ) ^ m - (2 : ℝ) ^ t)) * ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := hLHS
      _ = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (∑ k ∈ Finset.Icc 1 n, (-∏ t ∈ Finset.Icc 1 (n - 1), (((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t)) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k)))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by rw [hL]
      _ = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl (fun k hk => ?_)
        rw [← hcoef k hk, mul_pow, mul_inv]
        ring
      _ = ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) := hRHS.symm
  -- Borwein Lemma 1 (proved): sum over m >= 1; the first n - 1 terms vanish.
  have hres : ∀ n : ℕ, 1 ≤ n → (∑' j : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((n + j : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (n + j : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (n + j : ℕ)))⁻¹)) = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) * (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) - ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) - ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := by
    intro n hn
    have pf := hpf n hn
    -- Summability of the two families of pieces.
    have hT : ∀ k : ℕ, Summable (fun m : ℕ => (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) := by
      intro k
      refine Summable.of_norm_bounded (summable_geometric_of_lt_one (by norm_num : (0 : ℝ) ≤ 1 / 2) (by norm_num)) (fun m => ?_)
      have h1 : (1 : ℝ) ≤ 2 ^ k := one_le_pow₀ (by norm_num)
      have h2 : (1 : ℝ) ≤ 2 ^ m := one_le_pow₀ (by norm_num)
      have he : (2 : ℝ) ^ (k + (m + 1)) = 2 * 2 ^ k * 2 ^ m := by ring
      have hneg : (1 : ℝ) - 8 / 3 * 2 ^ (k + (m + 1)) < 0 := by rw [he]; nlinarith
      rw [Real.norm_eq_abs, abs_inv, abs_of_neg hneg, one_div_pow, one_div]
      exact inv_anti₀ (by positivity) (by rw [he]; nlinarith)
    have hGeo : ∀ i : ℕ, 1 ≤ i → ∑' m : ℕ, (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹ = ((2 : ℝ) ^ i - 1)⁻¹ := by
      intro i hi
      have h2 : (2 : ℝ) ≤ 2 ^ i := by
        calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi
      have hr0 : (0 : ℝ) ≤ ((2 : ℝ) ^ i)⁻¹ := by positivity
      have hr1 : ((2 : ℝ) ^ i)⁻¹ < 1 := inv_lt_one_of_one_lt₀ (by linarith)
      have hc : ∀ m : ℕ, (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹ = ((2 : ℝ) ^ i)⁻¹ * (((2 : ℝ) ^ i)⁻¹) ^ m := by
        intro m
        rw [← pow_succ', inv_pow, ← pow_mul, ← pow_mul, mul_comm]
      rw [tsum_congr hc, tsum_mul_left, tsum_geometric_of_lt_one hr0 hr1]
      have h3 : (2 : ℝ) ^ i - 1 ≠ 0 := by linarith
      have h4 : (2 : ℝ) ^ i ≠ 0 := by positivity
      field_simp
    have hGs : ∀ i : ℕ, 1 ≤ i → Summable (fun m : ℕ => (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹) := by
      intro i hi
      by_contra hns
      have := tsum_eq_zero_of_not_summable hns
      rw [hGeo i hi] at this
      have h2 : (2 : ℝ) ≤ 2 ^ i := by
        calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi
      have : ((2 : ℝ) ^ i - 1)⁻¹ ≠ 0 := inv_ne_zero (by linarith)
      contradiction
    have hz0 : Summable (fun j : ℕ => (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) := by
      simpa using hT 0
    have hIcc : ∀ k : ℕ, ∑ i ∈ Finset.range k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (i + 1))⁻¹ = ∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ := by
      intro k
      induction k with
      | zero => simp
      | succ k ih => rw [Finset.sum_range_succ, ih, Finset.sum_Icc_succ_top (by omega)]
    have hTail : ∀ k : ℕ, ∑' m : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹ = (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) - ∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ := by
      intro k
      have hs := hz0.sum_add_tsum_nat_add k
      rw [hIcc k] at hs
      rw [← hs, add_sub_cancel_left]
      exact tsum_congr (fun m => by rw [show k + (m + 1) = m + k + 1 by omega])
    -- The series E(n) summed from m = 1: its first n - 1 terms vanish.
    have hRs1 : Summable (fun m : ℕ => ∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) :=
      summable_sum (fun k _ => (hT k).mul_left _)
    have hRs2 : Summable (fun m : ℕ => ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹) :=
      summable_sum (fun i hi => (hGs i (Finset.mem_Icc.mp hi).1).mul_left _)
    have hRs : Summable (fun m : ℕ => ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹)) := hRs1.add hRs2
    have hGsum : Summable (fun m : ℕ => (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((m + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((m + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((m + 1) : ℕ)))⁻¹)) :=
      hRs.congr (fun m => (pf (m + 1) (by omega)).symm)
    have hshift := hGsum.sum_add_tsum_nat_add (n - 1)
    have hzero : ∑ i ∈ Finset.range (n - 1), (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((i + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((i + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((i + 1) : ℕ)))⁻¹) = 0 := by
      refine Finset.sum_eq_zero (fun i hi => ?_)
      have hi' : i + 1 ∈ Finset.Icc 1 (n - 1) := by
        rw [Finset.mem_range] at hi
        rw [Finset.mem_Icc]; omega
      refine mul_eq_zero_of_right _ (Finset.prod_eq_zero hi' ?_)
      simp
    rw [hzero, zero_add] at hshift
    have hE : (∑' j : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((n + j : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (n + j : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (n + j : ℕ)))⁻¹)) = ∑' m : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((m + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((m + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((m + 1) : ℕ)))⁻¹) := by
      rw [← hshift]
      exact tsum_congr (fun j => by rw [show j + (n - 1) + 1 = n + j by omega])
    rw [hE, tsum_congr (fun m => pf (m + 1) (by omega)), hRs1.tsum_add hRs2,
      Summable.tsum_finsetSum (fun k _ => (hT k).mul_left _),
      Summable.tsum_finsetSum (fun i hi => (hGs i (Finset.mem_Icc.mp hi).1).mul_left _),
      Finset.sum_congr (s₁ := Finset.Icc 1 n) rfl (fun k _ => by rw [tsum_mul_left, hTail k]),
      Finset.sum_congr (s₁ := Finset.Icc 1 (n - 1)) rfl (fun i hi => by rw [tsum_mul_left, hGeo i (Finset.mem_Icc.mp hi).1])]
    simp only [mul_sub, Finset.sum_sub_distrib, Finset.sum_mul, div_eq_mul_inv]
    ring
  refine ⟨a, b, fun n hn => ?_⟩
  linear_combination (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) * hb n hn - ha n hn - (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * hres n hn
