import Mathlib
import Nodes.«erdos-1094--h2--h1».Context

open scoped Nat

/-! Hole `h_lo` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h2__h1 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → k * k ≤ n → n < k * k * k → (n.choose k).minFac > n / k → k ≤ K := by
  -- annex: 97a5239b102766886507b6fe000e0eef718bea41808d9a5b73090dd6a5b26865
  -- Konyagin's theorem, g(k) > k^3 for all large k, in the network's "bounded k" shape:
  -- a binomial coefficient C(n, k) with 2k ≤ n < k^3 whose prime factors all exceed k
  -- occurs only for bounded k. This is the one literature input the h_lo range needs.
  have h_good_below_cube : ∃ K : ℕ, ∀ n k : ℕ, 0 < k → 2 * k ≤ n → n < k * k * k →
      (n.choose k).minFac > k → k ≤ K := by sorry
  -- the assembly: for k^2 ≤ n, n / k ≥ k, so minFac > n / k forces minFac > k, and
  -- 2k ≤ k^2 ≤ n once k ≥ 2; k = 1 is absorbed by the bound max K 1.
  obtain ⟨K, hK⟩ := h_good_below_cube
  refine ⟨max K 1, fun n k hk hsq hcube hmin => ?_⟩
  rcases Nat.lt_or_ge k 2 with h1 | h2
  · exact le_trans (by omega) (le_max_right K 1)
  · have hkd : k ≤ n / k := (Nat.le_div_iff_mul_le hk).2 hsq
    have h2k : 2 * k ≤ n := le_trans (by nlinarith) hsq
    exact le_trans (hK n k hk h2k hcube (lt_of_le_of_lt hkd hmin)) (le_max_left K 1)
