import Mathlib

/-! Hole `borwein` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1 : ∃ a b,
  (∀ (n : ℕ), ↑(b n) * ∑' (n : ℕ), 1 / (2 ^ (n + 3) - 3) - ↑(a n) ≠ 0) ∧
    Filter.Tendsto (fun n => ↑(b n) * ∑' (n : ℕ), 1 / (2 ^ (n + 3) - 3) - ↑(a n)) Filter.atTop (nhds 0) := by
  sorry
