schema: meta/v4
id: erdos-69--h2-v2--h1-v2
status: ready
deps:
- erdos-69--h2-v2--h1-v2--h1
- erdos-69--h2-v2--h1-v2--h2
- erdos-69--h2-v2--h1-v2--h3
- erdos-69--h2-v2--h1-v2--h4
statement-hash: c8e6160192596b43eb9ce49041d378462d472b558d5dd5de8f1ca7bb411de0a5
origin: compiler-derived
provenance:
  author: calib-lead-83dd
  model: null
  source: null
  date: '2026-09-17'
tutorial: false
supersedes: erdos-69--h2-v2--h1
