import Mathlib
import Nodes.«erdos-402--h3-v2--h1».Context

open Filter

/-! Hole `hcomp` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1 : ∀ (B : Finset ℕ),
  (0 : ℕ) ∉ B →
    B.Nonempty →
      B.gcd id = (1 : ℕ) →
        ¬Nat.Prime B.card →
          (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
            (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
              (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                ∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ) := by
  -- Informal argument: annex 6a64518f9cd863c9abea3114b518f3172f4c73c6a187eb928b43db35f77c0002 on this node (graph PR #325, in the merge queue when this was prechecked).
  -- Hole `hsmooth`: B has a pair with gcd(a, b) ≤ a / n, or an element with a prime factor p ≥ n / 2.
  -- The assembly proves that the second alternative contradicts the strict inequalities.
  have hsmooth : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ q : ℕ, q.Prime → B.card ≠ q + 1) →
      (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      (∃ a ∈ B, ∃ b ∈ B, (a.gcd b : ℚ) ≤ (a : ℚ) / (B.card : ℚ)) ∨
        ∃ p : ℕ, p.Prime ∧ B.card ≤ 2 * p ∧ ∃ a ∈ B, p ∣ a := sorry
  have big : ∀ S : Finset ℕ, (∀ x ∈ S, 0 < x) → S.Nonempty → ∃ x ∈ S, S.card ≤ x := by
    intro S hpos hS
    by_contra h
    push Not at h
    have hsub : S ⊆ Finset.Ioo 0 S.card := by
      intro x hx
      exact Finset.mem_Ioo.mpr ⟨hpos x hx, h x hx⟩
    have h1 := Finset.card_le_card hsub
    rw [Nat.card_Ioo] at h1
    have h2 := hS.card_pos
    omega
  have key : ∀ (n p : ℕ) (X T : Finset ℕ), 0 < p → p < n →
      (∀ x ∈ X, ∀ t ∈ T, 0 < x * t ∧ x * t < n ∧ ¬ p ∣ x * t) →
      X.Nonempty → T.Nonempty → n ≤ X.card + T.card → False := by
    intro n p X T hp hpn hxt hX hT hcard
    have hXpos : ∀ x ∈ X, 0 < x := by
      intro x hx
      obtain ⟨t, ht⟩ := hT
      have h := (hxt x hx t ht).1
      exact Nat.pos_of_ne_zero (by rintro rfl; simp at h)
    have hTpos : ∀ t ∈ T, 0 < t := by
      intro t ht
      obtain ⟨x, hx⟩ := hX
      have h := (hxt x hx t ht).1
      exact Nat.pos_of_ne_zero (by rintro rfl; simp at h)
    obtain ⟨x0, hx0, hx0c⟩ := big X hXpos hX
    obtain ⟨t0, ht0, ht0c⟩ := big T hTpos hT
    have h1 := (hxt x0 hx0 t0 ht0).2.1
    have h2 : X.card * T.card ≤ x0 * t0 := Nat.mul_le_mul hx0c ht0c
    have hu := hX.card_pos
    have hv := hT.card_pos
    have hc2 : ((Finset.Ioo 0 n).erase p).card = n - 2 := by
      rw [Finset.card_erase_of_mem (Finset.mem_Ioo.mpr ⟨hp, hpn⟩), Nat.card_Ioo]
      omega
    have h3 : X.card = 1 ∨ T.card = 1 := by
      by_contra h
      push Not at h
      have h4 : 2 ≤ X.card := by omega
      have h5 : 2 ≤ T.card := by omega
      nlinarith
    rcases h3 with hu1 | hv1
    · have hsub : T.image (fun t => x0 * t) ⊆ (Finset.Ioo 0 n).erase p := by
        intro y hy
        obtain ⟨t, ht, rfl⟩ := Finset.mem_image.mp hy
        have h := hxt x0 hx0 t ht
        rw [Finset.mem_erase, Finset.mem_Ioo]
        exact ⟨fun e => h.2.2 (dvd_of_eq e.symm), h.1, h.2.1⟩
      have hc1 : (T.image (fun t => x0 * t)).card = T.card :=
        Finset.card_image_of_injective _ (fun a b h => Nat.eq_of_mul_eq_mul_left (hXpos x0 hx0) h)
      have h6 := Finset.card_le_card hsub
      omega
    · have hsub : X.image (fun x => x * t0) ⊆ (Finset.Ioo 0 n).erase p := by
        intro y hy
        obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hy
        have h := hxt x hx t0 ht0
        rw [Finset.mem_erase, Finset.mem_Ioo]
        exact ⟨fun e => h.2.2 (dvd_of_eq e.symm), h.1, h.2.1⟩
      have hc1 : (X.image (fun x => x * t0)).card = X.card :=
        Finset.card_image_of_injective _ (fun a b h => Nat.eq_of_mul_eq_mul_right (hTpos t0 ht0) h)
      have h6 := Finset.card_le_card hsub
      omega
  have hlarge : ∀ B : Finset ℕ, 0 ∉ B →
      (∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b) →
      ∀ p : ℕ, p.Prime → p < B.card →
      (∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b → a = p * a.gcd b) →
      (∃ a ∈ B, p ∣ a) → (∃ b ∈ B, ¬ p ∣ b) → False := by
    intro B h0 hlt p hp hpn hA hexa hexb
    obtain ⟨a0, ha0, hpa0⟩ := hexa
    obtain ⟨b0, hb0, hpb0⟩ := hexb
    have hG0 : (B.filter (fun b => ¬ p ∣ b)).gcd id ≠ 0 := by
      intro h
      have h1 : (B.filter (fun b => ¬ p ∣ b)).gcd id ∣ id b0 :=
        Finset.gcd_dvd (Finset.mem_filter.mpr ⟨hb0, hpb0⟩)
      rw [h] at h1
      exact hpb0 (by rw [show b0 = 0 from Nat.eq_zero_of_zero_dvd h1]; exact dvd_zero p)
    have hGb : ∀ b ∈ B, ¬ p ∣ b → (B.filter (fun b => ¬ p ∣ b)).gcd id ∣ b := by
      intro b hb hpb
      exact Finset.gcd_dvd (f := id) (Finset.mem_filter.mpr ⟨hb, hpb⟩)
    have hdG : ∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b →
        a.gcd b ∣ (B.filter (fun b => ¬ p ∣ b)).gcd id := by
      intro a ha hpa b hb hpb
      apply Finset.dvd_gcd
      intro b' hb'
      obtain ⟨hb'B, hpb'⟩ := Finset.mem_filter.mp hb'
      have e1 := hA a ha hpa b hb hpb
      have e2 := hA a ha hpa b' hb'B hpb'
      have e3 : a.gcd b = a.gcd b' := Nat.eq_of_mul_eq_mul_left hp.pos (e1.symm.trans e2)
      rw [e3]
      exact Nat.gcd_dvd_right a b'
    have hprod : ∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b →
        0 < ((B.filter (fun b => ¬ p ∣ b)).gcd id * p / a) * (b / (B.filter (fun b => ¬ p ∣ b)).gcd id) ∧
        ((B.filter (fun b => ¬ p ∣ b)).gcd id * p / a) * (b / (B.filter (fun b => ¬ p ∣ b)).gcd id) < B.card ∧
        ¬ p ∣ ((B.filter (fun b => ¬ p ∣ b)).gcd id * p / a) * (b / (B.filter (fun b => ¬ p ∣ b)).gcd id) ∧
        a * ((B.filter (fun b => ¬ p ∣ b)).gcd id * p / a) = (B.filter (fun b => ¬ p ∣ b)).gcd id * p := by
      intro a ha hpa b hb hpb
      generalize hG : (B.filter (fun b => ¬ p ∣ b)).gcd id = G at *
      obtain ⟨e, he⟩ := hdG a ha hpa b hb hpb
      obtain ⟨s, hs⟩ := hGb b hb hpb
      have ea := hA a ha hpa b hb hpb
      have ha0' : 0 < a := Nat.pos_of_ne_zero (fun h => h0 (h ▸ ha))
      have hb0' : b ≠ 0 := fun h => h0 (h ▸ hb)
      have hGp : G * p = e * a :=
        calc G * p = a.gcd b * e * p := by rw [he]
          _ = e * (p * a.gcd b) := by ring
          _ = e * a := by rw [← ea]
      have hx : G * p / a = e := Nat.div_eq_of_eq_mul_left ha0' hGp
      have ht : b / G = s := by
        rw [hs]
        exact Nat.mul_div_cancel_left s (Nat.pos_of_ne_zero hG0)
      rw [hx, ht]
      have hb2 : b = a.gcd b * (e * s) :=
        calc b = G * s := hs
          _ = a.gcd b * e * s := by rw [he]
          _ = a.gcd b * (e * s) := by ring
      have hes : e * s ≠ 0 := by
        intro h
        rw [h, Nat.mul_zero] at hb2
        exact hb0' hb2
      refine ⟨Nat.pos_of_ne_zero hes, ?_, ?_, ?_⟩
      · have h1 := hlt b hb a ha
        rw [Nat.gcd_comm b a] at h1
        have h2 : a.gcd b * (e * s) < a.gcd b * B.card := by
          rw [← hb2, Nat.mul_comm]; exact h1
        exact Nat.lt_of_mul_lt_mul_left h2
      · intro h
        exact hpb (hb2 ▸ Dvd.dvd.mul_left h _)
      · rw [hGp]; ring
    have hcardsum : (B.filter (fun a => p ∣ a)).card + (B.filter (fun b => ¬ p ∣ b)).card = B.card := by
      rw [← Finset.card_union_of_disjoint (Finset.disjoint_filter_filter_not B B (fun a => p ∣ a)),
        Finset.filter_union_filter_not_eq]
    have hinjX : Set.InjOn (fun a => (B.filter (fun b => ¬ p ∣ b)).gcd id * p / a)
        (B.filter (fun a => p ∣ a) : Finset ℕ) := by
      intro a ha a' ha' h
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨haB', hpa'⟩ := Finset.mem_filter.mp ha'
      have h1 := (hprod a haB hpa b0 hb0 hpb0)
      have h2 := (hprod a' haB' hpa' b0 hb0 hpb0).2.2.2
      simp only at h
      rw [← h] at h2
      have hq : 0 < (B.filter (fun b => ¬ p ∣ b)).gcd id * p / a :=
        Nat.pos_of_ne_zero (by
          intro hz
          have := h1.1
          rw [hz, Nat.zero_mul] at this
          exact lt_irrefl 0 this)
      exact Nat.eq_of_mul_eq_mul_right hq (h1.2.2.2.trans h2.symm)
    have hinjT : Set.InjOn (fun b => b / (B.filter (fun b => ¬ p ∣ b)).gcd id)
        (B.filter (fun b => ¬ p ∣ b) : Finset ℕ) := by
      intro b hb b' hb' h
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      obtain ⟨hbB', hpb'⟩ := Finset.mem_filter.mp hb'
      simp only at h
      rw [← Nat.div_mul_cancel (hGb b hbB hpb), ← Nat.div_mul_cancel (hGb b' hbB' hpb'), h]
    refine key B.card p
      ((B.filter (fun a => p ∣ a)).image (fun a => (B.filter (fun b => ¬ p ∣ b)).gcd id * p / a))
      ((B.filter (fun b => ¬ p ∣ b)).image (fun b => b / (B.filter (fun b => ¬ p ∣ b)).gcd id))
      hp.pos hpn ?_ ?_ ?_ ?_
    · intro x hx t ht
      obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp ht
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      have h := hprod a haB hpa b hbB hpb
      exact ⟨h.1, h.2.1, h.2.2.1⟩
    · exact ⟨_, Finset.mem_image_of_mem _ (Finset.mem_filter.mpr ⟨ha0, hpa0⟩)⟩
    · exact ⟨_, Finset.mem_image_of_mem _ (Finset.mem_filter.mpr ⟨hb0, hpb0⟩)⟩
    · rw [Finset.card_image_of_injOn hinjX, Finset.card_image_of_injOn hinjT, hcardsum]
  intro B h0 hne hgcd hnp hnp1 hle hpp
  by_contra hcon
  have hn : 0 < B.card := hne.card_pos
  have hnq : (0 : ℚ) < B.card := by exact_mod_cast hn
  have hlt : ∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b := by
    intro a ha b hb
    rcases (hle a ha b hb).lt_or_eq with h | h
    · exact h
    · exfalso
      apply hcon
      refine ⟨a, ha, b, hb, ?_⟩
      rw [le_div_iff₀ hnq]
      have h2 : a.gcd b * B.card ≤ a := by rw [Nat.mul_comm]; exact h.ge
      exact_mod_cast h2
  have hA : ∀ p : ℕ, p.Prime → B.card ≤ 2 * p →
      ∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b → a = p * a.gcd b := by
    intro p hp hnp2 a ha hpa b hb hpb
    have ha0 : a ≠ 0 := fun h => h0 (h ▸ ha)
    have hg0 : 0 < a.gcd b := Nat.gcd_pos_of_pos_left b (Nat.pos_of_ne_zero ha0)
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    have hpg : ¬ p ∣ a.gcd b := fun h => hpb (h.trans (Nat.gcd_dvd_right a b))
    have hpx : p ∣ x := by
      have h1 : p ∣ a.gcd b * x := hx ▸ hpa
      exact (hp.dvd_mul.mp h1).resolve_left hpg
    obtain ⟨t, ht⟩ := hpx
    have hlt' := hlt a ha b hb
    have hxn : x < B.card := by
      have h3 : a.gcd b * x < a.gcd b * B.card := by
        rw [← hx, Nat.mul_comm]; exact hlt'
      exact Nat.lt_of_mul_lt_mul_left h3
    have ht1 : t = 1 := by
      have hx0 : x ≠ 0 := by
        rintro rfl
        rw [Nat.mul_zero] at hx
        exact ha0 hx
      have ht0 : t ≠ 0 := by
        rintro rfl
        rw [Nat.mul_zero] at ht
        exact hx0 ht
      by_contra hne1
      have ht2 : 2 ≤ t := by omega
      have h4 : p * 2 ≤ p * t := Nat.mul_le_mul_left p ht2
      omega
    calc a = a.gcd b * x := hx
      _ = p * a.gcd b := by rw [ht, ht1]; ring
  rcases hsmooth B h0 hne hgcd hnp hnp1 hle hpp with h | ⟨p, hp, hnp2, a, ha, hpa⟩
  · exact hcon h
  · have hpn : p < B.card := by
      have h1 := hpp a ha p 1 hp (by rwa [pow_one])
      rwa [pow_one] at h1
    have hexb : ∃ b ∈ B, ¬ p ∣ b := by
      by_contra h
      push Not at h
      have h1 : p ∣ B.gcd id := Finset.dvd_gcd (fun b hb => h b hb)
      rw [hgcd] at h1
      exact hp.one_lt.ne' (Nat.dvd_one.mp h1)
    exact hlarge B h0 hlt p hp hpn (hA p hp hnp2) ⟨a, ha, hpa⟩ hexb
