/-! Declared dependencies (D-4 step 8): `variant-93e79cb5--h1`, `variant-93e79cb5--h2`. -/

/-! Hole `h₁` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_93e79cb5__h1 : ∀ (p q : Prop), p ∧ q → q ∧ p := by
  sorry


/-! Hole `h₂` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_93e79cb5__h2 : ∀ (p q : Prop), p ∧ q → q ∧ p → q ∧ p → p := by
  sorry
