import Mathlib
import Nodes.«erdos-1050--h1-v2--h3».Context

/-! Hole `hden` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h3 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            ∀ (n : ℕ),
              ∃ (d : ℕ),
                (0 : ℕ) < d ∧
                  (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                    (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n := by
  -- annex: 4670684d2f0db4568cdaf74d8147b2ae959ae6b3136c3eb5460dbfc117de376f
  have id1_test : ∀ (n j : ℕ) (hj : j ≤ n),
      (∏ i ∈ Finset.range j, ((2 : ℚ) ^ (n - i) - 1)) * ∏ s ∈ Finset.range (n - j), ((2 : ℚ) ^ (s + 1) - 1) =
        ∏ s ∈ Finset.range n, ((2 : ℚ) ^ (s + 1) - 1) := by
    intro n j hj
    induction j with
    | zero => simp
    | succ j ih =>
      have ih' := ih (by omega)
      rw [Finset.prod_range_succ, ← ih']
      obtain ⟨m, hm⟩ : ∃ m, n - j = m + 1 := ⟨n - j - 1, by omega⟩
      rw [hm, Finset.prod_range_succ, show n - (j + 1) = m by omega]
      ring
  have lower_test : ∀ (j : ℕ),
      ∏ i ∈ Finset.range j, ((2 : ℚ) ^ j - 2 ^ i) =
        2 ^ (j * (j - 1) / 2) * ∏ s ∈ Finset.range j, ((2 : ℚ) ^ (s + 1) - 1) := by
    intro j
    have h1 : ∀ i ∈ Finset.range j, ((2 : ℚ) ^ j - 2 ^ i) = 2 ^ i * (2 ^ (j - 1 - i + 1) - 1) := by
      intro i hi
      have hi' := Finset.mem_range.mp hi
      rw [mul_sub, ← pow_add, show i + (j - 1 - i + 1) = j by omega]
      ring
    rw [Finset.prod_congr rfl h1, Finset.prod_mul_distrib, Finset.prod_pow_eq_pow_sum,
      Finset.prod_range_reflect (fun s => ((2 : ℚ) ^ (s + 1) - 1)) j]
    congr 1
    congr 1
    have := Finset.sum_range_id_mul_two j
    omega
  have upper_test : ∀ (j n : ℕ) (hj : j ≤ n),
      ∏ i ∈ Finset.Ioc j n, ((2 : ℚ) ^ j - 2 ^ i) =
        (-1) ^ (n - j) * 2 ^ (j * (n - j)) * ∏ s ∈ Finset.range (n - j), ((2 : ℚ) ^ (s + 1) - 1) := by
    intro j n hj
    have e : Finset.Ioc j n = Finset.Ico (j + 1) (n + 1) := by
      ext x; simp only [Finset.mem_Ioc, Finset.mem_Ico]; omega
    rw [e, Finset.prod_Ico_eq_prod_range, show n + 1 - (j + 1) = n - j by omega]
    have h1 : ∀ t ∈ Finset.range (n - j), ((2 : ℚ) ^ j - 2 ^ (j + 1 + t)) = (-1) * 2 ^ j * (2 ^ (t + 1) - 1) := by
      intro t _
      rw [show j + 1 + t = j + (t + 1) by ring, pow_add]
      ring
    rw [Finset.prod_congr rfl h1, Finset.prod_mul_distrib, Finset.prod_mul_distrib, Finset.prod_const,
      Finset.prod_const, Finset.card_range, ← pow_mul]
  have rhs_test : ∀ (j n : ℕ) (hj : j ≤ n),
      (∏ K ∈ Finset.Ioc n (2 * n), ((2 : ℚ) ^ j - 2 ^ K)) *
        ∏ s ∈ Finset.range (n - j), ((2 : ℚ) ^ (s + 1) - 1) =
        (-1) ^ n * 2 ^ (j * n) * ∏ s ∈ Finset.range (2 * n - j), ((2 : ℚ) ^ (s + 1) - 1) := by
    intro j n hj
    have e : Finset.Ioc n (2 * n) = Finset.Ico (n + 1) (2 * n + 1) := by
      ext x; simp only [Finset.mem_Ioc, Finset.mem_Ico]; omega
    rw [e, Finset.prod_Ico_eq_prod_range, show 2 * n + 1 - (n + 1) = n by omega]
    have h1 : ∀ t ∈ Finset.range n, ((2 : ℚ) ^ j - 2 ^ (n + 1 + t)) =
        (-1) * 2 ^ j * (2 ^ ((n - j) + t + 1) - 1) := by
      intro t _
      rw [show n + 1 + t = j + ((n - j) + t + 1) by omega, pow_add]
      ring
    rw [Finset.prod_congr rfl h1, Finset.prod_mul_distrib, Finset.prod_mul_distrib, Finset.prod_const,
      Finset.prod_const, Finset.card_range, ← pow_mul,
      show 2 * n - j = (n - j) + n by omega, Finset.prod_range_add]
    ring
  have id1_full : ∀ (n j : ℕ) (hj : j ≤ n),
      (((-1 : ℚ) ^ j * (2 : ℚ) ^ (j * (j - (1 : ℕ)) / (2 : ℕ)) *
            ∏ i ∈ Finset.range j, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
          ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - j - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        2 ^ j * ∏ i ∈ (Finset.range (n + 1)).erase j, ((2 : ℚ) ^ j - 2 ^ i) =
      ∏ K ∈ Finset.Ioc n (2 * n), ((2 : ℚ) ^ j - 2 ^ K) := by
    intro n j hj
    have hPne : ∀ m : ℕ, ∏ s ∈ Finset.range m, ((2 : ℚ) ^ (s + 1) - 1) ≠ 0 := by
      intro m
      refine Finset.prod_ne_zero_iff.mpr (fun s _ => ?_)
      have : (1 : ℚ) < 2 ^ (s + 1) := one_lt_pow₀ (by norm_num) (by omega)
      linarith
    have hG1 : ∏ i ∈ Finset.range j, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ)) =
        (∏ s ∈ Finset.range n, ((2 : ℚ) ^ (s + 1) - 1)) /
          ((∏ s ∈ Finset.range (n - j), ((2 : ℚ) ^ (s + 1) - 1)) * ∏ s ∈ Finset.range j, ((2 : ℚ) ^ (s + 1) - 1)) := by
      rw [Finset.prod_div_distrib, ← id1_test n j hj]
      field_simp [hPne]
    have hG2 : ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - j - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ)) =
        (∏ s ∈ Finset.range (2 * n - j), ((2 : ℚ) ^ (s + 1) - 1)) /
          ((∏ s ∈ Finset.range (n - j), ((2 : ℚ) ^ (s + 1) - 1)) * ∏ s ∈ Finset.range n, ((2 : ℚ) ^ (s + 1) - 1)) := by
      rw [Finset.prod_div_distrib, ← id1_test (2 * n - j) n (by omega), show 2 * n - j - n = n - j by omega]
      field_simp [hPne]
    have hsplit : (Finset.range (n + 1)).erase j = Finset.range j ∪ Finset.Ioc j n := by
      ext x; simp only [Finset.mem_erase, Finset.mem_range, Finset.mem_union, Finset.mem_Ioc]; omega
    have hdisj : Disjoint (Finset.range j) (Finset.Ioc j n) := by
      rw [Finset.disjoint_left]
      intro x hx hx'
      simp only [Finset.mem_range, Finset.mem_Ioc] at hx hx'
      omega
    have hR := rhs_test j n hj
    obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hj
    have hsign : (-1 : ℚ) ^ (j + m) = (-1) ^ j * (-1) ^ (j + m - j) := by
      rw [← pow_add]; congr 1; omega
    have ha : 2 * (j * (j - 1) / 2) = j * (j - 1) := Nat.two_mul_div_two_of_even (Nat.even_mul_pred_self _)
    have hexp : j * (j + m) = j * (j - (1 : ℕ)) / (2 : ℕ) + j + j * (j - (1 : ℕ)) / (2 : ℕ) + j * (j + m - j) := by
      rw [show j + m - j = m by omega]
      rcases j with _ | i
      · simp
      · simp only [Nat.add_sub_cancel] at ha ⊢
        nlinarith [ha]
    rw [hG1, hG2, hsplit, Finset.prod_union hdisj, lower_test, upper_test j (j + m) hj]
    apply mul_right_cancel₀ (hPne (j + m - j))
    rw [hR, hsign, hexp, pow_add, pow_add, pow_add]
    field_simp [hPne]
  open Polynomial in
  have lagr_eval : ∀ (n : ℕ) (x : ℕ → ℚ) (hx : ∀ i ≤ n, ∀ j ≤ n, x i = x j → i = j)
    (N : ℚ[X]) (hNdeg : N.degree ≤ n) (r : ℕ → ℚ)
    (hr : ∀ j ≤ n, r j * ∏ i ∈ (Finset.range (n + 1)).erase j, (x j - x i) = N.eval (x j)),
      N = ∑ j ∈ Finset.range (n + 1), C (r j) * ∏ i ∈ (Finset.range (n + 1)).erase j, (X - C (x i)) := by
    intro n x hx N hNdeg r hr
    have hinj : Set.InjOn x (Finset.range (n + 1) : Set ℕ) := by
      intro i hi j hj h
      simp only [Finset.coe_range, Set.mem_Iio] at hi hj
      exact hx i (by omega) j (by omega) h
    apply Polynomial.eq_of_degree_sub_lt_of_eval_finset_eq ((Finset.range (n + 1)).image x)
    · rw [Finset.card_image_of_injOn hinj, Finset.card_range]
      refine lt_of_le_of_lt (Polynomial.degree_sub_le _ _) (max_lt ?_ ?_)
      · exact lt_of_le_of_lt hNdeg (by exact_mod_cast Nat.lt_succ_self n)
      · refine lt_of_le_of_lt (Polynomial.degree_sum_le _ _) ?_
        rw [Finset.sup_lt_iff (by exact WithBot.bot_lt_coe _)]
        intro j hj
        refine lt_of_le_of_lt (Polynomial.degree_mul_le _ _) ?_
        refine lt_of_le_of_lt (add_le_add (Polynomial.degree_C_le) (Polynomial.degree_prod_le _ _)) ?_
        have : ∑ i ∈ (Finset.range (n + 1)).erase j, (X - C (x i)).degree = ((n : ℕ) : WithBot ℕ) := by
          rw [Finset.sum_congr rfl (fun i _ => Polynomial.degree_X_sub_C (x i)), Finset.sum_const,
            Finset.card_erase_of_mem hj, Finset.card_range, Nat.add_sub_cancel]
          simp
        rw [this, zero_add]
        exact_mod_cast Nat.lt_succ_self n
    · intro y hy
      obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hy
      have hk' : k ≤ n := by have := Finset.mem_range.mp hk; omega
      rw [← hr k hk', Polynomial.eval_finset_sum, Finset.sum_eq_single k]
      · simp [Polynomial.eval_prod]
      · intro j hj hjk
        simp only [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_prod, Polynomial.eval_sub,
          Polynomial.eval_X]
        rw [Finset.prod_eq_zero (i := k) (Finset.mem_erase.mpr ⟨Ne.symm hjk, hk⟩) (by ring), mul_zero]
      · intro h; exact absurd hk h
  open Polynomial in
  have deriv_prod_eval : ∀ (S : Finset ℕ) (x : ℕ → ℚ) (z : ℚ),
      (derivative (∏ i ∈ S, (X - C (x i)))).eval z = ∑ l ∈ S, ∏ i ∈ S.erase l, (z - x i) := by
    intro S x z
    rw [Polynomial.derivative_prod_finset, Polynomial.eval_finset_sum]
    refine Finset.sum_congr rfl (fun l _ => ?_)
    simp [Polynomial.eval_prod]
  open Polynomial in
  have deriv_prod_eval_node : ∀ (S : Finset ℕ) (x : ℕ → ℚ) (k : ℕ) (hk : k ∈ S),
      (derivative (∏ i ∈ S, (X - C (x i)))).eval (x k) = ∏ i ∈ S.erase k, (x k - x i) := by
    intro S x k hk
    rw [deriv_prod_eval, Finset.sum_eq_single k]
    · intro l hl hlk
      exact Finset.prod_eq_zero (i := k) (Finset.mem_erase.mpr ⟨Ne.symm hlk, hk⟩) (by ring)
    · intro h; exact absurd hk h
  open Polynomial in
  have lagr_deriv : ∀ (n : ℕ) (x : ℕ → ℚ) (hx : ∀ i ≤ n, ∀ j ≤ n, x i = x j → i = j)
    (N : ℚ[X]) (hNdeg : N.degree ≤ n) (r : ℕ → ℚ)
    (hr : ∀ j ≤ n, r j * ∏ i ∈ (Finset.range (n + 1)).erase j, (x j - x i) = N.eval (x j))
    (k : ℕ) (hk : k ≤ n),
      (derivative N).eval (x k) =
        ∑ j ∈ (Finset.range (n + 1)).erase k, r j * ∏ i ∈ ((Finset.range (n + 1)).erase j).erase k, (x k - x i) +
        r k * ∑ l ∈ (Finset.range (n + 1)).erase k, ∏ i ∈ ((Finset.range (n + 1)).erase k).erase l, (x k - x i) := by
    intro n x hx N hNdeg r hr k hk
    have hkmem : k ∈ Finset.range (n + 1) := Finset.mem_range.mpr (by omega)
    conv_lhs => rw [lagr_eval n x hx N hNdeg r hr]
    rw [Polynomial.derivative_sum, Polynomial.eval_finset_sum, ← Finset.add_sum_erase _ _ hkmem, add_comm]
    congr 1
    · refine Finset.sum_congr rfl (fun j hj => ?_)
      have hjk : j ≠ k := Finset.ne_of_mem_erase hj
      rw [Polynomial.derivative_C_mul, Polynomial.eval_mul, Polynomial.eval_C,
        deriv_prod_eval_node _ x k (Finset.mem_erase.mpr ⟨Ne.symm hjk, hkmem⟩)]
    · rw [Polynomial.derivative_C_mul, Polynomial.eval_mul, Polynomial.eval_C, deriv_prod_eval]
  open Polynomial in
  have formula3 : ∀ (n k : ℕ) (hk : k ≤ n) (Qc : ℕ → ℕ → ℚ)
    (hQc : ∀ j ≤ n, Qc n j * 2 ^ j * ∏ i ∈ (Finset.range (n + 1)).erase j, ((2 : ℚ) ^ j - 2 ^ i) =
      ∏ K ∈ Finset.Ioc n (2 * n), ((2 : ℚ) ^ j - 2 ^ K)),
      ∑ j ∈ Finset.range (k + 1), Qc n j / ((2 : ℚ) ^ (k - j) - 1) =
        Qc n k * 2 ^ k * (∑ K ∈ Finset.Ioc n (2 * n), 1 / ((2 : ℚ) ^ k - 2 ^ K) -
          ∑ i ∈ (Finset.range (n + 1)).erase k, 1 / ((2 : ℚ) ^ k - 2 ^ i)) -
        ∑ j ∈ Finset.Ioc k n, Qc n j * 2 ^ (j - k) / (1 - 2 ^ (j - k)) := by
    intro n k hk Qc hQc
    set x : ℕ → ℚ := fun i => (2 : ℚ) ^ i with hxdef
    have hxinj : ∀ i ≤ n, ∀ j ≤ n, x i = x j → i = j := by
      intro i _ j _ h
      have h' : (2 : ℚ) ^ i = 2 ^ j := h
      exact Nat.pow_right_injective (le_refl 2) (by exact_mod_cast h')
    have hxne : ∀ a b : ℕ, a ≠ b → (2 : ℚ) ^ a - 2 ^ b ≠ 0 := by
      intro a b hab h
      apply hab
      exact Nat.pow_right_injective (le_refl 2) (by exact_mod_cast (sub_eq_zero.mp h))
    set S := (Finset.range (n + 1)).erase k with hS
    set T := Finset.Ioc n (2 * n) with hT
    set N : ℚ[X] := ∏ K ∈ T, (X - C ((2 : ℚ) ^ K)) with hN
    have hNdeg : N.degree ≤ n := by
      rw [hN, Polynomial.degree_prod]
      rw [Finset.sum_congr rfl (fun K _ => Polynomial.degree_X_sub_C ((2 : ℚ) ^ K)), Finset.sum_const, hT,
        Nat.card_Ioc]
      simp
      omega
    have hkmem : k ∈ Finset.range (n + 1) := Finset.mem_range.mpr (by omega)
    have hr : ∀ j ≤ n, (Qc n j * 2 ^ j) * ∏ i ∈ (Finset.range (n + 1)).erase j, (x j - x i) = N.eval (x j) := by
      intro j hj
      rw [hN, Polynomial.eval_prod]
      simp only [Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C, hxdef]
      exact hQc j hj
    have hD := lagr_deriv n x hxinj N hNdeg (fun j => Qc n j * 2 ^ j) hr k hk
    have hD2 : (derivative N).eval (x k) = ∑ K ∈ T, ∏ a ∈ T.erase K, (x k - 2 ^ a) := by
      rw [hN, deriv_prod_eval]
    set P := ∏ i ∈ S, (x k - x i) with hP
    have hPne : P ≠ 0 := by
      rw [hP]
      refine Finset.prod_ne_zero_iff.mpr (fun i hi => hxne k i (Ne.symm (Finset.ne_of_mem_erase hi)))
    have hNk : N.eval (x k) = (Qc n k * 2 ^ k) * P := by
      rw [← hr k hk]
    have hNk' : N.eval (x k) = ∏ K ∈ T, (x k - 2 ^ K) := by
      rw [hN, Polynomial.eval_prod]
      simp only [Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C]
    -- (a)
    have ha : ∀ j ∈ S, ∏ i ∈ ((Finset.range (n + 1)).erase j).erase k, (x k - x i) = P / (x k - x j) := by
      intro j hj
      have hne : x k - x j ≠ 0 := hxne k j (Ne.symm (Finset.ne_of_mem_erase hj))
      rw [Finset.erase_right_comm, eq_div_iff hne, mul_comm, hP, Finset.mul_prod_erase S (fun i => x k - x i) hj]
    have hb : ∀ l ∈ S, ∏ i ∈ S.erase l, (x k - x i) = P / (x k - x l) := by
      intro l hl
      have hne : x k - x l ≠ 0 := hxne k l (Ne.symm (Finset.ne_of_mem_erase hl))
      rw [eq_div_iff hne, mul_comm, hP, Finset.mul_prod_erase S (fun i => x k - x i) hl]
    have hc : ∀ K ∈ T, ∏ a ∈ T.erase K, (x k - 2 ^ a) = N.eval (x k) / (x k - 2 ^ K) := by
      intro K hK
      have hKn : n < K := (Finset.mem_Ioc.mp hK).1
      have hne : x k - 2 ^ K ≠ 0 := hxne k K (by omega)
      rw [eq_div_iff hne, mul_comm, hNk', Finset.mul_prod_erase T (fun a => x k - 2 ^ a) hK]
    rw [← hS] at hD
    rw [hD2, Finset.sum_congr rfl hc] at hD
    have hD3 : ∑ j ∈ S, Qc n j * 2 ^ j * ∏ i ∈ ((Finset.range (n + 1)).erase j).erase k, (x k - x i) =
        ∑ j ∈ S, Qc n j * 2 ^ j * (P / (x k - x j)) :=
      Finset.sum_congr rfl (fun j hj => by rw [ha j hj])
    have hD4 : ∑ l ∈ S, ∏ i ∈ S.erase l, (x k - x i) = ∑ l ∈ S, P / (x k - x l) :=
      Finset.sum_congr rfl hb
    rw [hD3, hD4, hNk] at hD
    -- key: sum over S of r_j / (x k - x j) = r_k * beta
    have key : ∑ j ∈ S, (Qc n j * 2 ^ j) / (x k - x j) =
        (Qc n k * 2 ^ k) * (∑ K ∈ T, 1 / (x k - 2 ^ K) - ∑ i ∈ S, 1 / (x k - x i)) := by
      have e1 : ∑ K ∈ T, Qc n k * 2 ^ k * P / (x k - 2 ^ K) = P * ((Qc n k * 2 ^ k) * ∑ K ∈ T, 1 / (x k - 2 ^ K)) := by
        rw [Finset.mul_sum, Finset.mul_sum]; refine Finset.sum_congr rfl (fun K _ => by ring)
      have e2 : ∑ j ∈ S, Qc n j * 2 ^ j * (P / (x k - x j)) = P * ∑ j ∈ S, (Qc n j * 2 ^ j) / (x k - x j) := by
        rw [Finset.mul_sum]; refine Finset.sum_congr rfl (fun j _ => by ring)
      have e3 : ∑ l ∈ S, P / (x k - x l) = P * ∑ i ∈ S, 1 / (x k - x i) := by
        rw [Finset.mul_sum]; refine Finset.sum_congr rfl (fun j _ => by ring)
      rw [e1, e2, e3] at hD
      apply mul_left_cancel₀ hPne
      linear_combination -hD
    -- split S into range k and Ioc k n
    have hsplit : S = Finset.range k ∪ Finset.Ioc k n := by
      rw [hS]; ext x; simp only [Finset.mem_erase, Finset.mem_range, Finset.mem_union, Finset.mem_Ioc]; omega
    have hdisj : Disjoint (Finset.range k) (Finset.Ioc k n) := by
      rw [Finset.disjoint_left]; intro a ha ha'
      simp only [Finset.mem_range, Finset.mem_Ioc] at ha ha'; omega
    rw [hsplit, Finset.sum_union hdisj] at key
    have hlow : ∀ j ∈ Finset.range k, (Qc n j * 2 ^ j) / (x k - x j) = Qc n j / ((2 : ℚ) ^ (k - j) - 1) := by
      intro j hj
      have hjk : j < k := Finset.mem_range.mp hj
      have hne : (2 : ℚ) ^ (k - j) - 1 ≠ 0 := by
        have : (1 : ℚ) < 2 ^ (k - j) := one_lt_pow₀ (by norm_num) (by omega)
        linarith
      have hne2 : (2 : ℚ) ^ k - 2 ^ j ≠ 0 := hxne k j (by omega)
      simp only [hxdef]
      rw [div_eq_div_iff hne2 hne, show k = j + (k - j) by omega, pow_add]
      simp only [show j + (k - j) - j = k - j by omega]
      ring
    have hhigh : ∀ j ∈ Finset.Ioc k n, (Qc n j * 2 ^ j) / (x k - x j) = Qc n j * 2 ^ (j - k) / (1 - 2 ^ (j - k)) := by
      intro j hj
      have hkj : k < j := (Finset.mem_Ioc.mp hj).1
      have hne : (1 : ℚ) - 2 ^ (j - k) ≠ 0 := by
        have : (1 : ℚ) < 2 ^ (j - k) := one_lt_pow₀ (by norm_num) (by omega)
        linarith
      have hne2 : (2 : ℚ) ^ k - 2 ^ j ≠ 0 := hxne k j (by omega)
      simp only [hxdef]
      rw [div_eq_div_iff hne2 hne, show j = k + (j - k) by omega, pow_add]
      simp only [show k + (j - k) - k = j - k by omega]
      ring
    rw [Finset.sum_congr rfl hlow, Finset.sum_congr rfl hhigh] at key
    rw [Finset.sum_range_succ, Nat.sub_self, pow_zero, sub_self, div_zero, add_zero]
    simp only [hxdef] at key
    rw [← hsplit] at key
    linear_combination key
  have hform : ∀ (Qc : ℕ → ℕ → ℚ),
    (Qc = fun (n k : ℕ) =>
        ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
            ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
          ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (n k : ℕ), k ≤ n →
      ∑ j ∈ Finset.range (k + 1), Qc n j / ((2 : ℚ) ^ (k - j) - 1) =
        Qc n k * 2 ^ k * (∑ K ∈ Finset.Ioc n (2 * n), 1 / ((2 : ℚ) ^ k - 2 ^ K) -
          ∑ i ∈ (Finset.range (n + 1)).erase k, 1 / ((2 : ℚ) ^ k - 2 ^ i)) -
        ∑ j ∈ Finset.Ioc k n, Qc n j * 2 ^ (j - k) / (1 - 2 ^ (j - k)) := by
    intro Qc hQc n k hk
    exact formula3 n k hk Qc (fun j hj => by subst hQc; exact id1_full n j hj)
  clear id1_test lower_test upper_test rhs_test id1_full lagr_eval deriv_prod_eval deriv_prod_eval_node lagr_deriv formula3
  have gauss : ∀ n k : ℕ,
      ∃ z : ℤ, (z : ℚ) = ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
    intro n k
    have hD : ∀ j : ℕ, ((2 : ℚ) ^ (j + 1) - 1) ≠ 0 := by
      intro j
      have h1 : (1 : ℚ) < 2 ^ (j + 1) := one_lt_pow₀ (by norm_num) (by omega)
      exact ne_of_gt (sub_pos.mpr h1)
    have hDk : ∀ k : ℕ, (∏ i ∈ Finset.range k, ((2 : ℚ) ^ (i + 1) - 1)) ≠ 0 := by
      intro k
      exact Finset.prod_ne_zero_iff.mpr (fun i _ => hD i)
    have key : ∀ m j : ℕ,
        (∏ i ∈ Finset.range (j + 1), ((2 : ℚ) ^ (m + 1 - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1)) =
          (∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1)) +
          2 ^ (j + 1) *
            ∏ i ∈ Finset.range (j + 1), ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
      intro m j
      simp only [Finset.prod_div_distrib]
      rw [Finset.prod_range_succ' (fun i => (2 : ℚ) ^ (m + 1 - i) - 1)]
      have hshift : ∀ i : ℕ, m + 1 - (i + 1) = m - i := fun i => by omega
      simp only [hshift, Nat.sub_zero]
      rw [Finset.prod_range_succ (fun i => (2 : ℚ) ^ (m - i) - 1),
        Finset.prod_range_succ (fun i => (2 : ℚ) ^ (i + 1) - 1)]
      have hDj := hDk j
      have hj := hD j
      by_cases hjm : j ≤ m
      · have e : (2 : ℚ) ^ (m + 1) = 2 ^ (m - j) * 2 ^ (j + 1) := by
          rw [← pow_add]
          congr 1
          omega
        rw [e]
        field_simp
        ring
      · have hz : (∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1)) = 0 :=
          Finset.prod_eq_zero (i := m) (Finset.mem_range.mpr (by omega)) (by simp)
        rw [hz]
        simp
    have main : ∀ m j : ℕ, ∃ z : ℤ,
        (z : ℚ) = ∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
      intro m
      induction m with
      | zero =>
        intro j
        cases j with
        | zero => exact ⟨1, by simp⟩
        | succ j =>
          refine ⟨0, ?_⟩
          rw [Finset.prod_eq_zero (i := 0) (by simp) (by simp)]
          simp
      | succ m ih =>
        intro j
        cases j with
        | zero => exact ⟨1, by simp⟩
        | succ j =>
          obtain ⟨a, ha⟩ := ih j
          obtain ⟨b, hb⟩ := ih (j + 1)
          refine ⟨a + 2 ^ (j + 1) * b, ?_⟩
          rw [key, ← ha, ← hb]
          push_cast
          ring
    exact main n k
  have hodd : ∀ (n k : ℕ), k ≤ n → ∀ (c : ℕ → ℤ),
      ∃ z : ℤ, (z : ℚ) = (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
        ∑ j ∈ Finset.range (k + 1), (c j : ℚ) / ((2 : ℚ) ^ (k - j) - 1) := by
    intro n k hk c
    have hint : ∀ j ∈ Finset.range (k + 1), ∃ z : ℤ,
        (z : ℚ) = (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
          ((c j : ℚ) / ((2 : ℚ) ^ (k - j) - 1)) := by
      intro j hj
      have hjk : j ≤ k := Nat.lt_succ_iff.mp (Finset.mem_range.mp hj)
      by_cases hjeq : j = k
      · subst hjeq
        exact ⟨0, by simp⟩
      · obtain ⟨d, hd⟩ : ∃ d, k - j = d + 1 := ⟨k - j - 1, by omega⟩
        rw [hd]
        have hdn : d + 1 ≤ n := by omega
        have ht : 1 ≤ n / (d + 1) := (Nat.one_le_div_iff (by omega)).mpr hdn
        have hP1 : (d + 1) * (n / (d + 1)) ≤ n := Nat.mul_div_le n (d + 1)
        have hP2 : n < (d + 1) * (n / (d + 1)) + (d + 1) := by
          have := Nat.lt_mul_div_succ n (show 0 < d + 1 by omega)
          rw [Nat.mul_succ] at this
          exact this
        have hP3 : (d + 1) ≤ (d + 1) * (n / (d + 1)) := Nat.le_mul_of_pos_right _ ht
        have hmem : (d + 1) * (n / (d + 1)) ∈ Finset.Ioc (n / 2) n := by
          rw [Finset.mem_Ioc]
          generalize (d + 1) * (n / (d + 1)) = P at hP1 hP2 hP3 ⊢
          omega
        have hdvd : ((2 : ℤ) ^ (d + 1) - 1) ∣ ∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℤ) ^ m - 1) := by
          refine dvd_trans ?_ (Finset.dvd_prod_of_mem _ hmem)
          have := sub_dvd_pow_sub_pow ((2 : ℤ) ^ (d + 1)) 1 (n / (d + 1))
          rw [one_pow, ← pow_mul] at this
          exact this
        obtain ⟨q, hq⟩ := hdvd
        have hne : ((2 : ℚ) ^ (d + 1) - 1) ≠ 0 := by
          have : (1 : ℚ) < 2 ^ (d + 1) := one_lt_pow₀ (by norm_num) (by omega)
          linarith
        refine ⟨c j * q, ?_⟩
        have hcast : (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) =
            (((2 : ℤ) ^ (d + 1) - 1 : ℤ) : ℚ) * (q : ℚ) := by
          rw [← Int.cast_mul, ← hq]
          push_cast
          rfl
        rw [hcast]
        push_cast
        field_simp
    choose! g hg using hint
    refine ⟨∑ j ∈ Finset.range (k + 1), g j, ?_⟩
    push_cast
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl hg
  have combine : ∀ (p M : ℚ) (a : ℕ) (Ω A B m : ℤ), Odd Ω →
      (Ω : ℚ) * p = 2 ^ a * A → (B : ℚ) = M * p → (m : ℚ) = M →
      ∃ z : ℤ, (z : ℚ) * 2 ^ a = M * p := by
    intro p M a Ω A B m hΩ h1 h2 hm
    have hint : Ω * B = 2 ^ a * (m * A) := by
      have : ((Ω * B : ℤ) : ℚ) = ((2 ^ a * (m * A) : ℤ) : ℚ) := by
        push_cast
        rw [h2, ← hm]
        linear_combination (m : ℚ) * h1
      exact_mod_cast this
    obtain ⟨t, ht⟩ := hΩ
    have hcop : IsCoprime ((2 : ℤ) ^ a) Ω := by
      apply IsCoprime.pow_left
      exact ⟨-t, 1, by rw [ht]; ring⟩
    have hdvd : (2 : ℤ) ^ a ∣ B * Ω := ⟨m * A, by rw [mul_comm, hint]⟩
    obtain ⟨c, hc⟩ := hcop.dvd_of_dvd_mul_right hdvd
    refine ⟨c, ?_⟩
    rw [← h2, hc]
    push_cast
    ring
  have hcore : ∀ (Qc : ℕ → ℕ → ℚ),
    (Qc = fun (n k : ℕ) =>
        ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
            ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
          ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (n k : ℕ), k ≤ n →
      ∃ z : ℤ, (z : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) =
        (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
          ∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ)) := by
    intro Qc hQc n k hk
    have hQcint : ∀ j : ℕ, ∃ g : ℤ, Qc n j = 2 ^ (j * (j - 1) / 2) * g := by
      intro j
      obtain ⟨a, ha⟩ := gauss n j
      obtain ⟨b, hb⟩ := gauss (2 * n - j) n
      refine ⟨(-1) ^ j * a * b, ?_⟩
      rw [hQc]
      simp only []
      rw [← ha, ← hb]
      push_cast
      ring
    choose g hg using hQcint
    -- the odd product
    have hΩdiv : ∀ s : ℕ, 1 ≤ s → s ≤ 2 * n → ∃ w : ℤ,
        (w : ℚ) * ((2 : ℚ) ^ s - 1) = ((∏ t ∈ Finset.Icc 1 (2 * n), ((2 : ℤ) ^ t - 1) : ℤ) : ℚ) := by
      intro s h1 h2
      refine ⟨∏ t ∈ (Finset.Icc 1 (2 * n)).erase s, ((2 : ℤ) ^ t - 1), ?_⟩
      rw [← Finset.prod_erase_mul _ _ (Finset.mem_Icc.mpr ⟨h1, h2⟩)]
      push_cast
      ring
    have hΩodd : Odd (∏ t ∈ Finset.Icc 1 (2 * n), ((2 : ℤ) ^ t - 1)) := by
      apply Finset.prod_induction _ (fun x : ℤ => Odd x)
      · intro x y hx hy
        exact hx.mul hy
      · exact odd_one
      · intro t ht
        have ht1 : t ≠ 0 := by
          have := (Finset.mem_Icc.mp ht).1
          omega
        exact Even.sub_odd ((Int.even_pow).mpr ⟨even_two, ht1⟩) odd_one
    -- one term 2^a / (2^a - 2^b), times the odd product, is an integer
    have key1 : ∀ a b : ℕ, a ≠ b → a ≤ 2 * n → b ≤ 2 * n → ∃ w : ℤ,
        (w : ℚ) = ((∏ t ∈ Finset.Icc 1 (2 * n), ((2 : ℤ) ^ t - 1) : ℤ) : ℚ) * 2 ^ a * (1 / ((2 : ℚ) ^ a - 2 ^ b)) := by
      intro a b hab ha hb
      rcases Nat.lt_or_gt_of_ne hab with hlt | hgt
      · obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_lt hlt
        obtain ⟨w, hw⟩ := hΩdiv (d + 1) (by omega) (by omega)
        refine ⟨-w, ?_⟩
        have hne : (2 : ℚ) ^ (d + 1) - 1 ≠ 0 := by
          have : (1 : ℚ) < 2 ^ (d + 1) := one_lt_pow₀ (by norm_num) (by omega)
          linarith
        have h2a : (2 : ℚ) ^ a ≠ 0 := by positivity
        rw [← hw, show a + d + 1 = a + (d + 1) by ring, show (2 : ℚ) ^ (a + (d + 1)) = 2 ^ a * 2 ^ (d + 1) from pow_add _ _ _]
        have : (2 : ℚ) ^ a - 2 ^ a * 2 ^ (d + 1) = -(2 ^ a * (2 ^ (d + 1) - 1)) := by ring
        rw [this]
        field_simp
        push_cast
        ring
      · obtain ⟨d, rfl⟩ := Nat.exists_eq_add_of_lt hgt
        obtain ⟨w, hw⟩ := hΩdiv (d + 1) (by omega) (by omega)
        refine ⟨w * 2 ^ (d + 1), ?_⟩
        have hne : (2 : ℚ) ^ (d + 1) - 1 ≠ 0 := by
          have : (1 : ℚ) < 2 ^ (d + 1) := one_lt_pow₀ (by norm_num) (by omega)
          linarith
        have h2b : (2 : ℚ) ^ b ≠ 0 := by positivity
        rw [← hw, show b + d + 1 = b + (d + 1) by ring, show (2 : ℚ) ^ (b + (d + 1)) = 2 ^ b * 2 ^ (d + 1) from pow_add _ _ _]
        have : (2 : ℚ) ^ b * 2 ^ (d + 1) - 2 ^ b = 2 ^ b * (2 ^ (d + 1) - 1) := by ring
        rw [this]
        field_simp
        push_cast
        ring
    set Ω : ℤ := ∏ t ∈ Finset.Icc 1 (2 * n), ((2 : ℤ) ^ t - 1) with hΩ
    have hK : ∀ K ∈ Finset.Ioc n (2 * n), ∃ w : ℤ,
        (w : ℚ) = (Ω : ℚ) * 2 ^ k * (1 / ((2 : ℚ) ^ k - 2 ^ K)) := by
      intro K hK'
      have := Finset.mem_Ioc.mp hK'
      exact key1 k K (by omega) (by omega) (by omega)
    have hI : ∀ i ∈ (Finset.range (n + 1)).erase k, ∃ w : ℤ,
        (w : ℚ) = (Ω : ℚ) * 2 ^ k * (1 / ((2 : ℚ) ^ k - 2 ^ i)) := by
      intro i hi
      have h1 := Finset.ne_of_mem_erase hi
      have h2 := Finset.mem_range.mp (Finset.mem_of_mem_erase hi)
      exact key1 k i (Ne.symm h1) (by omega) (by omega)
    have hT : ∀ j ∈ Finset.Ioc k n, ∃ w : ℤ,
        (w : ℚ) * 2 ^ (k * (k - 1) / 2) = (Ω : ℚ) * (Qc n j * 2 ^ (j - k) / (1 - 2 ^ (j - k))) := by
      intro j hj
      have hj' := Finset.mem_Ioc.mp hj
      obtain ⟨d, hd⟩ : ∃ d, j - k = d + 1 := ⟨j - k - 1, by omega⟩
      obtain ⟨w, hw⟩ := hΩdiv (d + 1) (by omega) (by omega)
      have hmono : k * (k - 1) / 2 ≤ j * (j - 1) / 2 :=
        Nat.div_le_div_right (Nat.mul_le_mul (by omega) (by omega))
      obtain ⟨e, he⟩ := Nat.exists_eq_add_of_le hmono
      refine ⟨-(w * g j * 2 ^ e * 2 ^ (d + 1)), ?_⟩
      have hne : (2 : ℚ) ^ (d + 1) - 1 ≠ 0 := by
        have : (1 : ℚ) < 2 ^ (d + 1) := one_lt_pow₀ (by norm_num) (by omega)
        linarith
      have hne' : (1 : ℚ) - 2 ^ (d + 1) ≠ 0 := by
        intro h
        apply hne
        linarith
      rw [hd, hg j, he, ← hw, show (2 : ℚ) ^ (k * (k - 1) / 2 + e) = 2 ^ (k * (k - 1) / 2) * 2 ^ e from pow_add _ _ _]
      field_simp
      push_cast
      ring
    choose! fK hfK using hK
    choose! fI hfI using hI
    choose! fT hfT using hT
    have h2adic : (Ω : ℚ) * ∑ j ∈ Finset.range (k + 1), Qc n j / ((2 : ℚ) ^ (k - j) - 1) =
        2 ^ (k * (k - 1) / 2) * ((g k * (∑ K ∈ Finset.Ioc n (2 * n), fK K -
          ∑ i ∈ (Finset.range (n + 1)).erase k, fI i) - ∑ j ∈ Finset.Ioc k n, fT j : ℤ) : ℚ) := by
      rw [hform Qc hQc n k hk]
      push_cast
      rw [Finset.sum_congr rfl hfK, Finset.sum_congr rfl hfI, ← Finset.mul_sum, ← Finset.mul_sum]
      have htail : (2 : ℚ) ^ (k * (k - 1) / 2) * ∑ j ∈ Finset.Ioc k n, (fT j : ℚ) =
          (Ω : ℚ) * ∑ j ∈ Finset.Ioc k n, Qc n j * 2 ^ (j - k) / (1 - 2 ^ (j - k)) := by
        rw [Finset.mul_sum, Finset.mul_sum]
        refine Finset.sum_congr rfl (fun j hj => ?_)
        rw [mul_comm]
        exact hfT j hj
      rw [hg k]
      simp only [one_div] at htail ⊢
      linear_combination htail
    -- the odd half
    obtain ⟨B, hB⟩ := hodd n k hk (fun j => 2 ^ (j * (j - 1) / 2) * g j)
    have hB' : (B : ℚ) = (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
        ∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ)) := by
      rw [hB]
      congr 1
      refine Finset.sum_congr rfl (fun j _ => ?_)
      rw [hg j]
      push_cast
      ring
    exact combine _ _ _ Ω _ B (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℤ) ^ m - 1)) hΩodd h2adic hB'
      (by push_cast; rfl)
  clear hform hodd combine
  have hcnall : ∀ n : ℕ, ∃ z : ℤ, (z : ℚ) = (∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
      ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + 1) - 3) := by
    intro n
    have hint : ∀ j ∈ Finset.range n, ∃ z : ℤ,
        (z : ℚ) = (∏ i ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (i + 1) - 3)) * ((3 : ℚ) / ((2 : ℚ) ^ (j + 1) - 3)) := by
      intro j hj
      by_cases h2 : j < 2
      · have hj' : j = 0 ∨ j = 1 := by omega
        rcases hj' with rfl | rfl
        · refine ⟨-3 * ∏ i ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
          have e : (3 : ℚ) / ((2 : ℚ) ^ (0 + 1) - 3) = -3 := by norm_num
          rw [e]
          push_cast
          ring
        · refine ⟨3 * ∏ i ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
          have e : (3 : ℚ) / ((2 : ℚ) ^ (1 + 1) - 3) = 3 := by norm_num
          rw [e]
          push_cast
          ring
      · have hmem : j ∈ Finset.Ico 2 n := Finset.mem_Ico.mpr ⟨by omega, Finset.mem_range.mp hj⟩
        have hne : ((2 : ℚ) ^ (j + 1) - 3) ≠ 0 := by
          have h8 : (8 : ℚ) ≤ 2 ^ (j + 1) := by
            calc (8 : ℚ) = 2 ^ 3 := by norm_num
              _ ≤ 2 ^ (j + 1) := pow_le_pow_right₀ (by norm_num) (by omega)
          linarith
        refine ⟨3 * ∏ i ∈ (Finset.Ico 2 n).erase j, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
        rw [← Finset.mul_prod_erase _ _ hmem]
        push_cast
        field_simp
    choose! g hg using hint
    refine ⟨∑ j ∈ Finset.range n, g j, ?_⟩
    push_cast
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl hg
  intro Qc hQc Qx hQx Aq hAq n
  have hb :
    ((2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℕ) : ℝ) ^ 2 ≤
      (2 : ℝ) ^ (3 * n * n) := by
    have key : (2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
            (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ)) ^ 2 ≤
        2 ^ (3 * n * n) := by
      rcases (show n ≤ 9 ∨ 10 ≤ n by omega) with hn | hn
      · revert n
        decide +kernel
      · rw [if_neg (by omega), if_neg (by omega)]
        have hP1 : ∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) ≤ 2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) := by
          rw [← Finset.prod_pow_eq_pow_sum]
          exact Finset.prod_le_prod' (fun m _ => Nat.sub_le _ _)
        have hP2 : ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) ≤ 2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1)) := by
          rw [← Finset.prod_pow_eq_pow_sum]
          exact Finset.prod_le_prod' (fun m _ => Nat.sub_le _ _)
        obtain ⟨c, hc⟩ : ∃ c, n = n / 2 + c + 1 := ⟨n - n / 2 - 1, by omega⟩
        obtain ⟨d, hd⟩ : ∃ d, n = d + 3 := ⟨n - 3, by omega⟩
        have hS1 : (∑ m ∈ Finset.Ioc (n / 2) n, m) * 2 = 2 * (c + 1) * (n / 2 + 1) + (c + 1) * c := by
          have e : Finset.Ioc (n / 2) n = Finset.Ico (n / 2 + 1) (n + 1) := by
            ext x; simp only [Finset.mem_Ioc, Finset.mem_Ico]; omega
          rw [e, Finset.sum_Ico_eq_sum_range, show n + 1 - (n / 2 + 1) = c + 1 by omega,
            Finset.sum_add_distrib, Finset.sum_const, Finset.card_range, smul_eq_mul, add_mul,
            Finset.sum_range_id_mul_two]
          simp only [Nat.add_sub_cancel]
          ring
        have hS2 : (∑ j ∈ Finset.Ico 2 n, (j + 1)) * 2 = 6 * (d + 1) + (d + 1) * d := by
          rw [Finset.sum_Ico_eq_sum_range, show n - 2 = d + 1 by omega]
          have : ∀ k ∈ Finset.range (d + 1), 2 + k + 1 = 3 + k := fun k _ => by omega
          rw [Finset.sum_congr rfl this, Finset.sum_add_distrib, Finset.sum_const, Finset.card_range,
            smul_eq_mul, add_mul, Finset.sum_range_id_mul_two]
          simp only [Nat.add_sub_cancel]
          ring
        have hT : n * (n + 1) / 2 * 2 = n * (n + 1) :=
          Nat.div_mul_cancel (Nat.even_mul_succ_self n).two_dvd
        have hexp : 2 * (n * (n + 1) / 2) + 2 * (∑ m ∈ Finset.Ioc (n / 2) n, m) +
            2 * (∑ j ∈ Finset.Ico 2 n, (j + 1)) ≤ 3 * n * n := by
          have arith : ∀ e r A B T : ℕ, r ≤ 1 → 3 ≤ e →
              A * 2 = 2 * (e + 1 + r + 1) * (e + 2 + 1) + (e + 1 + r + 1) * (e + 1 + r) →
              B * 2 = 6 * (2 * e + 1 + r + 1) + (2 * e + 1 + r + 1) * (2 * e + 1 + r) →
              T * 2 = (2 * e + 4 + r) * (2 * e + 4 + r + 1) →
              2 * T + 2 * A + 2 * B ≤ 3 * (2 * e + 4 + r) * (2 * e + 4 + r) := by
            intro e r A B T hr he hA hB hT
            have hsq : 3 * e ≤ e * e := Nat.mul_le_mul_right e he
            rcases (show r = 0 ∨ r = 1 by omega) with rfl | rfl
            · ring_nf at hA hB hT hsq ⊢
              omega
            · ring_nf at hA hB hT hsq ⊢
              omega
          obtain ⟨e, he⟩ : ∃ e, n / 2 = e + 2 := ⟨n / 2 - 2, by omega⟩
          obtain ⟨r, hr1, hr⟩ : ∃ r, r ≤ 1 ∧ n = 2 * e + 4 + r := ⟨n - (2 * e + 4), by omega, by omega⟩
          have hc' : c = e + 1 + r := by omega
          have hd' : d = 2 * e + 1 + r := by omega
          rw [he, hc'] at hS1
          rw [hd'] at hS2
          have hT' : n * (n + 1) / 2 * 2 = (2 * e + 4 + r) * (2 * e + 4 + r + 1) := by rw [hT, hr]
          have := arith e r _ _ _ hr1 (by omega) hS1 hS2 hT'
          rw [he]
          rw [hr] at this ⊢
          exact this
        calc (2 ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
                ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3))) ^ 2
            ≤ (2 ^ (n * (n + 1) / 2) * (2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) *
                2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1)))) ^ 2 := by gcongr
          _ = 2 ^ (2 * (n * (n + 1) / 2) + 2 * (∑ m ∈ Finset.Ioc (n / 2) n, m) +
                2 * (∑ j ∈ Finset.Ico 2 n, (j + 1))) := by
            rw [← pow_add, ← pow_add, ← pow_mul]; congr 1; ring
          _ ≤ 2 ^ (3 * n * n) := Nat.pow_le_pow_right (by norm_num) hexp
    exact_mod_cast key
  have hqx : ∃ z : ℤ, (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) *
      ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k := by
    have hterm : ∀ k ∈ Finset.range (n + 1), ∃ z : ℤ,
        (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) * (Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) := by
      intro k hk
      have hkn : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
      obtain ⟨a, ha⟩ := gauss n k
      obtain ⟨b, hb⟩ := gauss (2 * n - k) n
      obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hkn
      have hexp : (k + m) * (k + m + 1) / 2 + k * (k - 1) / 2 = m * (m + 1) / 2 + (k + m) * k := by
        have e1 : 2 * ((k + m) * (k + m + 1) / 2) = (k + m) * (k + m + 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
        have e2 : 2 * (k * (k - 1) / 2) = k * (k - 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_pred_self _)
        have e3 : 2 * (m * (m + 1) / 2) = m * (m + 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
        rcases k with _ | j
        · simp
        · simp only [Nat.add_sub_cancel] at e2 ⊢
          ring_nf at e1 e2 e3 ⊢
          omega
      refine ⟨(-1) ^ k * 3 ^ k * 2 ^ (m * (m + 1) / 2) * a * b, ?_⟩
      have hpow : (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2) =
          (2 : ℚ) ^ (m * (m + 1) / 2) * ((2 : ℚ) ^ (k + m)) ^ k := by
        rw [← pow_add, ← pow_mul, ← pow_add, hexp]
      have h2 : ((2 : ℚ) ^ (k + m)) ≠ 0 := by positivity
      rw [hQc]
      simp only []
      rw [← ha, ← hb]
      push_cast
      rw [div_pow, mul_div_assoc']
      field_simp
      linear_combination -(a : ℚ) * b * hpow
    choose! g hg using hterm
    refine ⟨∑ k ∈ Finset.range (n + 1), g k, ?_⟩
    push_cast
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl (fun k hk => hg k hk)
  have hE : 0 < (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) := by
    split_ifs
    · norm_num
    · norm_num
    · refine Nat.mul_pos (Finset.prod_pos fun m hm => ?_) (Finset.prod_pos fun j hj => ?_)
      · have hm1 : 1 ≤ m := by
          have := (Finset.mem_Ioc.mp hm).1
          omega
        have : 2 ≤ 2 ^ m := by
          calc 2 = 2 ^ 1 := by norm_num
            _ ≤ 2 ^ m := Nat.pow_le_pow_right (by norm_num) hm1
        omega
      · have hj2 : 2 ≤ j := (Finset.mem_Ico.mp hj).1
        have : 8 ≤ 2 ^ (j + 1) := by
          calc 8 = 2 ^ 3 := by norm_num
            _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
        omega
  have hAqint : ∃ z : ℤ, (z : ℚ) = ((2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
        (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℕ) : ℚ) * Aq n := by
    by_cases h5 : n = 5
    · subst h5
      refine ⟨1380067124193819576, ?_⟩
      rw [if_pos rfl]
      subst hQc hQx hAq
      decide +kernel
    · by_cases h7 : n = 7
      · subst h7
        refine ⟨674036225808261890798679141926088, ?_⟩
        rw [if_neg (by norm_num), if_pos rfl]
        subst hQc hQx hAq
        decide +kernel
      · rw [if_neg h5, if_neg h7]
        have hM : ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) : ℕ) : ℚ) =
            ∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1) := by
          rw [Nat.cast_prod]
          refine Finset.prod_congr rfl (fun m _ => ?_)
          rw [Nat.cast_sub Nat.one_le_two_pow]
          push_cast
          ring
        have hC : ((∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℚ) =
            ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3) := by
          rw [Nat.cast_prod]
          refine Finset.prod_congr rfl (fun j hj => ?_)
          have hj2 : 2 ≤ j := (Finset.mem_Ico.mp hj).1
          have h3 : 3 ≤ 2 ^ (j + 1) := by
            calc 3 ≤ 2 ^ 2 := by norm_num
              _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
          rw [Nat.cast_sub h3]
          push_cast
          ring
        have hd : ((2 ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
            ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3)) : ℕ) : ℚ) =
            (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) := by
          rw [Nat.cast_mul, Nat.cast_mul, hM, hC]
          push_cast
          ring
        obtain ⟨zcn, hzcn⟩ := hcnall n
        obtain ⟨zq', hzq'⟩ := hqx
        have hQxn : Qx n = ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k := by
          rw [hQx]
        have hterm : ∀ k ∈ Finset.range (n + 1), ∃ z : ℤ,
            (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
              ((∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) := by
          intro k hk
          have hkn : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
          obtain ⟨w, hw⟩ := hcore Qc hQc n k hkn
          obtain ⟨m, hm⟩ := Nat.exists_eq_add_of_le hkn
          have hexp : n * (n + 1) / 2 + k * (k - 1) / 2 = m * (m + 1) / 2 + n * k := by
            rw [hm]
            have e1 : 2 * ((k + m) * (k + m + 1) / 2) = (k + m) * (k + m + 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
            have e2 : 2 * (k * (k - 1) / 2) = k * (k - 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_pred_self _)
            have e3 : 2 * (m * (m + 1) / 2) = m * (m + 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
            rcases k with _ | j
            · simp
            · simp only [Nat.add_sub_cancel] at e2 ⊢
              ring_nf at e1 e2 e3 ⊢
              omega
          have hpow : (2 : ℚ) ^ (n * (n + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2) =
              (2 : ℚ) ^ (m * (m + 1) / 2) * ((2 : ℚ) ^ n) ^ k := by
            rw [← pow_add, ← pow_mul, ← pow_add, hexp]
          have h2n : ((2 : ℚ) ^ n) ^ k ≠ 0 := by positivity
          refine ⟨(∏ j ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (j + 1) - 3)) * w * 3 ^ k * 2 ^ (m * (m + 1) / 2), ?_⟩
          have e1 : (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
              ((∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) =
              (∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) * 3 ^ k *
                (((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
                  ∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                  (2 : ℚ) ^ (n * (n + 1) / 2)) / ((2 : ℚ) ^ n) ^ k := by
            rw [div_pow]
            ring
          rw [e1, ← hw, show (w : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) * (2 : ℚ) ^ (n * (n + 1) / 2) =
            (w : ℚ) * ((2 : ℚ) ^ (n * (n + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2)) by ring, hpow]
          push_cast
          field_simp
        choose! g hg using hterm
        refine ⟨∑ k ∈ Finset.range (n + 1), g k +
          (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℤ) ^ m - 1)) * zq' * zcn, ?_⟩
        rw [hd, hAq]
        beta_reduce
        push_cast
        rw [mul_add, Finset.mul_sum, Finset.sum_congr rfl hg, hzcn, hzq', ← hQxn]
        ring
  obtain ⟨zq, hzq⟩ := hqx
  refine ⟨2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ), by positivity, hb, ⟨(if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) * zq, ?_⟩, hAqint⟩
  rw [hQx]
  push_cast
  rw [hzq]
  ring
