import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1050--h1-v2--h1`, `erdos-1050--h1-v2--h2`. -/

/-! Hole `hT` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h1 : Irrational (∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) := by
  sorry


/-! Hole `integrality` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h2 : ∃ (a : ℕ → ℤ) (b : ℕ → ℤ),
  ∀ (n : ℕ),
    (1 : ℕ) ≤ n →
      (↑(b n) : ℝ) * ∑' (j : ℕ), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + (1 : ℕ)))⁻¹ - (↑(a n) : ℝ) =
        (9 : ℝ) ^ n *
            (((↑(n - (2 : ℕ)).factorial : ℝ) * ∏ k ∈ Finset.Icc (1 : ℕ) n, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) *
              ∏ k ∈ Finset.Icc ((n + (1 : ℕ)) / (2 : ℕ)) n, ((1 : ℝ) - (2 : ℝ) ^ k)) *
          ∑' (j : ℕ),
            -((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑(n + j) : ℤ) + (↑n : ℤ)))⁻¹ *
              ∏ k ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)),
                ((1 : ℝ) - (2 : ℝ) ^ ((↑k : ℤ) - (↑(n + j) : ℤ))) *
                  ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑k : ℤ) + (↑(n + j) : ℤ)))⁻¹ := by
  sorry
