import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1050--h1-v2--h1`. -/

/-! Hole `hT` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h1 : Irrational (∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) := by
  sorry
