import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1050--h1-v2--h1`, `erdos-1050--h1-v2--h2`, `erdos-1050--h1-v2--h3`, `erdos-1050--h1-v2--h4`. -/

/-! Hole `hT` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h1 : Irrational (∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) := by
  sorry


/-! Hole `integrality` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h2 : ∃ (a : ℕ → ℤ) (b : ℕ → ℤ),
  ∀ (n : ℕ),
    (1 : ℕ) ≤ n →
      (↑(b n) : ℝ) * ∑' (j : ℕ), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + (1 : ℕ)))⁻¹ - (↑(a n) : ℝ) =
        (9 : ℝ) ^ n *
            (((↑(n - (2 : ℕ)).factorial : ℝ) * ∏ k ∈ Finset.Icc (1 : ℕ) n, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) *
              ∏ k ∈ Finset.Icc ((n + (1 : ℕ)) / (2 : ℕ)) n, ((1 : ℝ) - (2 : ℝ) ^ k)) *
          ∑' (j : ℕ),
            -((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑(n + j) : ℤ) + (↑n : ℤ)))⁻¹ *
              ∏ k ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)),
                ((1 : ℝ) - (2 : ℝ) ^ ((↑k : ℤ) - (↑(n + j) : ℤ))) *
                  ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑k : ℤ) + (↑(n + j) : ℤ)))⁻¹ := by
  sorry


/-! Hole `hden` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h3 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            ∀ (n : ℕ),
              ∃ (d : ℕ),
                (0 : ℕ) < d ∧
                  (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                    (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n := by
  sorry


/-! Hole `hrem` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h4 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            (∀ (n : ℕ),
                ∃ (d : ℕ),
                  (0 : ℕ) < d ∧
                    (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                      (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n) →
              ∀ (n : ℕ),
                (0 : ℝ) <
                    (↑(Qx n) : ℝ) * ((3 : ℝ) * ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) -
                      (↑(Aq n) : ℝ) ∧
                  ((↑(Qx n) : ℝ) * ((3 : ℝ) * ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) -
                          (↑(Aq n) : ℝ)) ^
                        (2 : ℕ) *
                      (2 : ℝ) ^ ((4 : ℕ) * n * n) ≤
                    (2 : ℝ) ^ ((2 : ℕ) * n + (4 : ℕ)) := by
  sorry
