import Defs.IsPrime
import Mathlib.Tactic

/-! Hole `euclid` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_2a7919a9__h2 : ∀ (l : List ℕ), (∀ x ∈ l, x ≤ l.sum) → ∃ p, l.sum < p ∧ Opn.IsPrime p := by
  intro l _
  have f1 : Nat.factorial (l.sum + 1) + 1 ≠ 1 := by
    have := Nat.factorial_pos (l.sum + 1)
    omega
  have pp : Nat.Prime (Nat.minFac (Nat.factorial (l.sum + 1) + 1)) := Nat.minFac_prime f1
  refine ⟨Nat.minFac (Nat.factorial (l.sum + 1) + 1), ?_, pp.two_le, ?_⟩
  · by_contra h
    have h₁ : Nat.minFac (Nat.factorial (l.sum + 1) + 1) ∣ Nat.factorial (l.sum + 1) :=
      Nat.dvd_factorial (Nat.minFac_pos _) (by omega)
    have h₂ : Nat.minFac (Nat.factorial (l.sum + 1) + 1) ∣ 1 :=
      (Nat.dvd_add_iff_right h₁).2 (Nat.minFac_dvd _)
    exact pp.not_dvd_one h₂
  · intro d hd
    obtain ⟨c, hc⟩ := hd
    exact (Nat.dvd_prime pp).mp ⟨c, hc⟩
