import Mathlib
import Nodes.«erdos-1094--h3».Context

open scoped Nat

/-! Hole `h_small_n` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → (2 : ℕ) * k ≤ n → n < k * k → (n.choose k).minFac > k → k ≤ K := by
  -- Konyagin's theorem, g(k) > k^3 for all large k, in the network's "bounded k" shape:
  -- a binomial coefficient C(n, k) with 2k ≤ n < k^3 whose prime factors all exceed k
  -- occurs only for bounded k. The same hole closes erdos-1094--h2--h1.
  have h_good_below_cube : ∃ K : ℕ, ∀ n k : ℕ, 0 < k → 2 * k ≤ n → n < k * k * k →
      (n.choose k).minFac > k → k ≤ K := by sorry
  -- the assembly: n < k^2 ≤ k^3.
  obtain ⟨K, hK⟩ := h_good_below_cube
  refine ⟨K, fun n k hk h2k hsq hmin => ?_⟩
  exact hK n k hk h2k (lt_of_lt_of_le hsq (by nlinarith)) hmin
