import Mathlib
import Nodes.«erdos-1094--h3».Context

open scoped Nat

/-! Hole `h_small_n` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → (2 : ℕ) * k ≤ n → n < k * k → (n.choose k).minFac > k → k ≤ K := by
  have h_sieve : ∃ K : ℕ, ∀ n k : ℕ, K < k → 2 * k ≤ n → n < k * k →
      ∃ p : ℕ, p.Prime ∧ p ≤ k ∧ n % p < k % p := by
    sorry
  obtain ⟨K, hS⟩ := h_sieve
  refine ⟨K, fun n k hk h2k hlt hmin => ?_⟩
  by_contra hKk'
  have hKk : K < k := Nat.lt_of_not_le hKk'
  obtain ⟨p, hp, hpk, hmod⟩ := hS n k hKk h2k hlt
  have hfact : Fact p.Prime := ⟨hp⟩
  have hzero : (n % p).choose (k % p) = 0 := Nat.choose_eq_zero_of_lt hmod
  have hmodeq := Choose.choose_modEq_choose_mod_mul_choose_div_nat (n := n) (k := k) (p := p)
  rw [hzero, zero_mul] at hmodeq
  have hdvd : p ∣ n.choose k := (Nat.modEq_zero_iff_dvd).1 hmodeq
  have hle : (n.choose k).minFac ≤ p := Nat.minFac_le_of_dvd hp.two_le hdvd
  omega
