import Mathlib

open scoped ArithmeticFunction.omega

/-! Hole `hB` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1 :
    (∑' n : ℕ, (ω n : ℝ) / 2 ^ n = ∑' p : Nat.Primes, (1 : ℝ) / (2 ^ (p : ℕ) - 1)) →
    ∀ b : ℕ, 0 < b → ∃ N : ℕ, ∀ z : ℤ,
      (b : ℝ) * ∑' j : ℕ, (ω (N + 1 + j) : ℝ) / 2 ^ (j + 1) ≠ (z : ℝ) := by
  -- annex: a120bc75bf16a798687d3a33a004688c9af9c1ad9d799de8ab0dfa21fc3b3e30
  intro _hL
  have hsplit : ∀ N k : ℕ,
      ∑' j : ℕ, (ω (N + 1 + j) : ℝ) / 2 ^ (j + 1)
        = ∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) / 2 ^ (j + 1)
          + (∑' j : ℕ, (ω (N + k + 1 + j) : ℝ) / 2 ^ (j + 1)) / 2 ^ k := sorry
  have hpos : ∀ M : ℕ, 0 < ∑' j : ℕ, (ω (M + 1 + j) : ℝ) / 2 ^ (j + 1) := sorry
  have hbound : ∀ M : ℕ,
      ∑' j : ℕ, (ω (M + 1 + j) : ℝ) / 2 ^ (j + 1) ≤ Real.logb 2 ((M : ℝ) + 1) + 1 := sorry
  have hcrux : ∀ b : ℕ, 0 < b → ∃ N k : ℕ,
      (((b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) % 2 ^ k : ℕ) : ℝ)
        + (b : ℝ) * (Real.logb 2 (((N + k : ℕ) : ℝ) + 1) + 1) < (2 : ℝ) ^ k := sorry
  intro b hb
  obtain ⟨N, k, hck⟩ := hcrux b hb
  refine ⟨N, fun z hz => ?_⟩
  have hbR : (0 : ℝ) < (b : ℝ) := by exact_mod_cast hb
  have h2k : (0 : ℝ) < (2 : ℝ) ^ k := by positivity
  -- the finite head, rescaled by 2^k, is the integer sum of the crux
  have hhead : (∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) / 2 ^ (j + 1)) * 2 ^ k
      = ∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) * 2 ^ (k - 1 - j) := by
    rw [Finset.sum_mul]
    refine Finset.sum_congr rfl (fun j hj => ?_)
    have hjk : j + 1 + (k - 1 - j) = k := by
      have := Finset.mem_range.1 hj
      omega
    have h2 : (2 : ℝ) ^ k = 2 ^ (j + 1) * 2 ^ (k - 1 - j) := by rw [← pow_add, hjk]
    have h3 : (2 : ℝ) ^ (j + 1) ≠ 0 := by positivity
    rw [h2]
    field_simp
  have hT'pos := hpos (N + k)
  have hT'le := hbound (N + k)
  rw [hsplit N k] at hz
  generalize (∑' j : ℕ, (ω (N + k + 1 + j) : ℝ) / 2 ^ (j + 1)) = T' at hz hT'pos hT'le
  -- multiply through by 2^k
  have hkey : (b : ℝ) * (∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) * 2 ^ (k - 1 - j))
      + (b : ℝ) * T' = ((z * 2 ^ k : ℤ) : ℝ) := by
    rw [← hhead]
    push_cast
    rw [← hz]
    field_simp
  have hA : ((∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j) : ℕ) : ℝ)
      = ∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) * 2 ^ (k - 1 - j) := by
    push_cast
    rfl
  have hdm := Nat.div_add_mod (b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) (2 ^ k)
  have hdmR : (2 : ℝ) ^ k * (((b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) / 2 ^ k : ℕ) : ℝ)
      + (((b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) % 2 ^ k : ℕ) : ℝ)
      = (b : ℝ) * ∑ j ∈ Finset.range k, (ω (N + 1 + j) : ℝ) * 2 ^ (k - 1 - j) := by
    rw [← hA]
    exact_mod_cast hdm
  generalize ((b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) % 2 ^ k) = r at hck hdmR
  generalize ((b * ∑ j ∈ Finset.range k, ω (N + 1 + j) * 2 ^ (k - 1 - j)) / 2 ^ k) = q at hdmR
  have hr : (0 : ℝ) ≤ (r : ℝ) := Nat.cast_nonneg r
  have hbT : 0 < (b : ℝ) * T' := mul_pos hbR hT'pos
  have hbT2 : (b : ℝ) * T' ≤ (b : ℝ) * (Real.logb 2 (((N + k : ℕ) : ℝ) + 1) + 1) :=
    mul_le_mul_of_nonneg_left hT'le hbR.le
  have hlo : ((((q : ℤ)) * 2 ^ k : ℤ) : ℝ) < ((z * 2 ^ k : ℤ) : ℝ) := by
    rw [← hkey]
    push_cast
    linarith
  have hhi : ((z * 2 ^ k : ℤ) : ℝ) < ((((q : ℤ) + 1) * 2 ^ k : ℤ) : ℝ) := by
    rw [← hkey]
    push_cast
    linarith
  have hp : (0 : ℤ) < 2 ^ k := by positivity
  have h1 : (q : ℤ) < z := lt_of_mul_lt_mul_right (Int.cast_lt.1 hlo) hp.le
  have h2 : z < (q : ℤ) + 1 := lt_of_mul_lt_mul_right (Int.cast_lt.1 hhi) hp.le
  omega
