import Mathlib
import Nodes.«erdos-1094--h2».Context

open scoped Nat

/-! Hole `h_large_n` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h2 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → k * k ≤ n → (n.choose k).minFac > n / k → k ≤ K := by
  -- annex: 301ade26e4fe34edb5cfb1186ec23735a245ff1d1027f281d716cb784fa2458c
  have hall : (∃ K : ℕ, ∀ n k : ℕ, 0 < k → k * k ≤ n → n < k * k * k →
        (n.choose k).minFac > n / k → k ≤ K) ∧
      (∃ K : ℕ, ∀ n k : ℕ, 0 < k → k * k * k ≤ n →
        (n.choose k).minFac > n / k → k ≤ K) := by
    refine ⟨?_, ?_⟩
    · have h_lo : ∃ K : ℕ, ∀ n k : ℕ, 0 < k → k * k ≤ n → n < k * k * k →
          (n.choose k).minFac > n / k → k ≤ K := by sorry
      exact h_lo
    · have h_hi : ∃ K : ℕ, ∀ n k : ℕ, 0 < k → k * k * k ≤ n →
          (n.choose k).minFac > n / k → k ≤ K := by sorry
      exact h_hi
  obtain ⟨⟨K₁, hK₁⟩, ⟨K₂, hK₂⟩⟩ := hall
  refine ⟨max K₁ K₂, fun n k hk hn hex => ?_⟩
  by_cases hc : n < k * k * k
  · exact le_trans (hK₁ n k hk hn hc hex) (le_max_left _ _)
  · exact le_trans (hK₂ n k hk (Nat.le_of_not_lt hc) hex) (le_max_right _ _)
