import Mathlib
import Nodes.«erdos-1050--h1-v2--h2».Context

/-! Hole `integrality` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h2 : ∃ (a : ℕ → ℤ) (b : ℕ → ℤ),
  ∀ (n : ℕ),
    (1 : ℕ) ≤ n →
      (↑(b n) : ℝ) * ∑' (j : ℕ), ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + (1 : ℕ)))⁻¹ - (↑(a n) : ℝ) =
        (9 : ℝ) ^ n *
            (((↑(n - (2 : ℕ)).factorial : ℝ) * ∏ k ∈ Finset.Icc (1 : ℕ) n, ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) *
              ∏ k ∈ Finset.Icc ((n + (1 : ℕ)) / (2 : ℕ)) n, ((1 : ℝ) - (2 : ℝ) ^ k)) *
          ∑' (j : ℕ),
            -((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑(n + j) : ℤ) + (↑n : ℤ)))⁻¹ *
              ∏ k ∈ Finset.Icc (1 : ℕ) (n - (1 : ℕ)),
                ((1 : ℝ) - (2 : ℝ) ^ ((↑k : ℤ) - (↑(n + j) : ℤ))) *
                  ((1 : ℝ) - (8 / 3 : ℝ) * (2 : ℝ) ^ ((↑k : ℤ) + (↑(n + j) : ℤ)))⁻¹ := by
  -- E(n) = beta0(n) * z - alpha0(n) by partial fractions in x = 2^m (proved below, via Lagrange
  -- interpolation); b(n) = 9^n W(n) beta0(n) is an integer (proved below); a(n) = 9^n W(n) alpha0(n)
  -- is the one hole. Informal argument: annex 959e0d5b10994049b5f27ad77d9d2d8535be9f817bf4de69d747a1e05b9db44b on this node.
  -- Borwein Lemma 3 (numerator integrality): the one hole.
  have numerator_integral : ∃ a : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (a n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) - ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := sorry
  obtain ⟨a, ha⟩ := numerator_integral
  -- Denominator integrality (proved): 3^(n-1) beta0(n) is a coefficient of an integer polynomial.
  have hden : ∃ b : ℕ → ℤ, ∀ n : ℕ, 1 ≤ n → (b n : ℝ) = (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := by
    have key : ∀ n : ℕ, 1 ≤ n → ∃ z : ℤ, (z : ℝ) = (3 : ℝ) ^ (n - 1) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) := by
      intro n hn
      have hr0 : ∀ k : ℕ, ((8 : ℝ) * 2 ^ k) ≠ 0 := fun k => by positivity
      have hvinj : Set.InjOn (fun k : ℕ => ((8 : ℝ) * 2 ^ k)⁻¹) (Finset.Icc 1 n : Set ℕ) := by
        intro a _ b _ hab
        have h : (2 : ℝ) ^ a = 2 ^ b := by
          have := inv_injective hab
          exact mul_left_cancel₀ (by norm_num : (8 : ℝ) ≠ 0) this
        exact pow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) h
      -- (1) the polynomial partial-fraction identity, by agreement at the n nodes 1/r_k
      have hid : (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))) = ∑ k ∈ Finset.Icc 1 n, Polynomial.C ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).eval ((8 : ℝ) * 2 ^ k)⁻¹ * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)))⁻¹) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X)) := by
        refine Polynomial.eq_of_natDegree_lt_card_of_eval_eq' _ _ ((Finset.Icc 1 n).image (fun k : ℕ => ((8 : ℝ) * 2 ^ k)⁻¹)) ?_ ?_
        · intro y hy
          obtain ⟨k, hk, rfl⟩ := Finset.mem_image.mp hy
          rw [Polynomial.eval_finsetSum, Finset.sum_eq_single_of_mem k hk]
          · rw [Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_prod]
            simp only [Polynomial.eval_sub, Polynomial.eval_one, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_X]
            have hne : ∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)) ≠ 0 := by
              refine Finset.prod_ne_zero_iff.mpr (fun j hj => ?_)
              have hjk : j ≠ k := Finset.ne_of_mem_erase hj
              intro h0
              have : ((8 : ℝ) * 2 ^ j) = ((8 : ℝ) * 2 ^ k) := by
                have := hr0 k
                field_simp at h0
                linarith
              exact hjk (pow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) (mul_left_cancel₀ (by norm_num : (8 : ℝ) ≠ 0) this))
            rw [mul_assoc, ← Finset.prod_congr rfl (fun j _ => by rw [div_eq_mul_inv, mul_comm (((8 : ℝ) * 2 ^ j)) _] : ∀ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)) = 1 - ((8 : ℝ) * 2 ^ j) * ((8 : ℝ) * 2 ^ k)⁻¹), inv_mul_cancel₀ hne, mul_one]
          · intro i hi hik
            rw [Polynomial.eval_mul, Polynomial.eval_prod]
            refine mul_eq_zero_of_right _ (Finset.prod_eq_zero (i := k) (Finset.mem_erase.mpr ⟨Ne.symm hik, hk⟩) ?_)
            simp only [Polynomial.eval_sub, Polynomial.eval_one, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_X]
            rw [mul_inv_cancel₀ (hr0 k), sub_self]
        · rw [Finset.card_image_of_injOn hvinj, Nat.card_Icc]
          have hQdeg : (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).natDegree ≤ n - 1 := by
            rw [Polynomial.natDegree_neg]
            refine (Polynomial.natDegree_prod_le _ _).trans ?_
            refine (Finset.sum_le_sum (g := fun _ => 1) (fun t _ => ?_)).trans (le_of_eq ?_)
            · compute_degree
            · simp only [Finset.sum_const, smul_eq_mul, mul_one, Nat.card_Icc]; omega
          have hRdeg : (∑ k ∈ Finset.Icc 1 n, Polynomial.C ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).eval ((8 : ℝ) * 2 ^ k)⁻¹ * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)))⁻¹) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X))).natDegree ≤ n - 1 := by
            refine Polynomial.natDegree_sum_le_of_forall_le _ _ (fun k hk => ?_)
            refine (Polynomial.natDegree_C_mul_le _ _).trans ((Polynomial.natDegree_prod_le _ _).trans ?_)
            refine (Finset.sum_le_sum (g := fun _ => 1) (fun j _ => ?_)).trans (le_of_eq ?_)
            · compute_degree
            · simp only [Finset.sum_const, smul_eq_mul, mul_one]
              rw [Finset.card_erase_of_mem hk, Nat.card_Icc]; omega
          omega
      -- (2) coefficient n - 1 of T_k * P is r_k ^ (n - 1)
      have hU : ∀ (S : Finset ℕ), ∀ d < n, (∏ j ∈ S, (1 - (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ n)).coeff d = if d = 0 then 1 else 0 := by
        intro S
        induction S using Finset.induction_on with
        | empty => intro d hd; simp [Polynomial.coeff_one]
        | insert a S ha ih =>
          intro d hd
          rw [Finset.prod_insert ha, sub_mul, one_mul, Polynomial.coeff_sub, mul_pow, ← Polynomial.C_pow, mul_assoc,
            Polynomial.coeff_C_mul, Polynomial.coeff_X_pow_mul', if_neg (by omega), mul_zero, sub_zero, ih d hd]
      have hG : ∀ k : ℕ, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ k) * Polynomial.X) ^ i).coeff (n - 1) = ((8 : ℝ) * 2 ^ k) ^ (n - 1) := by
        intro k
        simp only [mul_pow, ← Polynomial.C_pow, Polynomial.finsetSum_coeff, Polynomial.coeff_C_mul_X_pow]
        rw [Finset.sum_ite_eq (Finset.range n) (n - 1), if_pos (Finset.mem_range.mpr (by omega))]
      have hTP : ∀ k ∈ Finset.Icc 1 n, ((∏ j ∈ (Finset.Icc 1 n).erase k, (1 - Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X)) * (∏ j ∈ Finset.Icc 1 n, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i))).coeff (n - 1) = ((8 : ℝ) * 2 ^ k) ^ (n - 1) := by
        intro k hk
        have hsplitP : (∏ j ∈ Finset.Icc 1 n, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i)) = (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ k) * Polynomial.X) ^ i) * ∏ j ∈ (Finset.Icc 1 n).erase k, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i) :=
          (Finset.mul_prod_erase _ (fun j => (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i)) hk).symm
        have hprod : (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X)) * (∏ j ∈ Finset.Icc 1 n, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i)) = (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ k) * Polynomial.X) ^ i) * ∏ j ∈ (Finset.Icc 1 n).erase k, (1 - (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ n) := by
          rw [hsplitP, mul_left_comm, ← Finset.prod_mul_distrib]
          congr 1
          refine Finset.prod_congr rfl (fun j _ => ?_)
          rw [mul_neg_geom_sum]
        obtain ⟨E, hE⟩ : Polynomial.X ^ n ∣ (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ n)) - 1 :=
          Polynomial.X_pow_dvd_iff.mpr (fun d hd => by
          rw [Polynomial.coeff_sub, hU _ d hd, Polynomial.coeff_one]; split_ifs <;> simp_all)
        rw [hprod, show ∏ j ∈ (Finset.Icc 1 n).erase k, (1 - (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ n) = 1 + Polynomial.X ^ n * E by rw [← hE]; ring,
          mul_add, mul_one, Polynomial.coeff_add, mul_left_comm, Polynomial.coeff_X_pow_mul', if_neg (by omega), add_zero, hG]
      -- (3) so coefficient n - 1 of Qt * P is the sum of C_k r_k^(n-1)
      have hQP : ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i))).coeff (n - 1) = ∑ k ∈ Finset.Icc 1 n, ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).eval ((8 : ℝ) * 2 ^ k)⁻¹ * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)))⁻¹) * ((8 : ℝ) * 2 ^ k) ^ (n - 1) := by
        nth_rw 1 [hid]
        rw [Finset.sum_mul, Polynomial.finsetSum_coeff]
        refine Finset.sum_congr rfl (fun k hk => ?_)
        rw [mul_assoc, Polynomial.coeff_C_mul, hTP k hk]
      -- (4) and it is an integer, since Qt * P has integer coefficients
      have hmap : (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, (∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℝ) * 2 ^ j) * Polynomial.X) ^ i)) = Polynomial.map (Int.castRingHom ℝ) ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℤ) * Polynomial.X - Polynomial.C ((2 : ℤ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, ∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℤ) * 2 ^ j) * Polynomial.X) ^ i)) := by
        simp [Polynomial.map_prod, Polynomial.map_sum, Polynomial.C_mul, Polynomial.C_pow, map_ofNat]
      -- (5) C_k r_k^(n-1) = 3^(n-1) A(n,k)
      have hcard : (Finset.Icc 1 (n - 1)).card = n - 1 := by rw [Nat.card_Icc]; omega
      have hterm : ∀ k ∈ Finset.Icc 1 n, ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℝ) * Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).eval ((8 : ℝ) * 2 ^ k)⁻¹ * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k)))⁻¹) * ((8 : ℝ) * 2 ^ k) ^ (n - 1) = (3 : ℝ) ^ (n - 1) * (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) := by
        intro k hk
        have hq : ∀ t : ℕ, (3 : ℝ) * ((8 : ℝ) * 2 ^ k)⁻¹ - 2 ^ t = ((8 : ℝ) * 2 ^ k)⁻¹ * (3 * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) := fun t => by
          have := hr0 k
          rw [pow_add]; field_simp
        have hw : ∀ j : ℕ, ((8 : ℝ) * 2 ^ j) / ((8 : ℝ) * 2 ^ k) = (2 : ℝ) ^ ((j : ℤ) - (k : ℤ)) := fun j => by
          rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast]
          field_simp
        have hrr : (((8 : ℝ) * 2 ^ k)⁻¹) ^ (n - 1) * ((8 : ℝ) * 2 ^ k) ^ (n - 1) = 1 := by
          rw [← mul_pow, inv_mul_cancel₀ (hr0 k), one_pow]
        simp only [Polynomial.eval_neg, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_mul, Polynomial.eval_C,
          Polynomial.eval_X]
        rw [Finset.prod_congr rfl (fun t _ => hq t), Finset.prod_mul_distrib, Finset.prod_mul_distrib, Finset.prod_const,
          Finset.prod_const, hcard]
        simp only [hw]
        linear_combination (-((3 : ℝ) ^ (n - 1) * ∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) *
          (∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - (k : ℤ))))⁻¹) * hrr
      refine ⟨((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℤ) * Polynomial.X - Polynomial.C ((2 : ℤ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, ∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℤ) * 2 ^ j) * Polynomial.X) ^ i)).coeff (n - 1), ?_⟩
      have hc : ((((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℤ) * Polynomial.X - Polynomial.C ((2 : ℤ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, ∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℤ) * 2 ^ j) * Polynomial.X) ^ i)).coeff (n - 1) : ℤ) : ℝ) = (Polynomial.map (Int.castRingHom ℝ) ((-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.C (3 : ℤ) * Polynomial.X - Polynomial.C ((2 : ℤ) ^ t))) * (∏ j ∈ Finset.Icc 1 n, ∑ i ∈ Finset.range n, (Polynomial.C ((8 : ℤ) * 2 ^ j) * Polynomial.X) ^ i))).coeff (n - 1) := by
        rw [Polynomial.coeff_map]; simp
      rw [hc, ← hmap, hQP, Finset.mul_sum]
      exact Finset.sum_congr rfl hterm
    have hW3 : ∀ n : ℕ, ∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = (∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k)) * ((3 : ℝ) ^ n)⁻¹ := by
      intro n
      rw [Finset.prod_congr rfl (fun k _ => (by ring : (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k) = ((3 : ℝ) - 8 * 2 ^ k) * (3 : ℝ)⁻¹)),
        Finset.prod_mul_distrib, Finset.prod_const, Nat.card_Icc, Nat.add_sub_cancel, inv_pow]
    refine ⟨fun n => if h : 1 ≤ n then 3 * (Nat.factorial (n - 2) : ℤ) * (∏ k ∈ Finset.Icc 1 n, ((3 : ℤ) - 8 * 2 ^ k)) *
        (∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℤ) - 2 ^ k)) * Classical.choose (key n h) else 0, fun n hn => ?_⟩
    simp only [dif_pos hn]
    push_cast
    rw [Classical.choose_spec (key n hn), hW3 n]
    have h9 : (9 : ℝ) ^ n = 3 * (3 : ℝ) ^ (n - 1) * (3 : ℝ) ^ n := by
      rw [show (9 : ℝ) = 3 * 3 by norm_num, mul_pow, mul_comm (3 : ℝ) _, ← pow_succ, Nat.sub_add_cancel hn]
    have h3 : ((3 : ℝ) ^ n)⁻¹ * (3 : ℝ) ^ n = 1 := inv_mul_cancel₀ (by positivity)
    rw [h9]
    linear_combination (-(3 : ℝ) * (Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, ((3 : ℝ) - 8 * 2 ^ k)) *
        (∏ k ∈ Finset.Icc ((n + 1) / 2) n, ((1 : ℝ) - 2 ^ k)) * ((3 : ℝ) ^ (n - 1) * (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))))) * h3
  obtain ⟨b, hb⟩ := hden
  -- The partial-fraction identity at x = 2^m (proved).
  have hpf : ∀ n : ℕ, 1 ≤ n → ∀ m : ℕ, 1 ≤ m → (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) := by
    intro n hn m hm
    -- General partial fractions, from Mathlib's Lagrange interpolation.
    have lag : ∀ (s : Finset ℕ) (p : ℕ → ℝ) (Q : Polynomial ℝ), (∀ k ∈ s, p k ≠ 0) → Set.InjOn p s →
      Q.degree < s.card → ∀ x : ℝ, (∀ k ∈ s, 1 - p k * x ≠ 0) →
      Q.eval x * ∏ k ∈ s, (1 - p k * x)⁻¹ =
        ∑ k ∈ s, Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (1 - p j / p k))⁻¹ * (1 - p k * x)⁻¹ := by
      intro s p Q hp hinj hdeg x hx
      have hinj' : Set.InjOn (fun k => (p k)⁻¹) s := by
        intro a ha b hb hab
        exact hinj ha hb (inv_injective hab)
      have hxv : ∀ k ∈ s, x ≠ (p k)⁻¹ := by
        intro k hk hxk
        apply hx k hk
        rw [hxk, mul_inv_cancel₀ (hp k hk), sub_self]
      have hQ := Lagrange.eq_interpolate hinj' hdeg
      have hev := Lagrange.eval_interpolate_not_at_node (s := s) (v := fun k => (p k)⁻¹) (fun i => Q.eval (p i)⁻¹) hxv
      rw [← hQ, Lagrange.eval_nodal] at hev
      have hfac : ∀ k ∈ s, (1 - p k * x)⁻¹ = (x - (p k)⁻¹)⁻¹ * (-(p k)⁻¹) := by
        intro k hk
        have h1 := hp k hk
        have h3 : (x - (p k)⁻¹) * (-(p k)) = 1 - p k * x := by
          rw [sub_mul, mul_neg, mul_neg, inv_mul_cancel₀ h1]; ring
        rw [← h3, mul_inv, inv_neg]
      rw [Finset.prod_congr rfl hfac, Finset.prod_mul_distrib, hev]
      have hne : ∏ i ∈ s, (x - (p i)⁻¹) ≠ 0 := Finset.prod_ne_zero_iff.mpr (fun i hi => sub_ne_zero.mpr (hxv i hi))
      rw [Finset.prod_inv_distrib, mul_assoc, ← mul_assoc (∑ i ∈ s, _), mul_comm (∑ i ∈ s, _), ← mul_assoc, ← mul_assoc,
        mul_inv_cancel₀ hne, one_mul, Finset.sum_mul]
      refine Finset.sum_congr rfl (fun k hk => ?_)
      rw [Lagrange.nodalWeight, ← Finset.mul_prod_erase s (fun i => -(p i)⁻¹) hk]
      have hj : ∀ j ∈ s.erase k, ((p k)⁻¹ - (p j)⁻¹)⁻¹ * -(p j)⁻¹ = (1 - p j / p k)⁻¹ := by
        intro j hj
        have hjs := Finset.mem_of_mem_erase hj
        have hjk := Finset.ne_of_mem_erase hj
        have hpj := hp j hjs
        have hpk := hp k hk
        have hne : p j ≠ p k := fun h => hjk (hinj hjs hk h)
        have hsub : p k - p j ≠ 0 := sub_ne_zero.mpr (Ne.symm hne)
        field_simp
        ring
      calc (∏ j ∈ s.erase k, ((p k)⁻¹ - (p j)⁻¹)⁻¹) * (x - (p k)⁻¹)⁻¹ * Q.eval (p k)⁻¹ *
            (-(p k)⁻¹ * ∏ j ∈ s.erase k, -(p j)⁻¹)
          = Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (((p k)⁻¹ - (p j)⁻¹)⁻¹ * -(p j)⁻¹)) * ((x - (p k)⁻¹)⁻¹ * -(p k)⁻¹) := by
            rw [Finset.prod_mul_distrib]; ring
        _ = Q.eval (p k)⁻¹ * (∏ j ∈ s.erase k, (1 - p j / p k))⁻¹ * (1 - p k * x)⁻¹ := by
            rw [Finset.prod_congr rfl hj, ← Finset.prod_inv_distrib, hfac k hk]
    have hx2 : (2 : ℝ) ≤ (2 : ℝ) ^ m := by
      calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
        _ ≤ 2 ^ m := pow_le_pow_right₀ (by norm_num) hm
    have hx0 : (2 : ℝ) ^ m ≠ 0 := by positivity
    have hp0 : ∀ k : ℕ, (8 / 3 : ℝ) * 2 ^ k ≠ 0 := fun k => by positivity
    have hpx : ∀ k : ℕ, 1 - (8 / 3 : ℝ) * 2 ^ k * 2 ^ m ≠ 0 := by
      intro k
      have h1 : (1 : ℝ) ≤ 2 ^ k := one_le_pow₀ (by norm_num)
      nlinarith
    have hinj : Set.InjOn (fun k : ℕ => (8 / 3 : ℝ) * 2 ^ k) (Finset.Icc 1 n : Set ℕ) := by
      intro a _ b _ hab
      have h : (2 : ℝ) ^ a = 2 ^ b := by
        have := hab; simp only at this
        exact mul_left_cancel₀ (by norm_num : (8 / 3 : ℝ) ≠ 0) this
      exact pow_right_injective₀ (by norm_num : (0 : ℝ) < 2) (by norm_num) h
    have hdeg : (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.X - Polynomial.C ((2 : ℝ) ^ t))).degree < ((Finset.Icc 1 n).card : WithBot ℕ) := by
      rw [Polynomial.degree_neg, Polynomial.degree_prod]
      simp only [Polynomial.degree_X_sub_C, Finset.sum_const, Nat.card_Icc]
      rw [show n - 1 + 1 - 1 = n - 1 by omega, show n + 1 - 1 = n by omega, nsmul_one]
      exact_mod_cast (by omega : n - 1 < n)
    have hL := lag (Finset.Icc 1 n) (fun k => (8 / 3 : ℝ) * 2 ^ k) (-∏ t ∈ Finset.Icc 1 (n - 1), (Polynomial.X - Polynomial.C ((2 : ℝ) ^ t)))
      (fun k _ => hp0 k) hinj hdeg ((2 : ℝ) ^ m) (fun k _ => hpx k)
    simp only [Polynomial.eval_neg, Polynomial.eval_prod, Polynomial.eval_sub, Polynomial.eval_X, Polynomial.eval_C] at hL
    have hcard : (Finset.Icc 1 (n - 1)).card = n - 1 := by rw [Nat.card_Icc]; omega
    -- geometric sums
    have hgeo : ∀ u : ℝ, u ≠ 0 → 1 - u ≠ 0 → ∀ N : ℕ, (1 - u)⁻¹ + ∑ i ∈ Finset.Icc 1 N, (u ^ i)⁻¹ = (u ^ N)⁻¹ * (1 - u)⁻¹ := by
      intro u hu hu1 N
      induction N with
      | zero => simp
      | succ N ih =>
        rw [Finset.sum_Icc_succ_top (by omega), ← add_assoc, ih]
        have hN : u ^ N ≠ 0 := pow_ne_zero _ hu
        field_simp
        ring
    -- the left side, in terms of the Lagrange data
    have hz1 : ∀ k : ℕ, (2 : ℝ) ^ ((k : ℤ) - (m : ℤ)) = 2 ^ k * ((2 : ℝ) ^ m)⁻¹ := fun k => by
      rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast, div_eq_mul_inv]
    have hz2 : ∀ k : ℕ, (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℤ)) = ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m := fun k => by
      rw [zpow_add₀ two_ne_zero, zpow_natCast, zpow_natCast, mul_assoc]
    have hz3 : (8 / 3 : ℝ) * (2 : ℝ) ^ ((m : ℤ) + (n : ℤ)) = ((8 / 3 : ℝ) * 2 ^ n) * (2 : ℝ) ^ m := by
      rw [zpow_add₀ two_ne_zero, zpow_natCast, zpow_natCast, mul_comm ((2 : ℝ) ^ m), mul_assoc]
    have hsplit : ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹ = (∏ k ∈ Finset.Icc 1 (n - 1), (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) * (1 - ((8 / 3 : ℝ) * 2 ^ n) * (2 : ℝ) ^ m)⁻¹ := by
      have hn' : n = n - 1 + 1 := by omega
      conv_lhs => rw [hn']
      rw [Finset.prod_Icc_succ_top (by omega), ← hn']
    have hfac : ∀ k : ℕ, 1 - 2 ^ k * ((2 : ℝ) ^ m)⁻¹ = ((2 : ℝ) ^ m)⁻¹ * ((2 : ℝ) ^ m - (2 : ℝ) ^ k) := fun k => by
      rw [mul_sub, inv_mul_cancel₀ hx0]; ring
    have hLHS : (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * ((-∏ t ∈ Finset.Icc 1 (n - 1), ((2 : ℝ) ^ m - (2 : ℝ) ^ t)) * ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
      simp only [hz1, hz2, hz3]
      rw [Finset.prod_mul_distrib, hsplit, Finset.prod_congr rfl (fun k _ => hfac k), Finset.prod_mul_distrib,
        Finset.prod_const, hcard, inv_pow]
      ring
    -- the right side
    have hpk : ∀ k : ℕ, (8 / 3 : ℝ) * 2 ^ (k + m) = ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m := fun k => by rw [pow_add, mul_assoc]
    have hswap : ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹ = ∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ∑ i ∈ Finset.Icc 1 (n - 1), ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ i)⁻¹ := by
      simp only [Finset.sum_mul, Finset.mul_sum]
      rw [Finset.sum_comm]
      refine Finset.sum_congr rfl (fun k _ => Finset.sum_congr rfl (fun i _ => ?_))
      rw [mul_pow, mul_inv]; ring
    have hRHS : ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
      simp only [hpk]
      rw [hswap, ← Finset.sum_add_distrib]
      refine Finset.sum_congr rfl (fun k hk => ?_)
      rw [← mul_add, hgeo _ (mul_ne_zero (hp0 k) hx0) (hpx k) (n - 1)]
      ring
    -- matching the coefficients
    have hcoef : ∀ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * 2 ^ k) ^ (n - 1))⁻¹ = (-∏ t ∈ Finset.Icc 1 (n - 1), (((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t)) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k)))⁻¹ := by
      intro k hk
      have hq : ∀ t : ℕ, ((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t = ((8 / 3 : ℝ) * 2 ^ k)⁻¹ * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k)) := fun t => by
        rw [mul_sub, mul_one, pow_add, show ((8 / 3 : ℝ) * 2 ^ k)⁻¹ * ((8 / 3 : ℝ) * (2 ^ t * 2 ^ k)) = 2 ^ t * (((8 / 3 : ℝ) * 2 ^ k)⁻¹ * ((8 / 3 : ℝ) * 2 ^ k)) by ring,
          inv_mul_cancel₀ (hp0 k), mul_one]
      have hw : ∀ j : ℕ, ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k) = (2 : ℝ) ^ ((j : ℤ) - (k : ℤ)) := fun j => by
        rw [zpow_sub₀ two_ne_zero, zpow_natCast, zpow_natCast]
        field_simp
      rw [Finset.prod_congr rfl (fun t _ => hq t), Finset.prod_mul_distrib, Finset.prod_const, hcard, inv_pow]
      simp only [hw]
      ring
    calc (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((m : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (m : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (m : ℕ)))⁻¹) = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * ((-∏ t ∈ Finset.Icc 1 (n - 1), ((2 : ℝ) ^ m - (2 : ℝ) ^ t)) * ∏ k ∈ Finset.Icc 1 n, (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := hLHS
      _ = (((2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (∑ k ∈ Finset.Icc 1 n, (-∏ t ∈ Finset.Icc 1 (n - 1), (((8 / 3 : ℝ) * 2 ^ k)⁻¹ - (2 : ℝ) ^ t)) * (∏ j ∈ (Finset.Icc 1 n).erase k, (1 - ((8 / 3 : ℝ) * 2 ^ j) / ((8 / 3 : ℝ) * 2 ^ k)))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by rw [hL]
      _ = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * ((((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m) ^ (n - 1))⁻¹ * (1 - ((8 / 3 : ℝ) * 2 ^ k) * (2 : ℝ) ^ m)⁻¹) := by
        rw [Finset.mul_sum]
        refine Finset.sum_congr rfl (fun k hk => ?_)
        rw [← hcoef k hk, mul_pow, mul_inv]
        ring
      _ = ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + m))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ m) ^ i)⁻¹) := hRHS.symm
  -- Borwein Lemma 1 (proved): sum over m >= 1; the first n - 1 terms vanish.
  have hres : ∀ n : ℕ, 1 ≤ n → (∑' j : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((n + j : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (n + j : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (n + j : ℕ)))⁻¹)) = (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k)))) * (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) - ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹)) - ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) / ((2 : ℝ) ^ i - 1)) := by
    intro n hn
    have pf := hpf n hn
    -- Summability of the two families of pieces.
    have hT : ∀ k : ℕ, Summable (fun m : ℕ => (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) := by
      intro k
      refine Summable.of_norm_bounded (summable_geometric_of_lt_one (by norm_num : (0 : ℝ) ≤ 1 / 2) (by norm_num)) (fun m => ?_)
      have h1 : (1 : ℝ) ≤ 2 ^ k := one_le_pow₀ (by norm_num)
      have h2 : (1 : ℝ) ≤ 2 ^ m := one_le_pow₀ (by norm_num)
      have he : (2 : ℝ) ^ (k + (m + 1)) = 2 * 2 ^ k * 2 ^ m := by ring
      have hneg : (1 : ℝ) - 8 / 3 * 2 ^ (k + (m + 1)) < 0 := by rw [he]; nlinarith
      rw [Real.norm_eq_abs, abs_inv, abs_of_neg hneg, one_div_pow, one_div]
      exact inv_anti₀ (by positivity) (by rw [he]; nlinarith)
    have hGeo : ∀ i : ℕ, 1 ≤ i → ∑' m : ℕ, (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹ = ((2 : ℝ) ^ i - 1)⁻¹ := by
      intro i hi
      have h2 : (2 : ℝ) ≤ 2 ^ i := by
        calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi
      have hr0 : (0 : ℝ) ≤ ((2 : ℝ) ^ i)⁻¹ := by positivity
      have hr1 : ((2 : ℝ) ^ i)⁻¹ < 1 := inv_lt_one_of_one_lt₀ (by linarith)
      have hc : ∀ m : ℕ, (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹ = ((2 : ℝ) ^ i)⁻¹ * (((2 : ℝ) ^ i)⁻¹) ^ m := by
        intro m
        rw [← pow_succ', inv_pow, ← pow_mul, ← pow_mul, mul_comm]
      rw [tsum_congr hc, tsum_mul_left, tsum_geometric_of_lt_one hr0 hr1]
      have h3 : (2 : ℝ) ^ i - 1 ≠ 0 := by linarith
      have h4 : (2 : ℝ) ^ i ≠ 0 := by positivity
      field_simp
    have hGs : ∀ i : ℕ, 1 ≤ i → Summable (fun m : ℕ => (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹) := by
      intro i hi
      by_contra hns
      have := tsum_eq_zero_of_not_summable hns
      rw [hGeo i hi] at this
      have h2 : (2 : ℝ) ≤ 2 ^ i := by
        calc (2 : ℝ) = 2 ^ 1 := (pow_one 2).symm
          _ ≤ 2 ^ i := pow_le_pow_right₀ (by norm_num) hi
      have : ((2 : ℝ) ^ i - 1)⁻¹ ≠ 0 := inv_ne_zero (by linarith)
      contradiction
    have hz0 : Summable (fun j : ℕ => (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) := by
      simpa using hT 0
    have hIcc : ∀ k : ℕ, ∑ i ∈ Finset.range k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (i + 1))⁻¹ = ∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ := by
      intro k
      induction k with
      | zero => simp
      | succ k ih => rw [Finset.sum_range_succ, ih, Finset.sum_Icc_succ_top (by omega)]
    have hTail : ∀ k : ℕ, ∑' m : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹ = (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) - ∑ i ∈ Finset.Icc 1 k, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ i)⁻¹ := by
      intro k
      have hs := hz0.sum_add_tsum_nat_add k
      rw [hIcc k] at hs
      rw [← hs, add_sub_cancel_left]
      exact tsum_congr (fun m => by rw [show k + (m + 1) = m + k + 1 by omega])
    -- The series E(n) summed from m = 1: its first n - 1 terms vanish.
    have hRs1 : Summable (fun m : ℕ => ∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) :=
      summable_sum (fun k _ => (hT k).mul_left _)
    have hRs2 : Summable (fun m : ℕ => ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹) :=
      summable_sum (fun i hi => (hGs i (Finset.mem_Icc.mp hi).1).mul_left _)
    have hRs : Summable (fun m : ℕ => ((∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (k + (m + 1)))⁻¹) + ∑ i ∈ Finset.Icc 1 (n - 1), (∑ k ∈ Finset.Icc 1 n, (-(∏ t ∈ Finset.Icc 1 (n - 1), (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (t + k))) / ∏ l ∈ (Finset.Icc 1 n).erase k, (1 - (2 : ℝ) ^ ((l : ℤ) - k))) * (((8 / 3 : ℝ) * (2 : ℝ) ^ k) ^ i)⁻¹) * (((2 : ℝ) ^ (m + 1)) ^ i)⁻¹)) := hRs1.add hRs2
    have hGsum : Summable (fun m : ℕ => (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((m + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((m + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((m + 1) : ℕ)))⁻¹)) :=
      hRs.congr (fun m => (pf (m + 1) (by omega)).symm)
    have hshift := hGsum.sum_add_tsum_nat_add (n - 1)
    have hzero : ∑ i ∈ Finset.range (n - 1), (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((i + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((i + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((i + 1) : ℕ)))⁻¹) = 0 := by
      refine Finset.sum_eq_zero (fun i hi => ?_)
      have hi' : i + 1 ∈ Finset.Icc 1 (n - 1) := by
        rw [Finset.mem_range] at hi
        rw [Finset.mem_Icc]; omega
      refine mul_eq_zero_of_right _ (Finset.prod_eq_zero hi' ?_)
      simp
    rw [hzero, zero_add] at hshift
    have hE : (∑' j : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (((n + j : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - (n + j : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + (n + j : ℕ)))⁻¹)) = ∑' m : ℕ, (-(1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((((m + 1) : ℕ) : ℤ) + n))⁻¹ * ∏ k ∈ Finset.Icc 1 (n - 1), (1 - (2 : ℝ) ^ ((k : ℤ) - ((m + 1) : ℕ))) * (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ ((k : ℤ) + ((m + 1) : ℕ)))⁻¹) := by
      rw [← hshift]
      exact tsum_congr (fun j => by rw [show j + (n - 1) + 1 = n + j by omega])
    rw [hE, tsum_congr (fun m => pf (m + 1) (by omega)), hRs1.tsum_add hRs2,
      Summable.tsum_finsetSum (fun k _ => (hT k).mul_left _),
      Summable.tsum_finsetSum (fun i hi => (hGs i (Finset.mem_Icc.mp hi).1).mul_left _),
      Finset.sum_congr (s₁ := Finset.Icc 1 n) rfl (fun k _ => by rw [tsum_mul_left, hTail k]),
      Finset.sum_congr (s₁ := Finset.Icc 1 (n - 1)) rfl (fun i hi => by rw [tsum_mul_left, hGeo i (Finset.mem_Icc.mp hi).1])]
    simp only [mul_sub, Finset.sum_sub_distrib, Finset.sum_mul, div_eq_mul_inv]
    ring
  refine ⟨a, b, fun n hn => ?_⟩
  linear_combination (∑' j : ℕ, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ (j + 1))⁻¹) * hb n hn - ha n hn - (9 : ℝ) ^ n * ((Nat.factorial (n - 2) : ℝ) * (∏ k ∈ Finset.Icc 1 n, (1 - (8 / 3 : ℝ) * (2 : ℝ) ^ k)) * (∏ k ∈ Finset.Icc ((n + 1) / 2) n, (1 - (2 : ℝ) ^ k))) * hres n hn
