import Mathlib
import Nodes.«erdos-1094--h1».Context

open scoped Nat

/-! Hole `h_fixed_k` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h1 : ∀ (k : ℕ), (0 : ℕ) < k → {n : ℕ | k * k ≤ n ∧ (n.choose k).minFac > n / k}.Finite := by
  sorry
