import Mathlib

open Filter

/-! Hole `h2` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h2 : (∀ (A : Finset ℕ) (m : ℕ),
    0 ∉ A →
      (∀ a ∈ A, ∀ b ∈ A, a ≤ m * a.gcd b) →
        ∀ a ∈ A, ∀ b ∈ A, ∃ u v, 0 < u ∧ u ≤ m ∧ 0 < v ∧ v ≤ m ∧ u.Coprime v ∧ a * v = b * u) →
  ∀ (A : Finset ℕ),
    0 ∉ A →
      A.Nonempty →
        (∀ (B : Finset ℕ), 0 ∉ B → B.card = A.card → B.gcd id = 1 → ∃ a ∈ B, ∃ b ∈ B, a.gcd b ≤ (a / B.card : ℚ)) →
          ∃ a ∈ A, ∃ b ∈ A, a.gcd b ≤ (a / A.card : ℚ) := by
  intro _ A hA hne hprim
  obtain ⟨x, hx⟩ := hne
  have hx0 : x ≠ 0 := ne_of_mem_of_not_mem hx hA
  have hgdvd : ∀ a ∈ A, A.gcd id ∣ a := fun a ha => Finset.gcd_dvd (f := id) ha
  have hg0 : A.gcd id ≠ 0 := by
    intro h0
    have h1 := hgdvd x hx
    rw [h0] at h1
    exact hx0 (Nat.eq_zero_of_zero_dvd h1)
  have hgpos : 0 < A.gcd id := Nat.pos_of_ne_zero hg0
  have hB0 : 0 ∉ A.image (fun a => a / A.gcd id) := by
    intro h
    obtain ⟨a, ha, hag⟩ := Finset.mem_image.mp h
    have ha0 : a ≠ 0 := ne_of_mem_of_not_mem ha hA
    obtain ⟨k, hk⟩ := hgdvd a ha
    have hk0 : k = 0 := by
      have h2 : a / A.gcd id = k := by
        conv_lhs => rw [hk]
        exact Nat.mul_div_cancel_left _ hgpos
      rw [← h2]; exact hag
    exact ha0 (by rw [hk, hk0, mul_zero])
  have hcard : (A.image (fun a => a / A.gcd id)).card = A.card := by
    apply Finset.card_image_of_injOn
    intro a ha b hb hab
    exact (Nat.div_left_inj (hgdvd a ha) (hgdvd b hb)).mp hab
  have hgcd : (A.image (fun a => a / A.gcd id)).gcd id = 1 := by
    rw [Finset.gcd_image]
    exact Finset.gcd_div_id_eq_one hx hx0
  obtain ⟨a', ha', b', hb', hab⟩ := hprim _ hB0 hcard hgcd
  obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp ha'
  obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hb'
  refine ⟨a, ha, b, hb, ?_⟩
  obtain ⟨k, hk⟩ := hgdvd a ha
  obtain ⟨l, hl⟩ := hgdvd b hb
  have e1 : a / A.gcd id = k := by
    conv_lhs => rw [hk]
    exact Nat.mul_div_cancel_left _ hgpos
  have e2 : b / A.gcd id = l := by
    conv_lhs => rw [hl]
    exact Nat.mul_div_cancel_left _ hgpos
  rw [hcard, e1, e2] at hab
  have e3 : a.gcd b = A.gcd id * k.gcd l := by
    conv_lhs => rw [hk, hl]
    exact Nat.gcd_mul_left _ _ _
  have e4 : (a : ℚ) = ((A.gcd id : ℕ) : ℚ) * k := by exact_mod_cast hk
  rw [e3, e4]
  push_cast
  rw [mul_div_assoc]
  exact mul_le_mul_of_nonneg_left hab (by positivity)
