import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1094--h2--h1`, `erdos-1094--h2--h2`. -/

open scoped Nat

/-! Hole `h_lo` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h2__h1 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → k * k ≤ n → n < k * k * k → (n.choose k).minFac > n / k → k ≤ K := by
  sorry


open scoped Nat

/-! Hole `h_hi` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h2__h2 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → k * k * k ≤ n → (n.choose k).minFac > n / k → k ≤ K := by
  sorry
