import Mathlib
import Nodes.«erdos-1094--h2».Context

open scoped Nat

/-! Hole `h_large_n` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h2 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → k * k ≤ n → (n.choose k).minFac > n / k → k ≤ K := by
  sorry
