import Mathlib
import Nodes.«erdos-1050--h1-v2--h3».Context

/-! Hole `hden` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h3 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            ∀ (n : ℕ),
              ∃ (d : ℕ),
                (0 : ℕ) < d ∧
                  (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                    (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n := by
  -- annex: 4670684d2f0db4568cdaf74d8147b2ae959ae6b3136c3eb5460dbfc117de376f
  -- Denominator d = 2^(n(n+1)/2) * M n * C n (annex 4670684d), explicit lcm's for n = 5, 7.
  intro Qc hQc Qx hQx Aq hAq n
  obtain ⟨M, hM⟩ : ∃ M : ℕ → ℕ, M = fun n => ∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) := ⟨_, rfl⟩
  obtain ⟨C, hC⟩ : ∃ C : ℕ → ℕ, C = fun n => ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) := ⟨_, rfl⟩
  -- ingredient 1: Qc n k = ± 2^(k(k-1)/2) [n k]_2 [2n-k n]_2; Gaussian binomial integrality at
  -- q = 2 is the statement of spec-440db0f9, applied to both products
  have hQcint : ∀ k ≤ n, ∃ z : ℤ, (z : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) = Qc n k := sorry
  -- ingredient 2, the crux: v2(p_k) ≥ k(k-1)/2, odd part of the denominator divides M n
  have hpint : ∀ k ≤ n, ∃ z : ℤ, (z : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) =
      (M n : ℚ) * ∑ j ∈ Finset.range (k + 1), Qc n j / ((2 : ℚ) ^ (k - j) - 1) := sorry
  -- ingredient 3: every 2^(j+1) - 3 (j ≥ 2) is a factor of C n; for j < 2 it is ±1
  have hcint : ∃ z : ℤ, (z : ℚ) = (C n : ℚ) * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + 1) - 3) := sorry
  -- ingredient 4: the size bound, false only at n = 5 and n = 7
  have hsize : n ≠ 5 → n ≠ 7 → (2 ^ (n * (n + 1) / 2) * M n * C n) ^ 2 ≤ 2 ^ (3 * n * n) := sorry
  -- n = 5 and n = 7: the least common denominators, a finite computation
  have hsmall : (n = 5 → ∃ z z' : ℤ, (z : ℚ) = 13403586560 * Qx n ∧ (z' : ℚ) = 13403586560 * Aq n) ∧
      (n = 7 → ∃ z z' : ℤ, (z : ℚ) = 348621924990976000 * Qx n ∧
        (z' : ℚ) = 348621924990976000 * Aq n) := sorry
  -- the assembly
  have hexp : ∀ k m : ℕ, (k + m) * (k + m + 1) / 2 + k * (k - 1) / 2 = (k + m) * k + m * (m + 1) / 2 := by
    intro k m
    have h1 := Nat.div_mul_cancel (Nat.even_mul_succ_self (k + m)).two_dvd
    have h3 := Nat.div_mul_cancel (Nat.even_mul_succ_self m).two_dvd
    rcases k with _ | k
    · simp
    · have h2 := Nat.div_mul_cancel (Nat.even_mul_succ_self k).two_dvd
      simp only [Nat.add_sub_cancel]
      have h2' : (k + 1) * k / 2 = k * (k + 1) / 2 := by rw [Nat.mul_comm]
      rw [h2']
      nlinarith
  have key : ∀ (c : ℚ) (a : ℕ → ℚ), (∀ k ≤ n, ∃ z : ℤ, (z : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) = c * a k) →
      ∃ z : ℤ, (z : ℚ) = c * (2 : ℚ) ^ (n * (n + 1) / 2) *
        ∑ k ∈ Finset.range (n + 1), a k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k := by
    intro c a ha
    rw [Finset.mul_sum]
    refine Finset.sum_induction _ (fun q : ℚ => ∃ z : ℤ, (z : ℚ) = q)
      (fun x y ⟨zx, hx⟩ ⟨zy, hy⟩ => ⟨zx + zy, by push_cast; rw [hx, hy]⟩) ⟨0, by simp⟩ ?_
    intro k hk
    have hkn : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
    obtain ⟨z, hz⟩ := ha k hkn
    obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hkn
    refine ⟨z * 3 ^ k * 2 ^ (m * (m + 1) / 2), ?_⟩
    have h2 : (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2) =
        (2 : ℚ) ^ ((k + m) * k) * (2 : ℚ) ^ (m * (m + 1) / 2) := by
      rw [← pow_add, ← pow_add, hexp]
    have hP : (2 : ℚ) ^ ((k + m) * k) ≠ 0 := by positivity
    push_cast
    calc (z : ℚ) * 3 ^ k * 2 ^ (m * (m + 1) / 2)
        = (z : ℚ) * 3 ^ k * ((2 : ℚ) ^ ((k + m) * k) * 2 ^ (m * (m + 1) / 2)) / (2 : ℚ) ^ ((k + m) * k) := by
          rw [eq_div_iff hP]; ring
      _ = (z : ℚ) * 3 ^ k * ((2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * 2 ^ (k * (k - 1) / 2)) /
          (2 : ℚ) ^ ((k + m) * k) := by rw [h2]
      _ = (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * 3 ^ k * ((z : ℚ) * 2 ^ (k * (k - 1) / 2)) /
          (2 : ℚ) ^ ((k + m) * k) := by ring
      _ = (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * 3 ^ k * (c * a k) / (2 : ℚ) ^ ((k + m) * k) := by rw [hz]
      _ = c * (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * (a k * ((3 : ℚ) / (2 : ℚ) ^ (k + m)) ^ k) := by
          rw [div_pow, ← pow_mul]; ring
  by_cases h5 : n = 5
  · obtain ⟨z, z', hz, hz'⟩ := hsmall.1 h5
    subst h5
    exact ⟨13403586560, by norm_num, by norm_num, ⟨z, by push_cast; exact hz⟩, ⟨z', by push_cast; exact hz'⟩⟩
  by_cases h7 : n = 7
  · obtain ⟨z, z', hz, hz'⟩ := hsmall.2 h7
    subst h7
    exact ⟨348621924990976000, by norm_num, by norm_num, ⟨z, by push_cast; exact hz⟩,
      ⟨z', by push_cast; exact hz'⟩⟩
  have hMpos : 0 < M n := by
    simp only [hM]
    refine Finset.prod_pos fun m hm => ?_
    have hm1 := (Finset.mem_Ioc.mp hm).1
    have := Nat.one_lt_two_pow (n := m) (by omega)
    omega
  have hCpos : 0 < C n := by
    simp only [hC]
    refine Finset.prod_pos fun j hj => ?_
    have hj2 := (Finset.mem_Ico.mp hj).1
    have : 8 ≤ 2 ^ (j + 1) := by
      calc 8 = 2 ^ 3 := by norm_num
        _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
    omega
  obtain ⟨zQ, hzQ⟩ := key 1 (Qc n) (fun k hk => by simpa using hQcint k hk)
  obtain ⟨zP, hzP⟩ := key (M n : ℚ) (fun k => ∑ j ∈ Finset.range (k + 1), Qc n j / ((2 : ℚ) ^ (k - j) - 1)) hpint
  obtain ⟨zc, hzc⟩ := hcint
  have hQx' : (zQ : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) * Qx n := by rw [hzQ, hQx, one_mul]
  refine ⟨2 ^ (n * (n + 1) / 2) * M n * C n, Nat.mul_pos (Nat.mul_pos (by positivity) hMpos) hCpos,
    by exact_mod_cast hsize h5 h7, ⟨zQ * M n * C n, ?_⟩, ⟨C n * zP + zQ * M n * zc, ?_⟩⟩
  · push_cast
    rw [hQx']
    ring
  · push_cast
    rw [hQx', hzP, hzc, hAq]
    ring
