import Mathlib
import Nodes.«erdos-1050--h1-v2--h3».Context

/-! Hole `hden` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h3 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            ∀ (n : ℕ),
              ∃ (d : ℕ),
                (0 : ℕ) < d ∧
                  (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                    (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n := by
  -- annex: 4670684d2f0db4568cdaf74d8147b2ae959ae6b3136c3eb5460dbfc117de376f
  have hcore : ∀ (Qc : ℕ → ℕ → ℚ),
    (Qc = fun (n k : ℕ) =>
        ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
            ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
          ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (n k : ℕ), k ≤ n →
      ∃ z : ℤ, (z : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) =
        (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
          ∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ)) := sorry
  have gauss : ∀ n k : ℕ,
      ∃ z : ℤ, (z : ℚ) = ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
    intro n k
    have hD : ∀ j : ℕ, ((2 : ℚ) ^ (j + 1) - 1) ≠ 0 := by
      intro j
      have h1 : (1 : ℚ) < 2 ^ (j + 1) := one_lt_pow₀ (by norm_num) (by omega)
      exact ne_of_gt (sub_pos.mpr h1)
    have hDk : ∀ k : ℕ, (∏ i ∈ Finset.range k, ((2 : ℚ) ^ (i + 1) - 1)) ≠ 0 := by
      intro k
      exact Finset.prod_ne_zero_iff.mpr (fun i _ => hD i)
    have key : ∀ m j : ℕ,
        (∏ i ∈ Finset.range (j + 1), ((2 : ℚ) ^ (m + 1 - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1)) =
          (∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1)) +
          2 ^ (j + 1) *
            ∏ i ∈ Finset.range (j + 1), ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
      intro m j
      simp only [Finset.prod_div_distrib]
      rw [Finset.prod_range_succ' (fun i => (2 : ℚ) ^ (m + 1 - i) - 1)]
      have hshift : ∀ i : ℕ, m + 1 - (i + 1) = m - i := fun i => by omega
      simp only [hshift, Nat.sub_zero]
      rw [Finset.prod_range_succ (fun i => (2 : ℚ) ^ (m - i) - 1),
        Finset.prod_range_succ (fun i => (2 : ℚ) ^ (i + 1) - 1)]
      have hDj := hDk j
      have hj := hD j
      by_cases hjm : j ≤ m
      · have e : (2 : ℚ) ^ (m + 1) = 2 ^ (m - j) * 2 ^ (j + 1) := by
          rw [← pow_add]
          congr 1
          omega
        rw [e]
        field_simp
        ring
      · have hz : (∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1)) = 0 :=
          Finset.prod_eq_zero (i := m) (Finset.mem_range.mpr (by omega)) (by simp)
        rw [hz]
        simp
    have main : ∀ m j : ℕ, ∃ z : ℤ,
        (z : ℚ) = ∏ i ∈ Finset.range j, ((2 : ℚ) ^ (m - i) - 1) / ((2 : ℚ) ^ (i + 1) - 1) := by
      intro m
      induction m with
      | zero =>
        intro j
        cases j with
        | zero => exact ⟨1, by simp⟩
        | succ j =>
          refine ⟨0, ?_⟩
          rw [Finset.prod_eq_zero (i := 0) (by simp) (by simp)]
          simp
      | succ m ih =>
        intro j
        cases j with
        | zero => exact ⟨1, by simp⟩
        | succ j =>
          obtain ⟨a, ha⟩ := ih j
          obtain ⟨b, hb⟩ := ih (j + 1)
          refine ⟨a + 2 ^ (j + 1) * b, ?_⟩
          rw [key, ← ha, ← hb]
          push_cast
          ring
    exact main n k
  have hcnall : ∀ n : ℕ, ∃ z : ℤ, (z : ℚ) = (∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
      ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + 1) - 3) := by
    intro n
    have hint : ∀ j ∈ Finset.range n, ∃ z : ℤ,
        (z : ℚ) = (∏ i ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (i + 1) - 3)) * ((3 : ℚ) / ((2 : ℚ) ^ (j + 1) - 3)) := by
      intro j hj
      by_cases h2 : j < 2
      · have hj' : j = 0 ∨ j = 1 := by omega
        rcases hj' with rfl | rfl
        · refine ⟨-3 * ∏ i ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
          have e : (3 : ℚ) / ((2 : ℚ) ^ (0 + 1) - 3) = -3 := by norm_num
          rw [e]
          push_cast
          ring
        · refine ⟨3 * ∏ i ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
          have e : (3 : ℚ) / ((2 : ℚ) ^ (1 + 1) - 3) = 3 := by norm_num
          rw [e]
          push_cast
          ring
      · have hmem : j ∈ Finset.Ico 2 n := Finset.mem_Ico.mpr ⟨by omega, Finset.mem_range.mp hj⟩
        have hne : ((2 : ℚ) ^ (j + 1) - 3) ≠ 0 := by
          have h8 : (8 : ℚ) ≤ 2 ^ (j + 1) := by
            calc (8 : ℚ) = 2 ^ 3 := by norm_num
              _ ≤ 2 ^ (j + 1) := pow_le_pow_right₀ (by norm_num) (by omega)
          linarith
        refine ⟨3 * ∏ i ∈ (Finset.Ico 2 n).erase j, ((2 : ℤ) ^ (i + 1) - 3), ?_⟩
        rw [← Finset.mul_prod_erase _ _ hmem]
        push_cast
        field_simp
    choose! g hg using hint
    refine ⟨∑ j ∈ Finset.range n, g j, ?_⟩
    push_cast
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl hg
  intro Qc hQc Qx hQx Aq hAq n
  have hb :
    ((2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℕ) : ℝ) ^ 2 ≤
      (2 : ℝ) ^ (3 * n * n) := by
    have key : (2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
            (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ)) ^ 2 ≤
        2 ^ (3 * n * n) := by
      rcases (show n ≤ 9 ∨ 10 ≤ n by omega) with hn | hn
      · interval_cases n <;> decide
      · rw [if_neg (by omega), if_neg (by omega)]
        have hP1 : ∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) ≤ 2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) := by
          rw [← Finset.prod_pow_eq_pow_sum]
          exact Finset.prod_le_prod' (fun m _ => Nat.sub_le _ _)
        have hP2 : ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) ≤ 2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1)) := by
          rw [← Finset.prod_pow_eq_pow_sum]
          exact Finset.prod_le_prod' (fun m _ => Nat.sub_le _ _)
        obtain ⟨c, hc⟩ : ∃ c, n = n / 2 + c + 1 := ⟨n - n / 2 - 1, by omega⟩
        obtain ⟨d, hd⟩ : ∃ d, n = d + 3 := ⟨n - 3, by omega⟩
        have hS1 : (∑ m ∈ Finset.Ioc (n / 2) n, m) * 2 = 2 * (c + 1) * (n / 2 + 1) + (c + 1) * c := by
          have e : Finset.Ioc (n / 2) n = Finset.Ico (n / 2 + 1) (n + 1) := by
            ext x; simp only [Finset.mem_Ioc, Finset.mem_Ico]; omega
          rw [e, Finset.sum_Ico_eq_sum_range, show n + 1 - (n / 2 + 1) = c + 1 by omega,
            Finset.sum_add_distrib, Finset.sum_const, Finset.card_range, smul_eq_mul, add_mul,
            Finset.sum_range_id_mul_two]
          simp only [Nat.add_sub_cancel]
          ring
        have hS2 : (∑ j ∈ Finset.Ico 2 n, (j + 1)) * 2 = 6 * (d + 1) + (d + 1) * d := by
          rw [Finset.sum_Ico_eq_sum_range, show n - 2 = d + 1 by omega]
          have : ∀ k ∈ Finset.range (d + 1), 2 + k + 1 = 3 + k := fun k _ => by omega
          rw [Finset.sum_congr rfl this, Finset.sum_add_distrib, Finset.sum_const, Finset.card_range,
            smul_eq_mul, add_mul, Finset.sum_range_id_mul_two]
          simp only [Nat.add_sub_cancel]
          ring
        have hT : n * (n + 1) / 2 * 2 = n * (n + 1) :=
          Nat.div_mul_cancel (Nat.even_mul_succ_self n).two_dvd
        have hexp : 2 * (n * (n + 1) / 2) + 2 * (∑ m ∈ Finset.Ioc (n / 2) n, m) +
            2 * (∑ j ∈ Finset.Ico 2 n, (j + 1)) ≤ 3 * n * n := by
          have hh5 : 5 ≤ n / 2 := by omega
          have hsq : 5 * (n / 2) ≤ (n / 2) * (n / 2) := Nat.mul_le_mul_right _ hh5
          rcases (show n = 2 * (n / 2) ∨ n = 2 * (n / 2) + 1 by omega) with hr | hr
          · have hc' : c = n / 2 - 1 := by omega
            have hd' : d = 2 * (n / 2) - 3 := by omega
            nlinarith
          · have hc' : c = n / 2 := by omega
            have hd' : d = 2 * (n / 2) - 2 := by omega
            nlinarith
        calc (2 ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
                ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3))) ^ 2
            ≤ (2 ^ (n * (n + 1) / 2) * (2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) *
                2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1)))) ^ 2 := by gcongr
          _ = 2 ^ (2 * (n * (n + 1) / 2) + 2 * (∑ m ∈ Finset.Ioc (n / 2) n, m) +
                2 * (∑ j ∈ Finset.Ico 2 n, (j + 1))) := by
            rw [← pow_add, ← pow_add, ← pow_mul]; congr 1; ring
          _ ≤ 2 ^ (3 * n * n) := Nat.pow_le_pow_right (by norm_num) hexp
    exact_mod_cast key
  have hqx : ∃ z : ℤ, (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) *
      ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k := by
    have hterm : ∀ k ∈ Finset.range (n + 1), ∃ z : ℤ,
        (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) * (Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) := by
      intro k hk
      have hkn : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
      obtain ⟨a, ha⟩ := gauss n k
      obtain ⟨b, hb⟩ := gauss (2 * n - k) n
      obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le hkn
      have hexp : (k + m) * (k + m + 1) / 2 + k * (k - 1) / 2 = m * (m + 1) / 2 + (k + m) * k := by
        have e1 : 2 * ((k + m) * (k + m + 1) / 2) = (k + m) * (k + m + 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
        have e2 : 2 * (k * (k - 1) / 2) = k * (k - 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_pred_self _)
        have e3 : 2 * (m * (m + 1) / 2) = m * (m + 1) :=
          Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
        rcases k with _ | j
        · simp
        · simp only [Nat.add_sub_cancel] at e2 ⊢
          nlinarith [e1, e2, e3]
      refine ⟨(-1) ^ k * 3 ^ k * 2 ^ (m * (m + 1) / 2) * a * b, ?_⟩
      have hpow : (2 : ℚ) ^ ((k + m) * (k + m + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2) =
          (2 : ℚ) ^ (m * (m + 1) / 2) * ((2 : ℚ) ^ (k + m)) ^ k := by
        rw [← pow_add, ← pow_mul, ← pow_add, hexp]
      have h2 : ((2 : ℚ) ^ (k + m)) ≠ 0 := by positivity
      rw [hQc]
      simp only []
      rw [← ha, ← hb]
      push_cast
      rw [div_pow, mul_div_assoc']
      field_simp
      linear_combination -(a : ℚ) * b * hpow
    choose! g hg using hterm
    refine ⟨∑ k ∈ Finset.range (n + 1), g k, ?_⟩
    push_cast
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl (fun k hk => hg k hk)
  have hE : 0 < (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) := by
    split_ifs
    · norm_num
    · norm_num
    · refine Nat.mul_pos (Finset.prod_pos fun m hm => ?_) (Finset.prod_pos fun j hj => ?_)
      · have hm1 : 1 ≤ m := by
          have := (Finset.mem_Ioc.mp hm).1
          omega
        have : 2 ≤ 2 ^ m := by
          calc 2 = 2 ^ 1 := by norm_num
            _ ≤ 2 ^ m := Nat.pow_le_pow_right (by norm_num) hm1
        omega
      · have hj2 : 2 ≤ j := (Finset.mem_Ico.mp hj).1
        have : 8 ≤ 2 ^ (j + 1) := by
          calc 8 = 2 ^ 3 := by norm_num
            _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
        omega
  have hAqint : ∃ z : ℤ, (z : ℚ) = ((2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
        (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℕ) : ℚ) * Aq n := by
    by_cases h5 : n = 5
    · subst h5
      refine ⟨1380067124193819576, ?_⟩
      rw [if_pos rfl]
      subst hQc hQx hAq
      simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero,
        Finset.prod_range_zero]
      norm_num
    · by_cases h7 : n = 7
      · subst h7
        refine ⟨674036225808261890798679141926088, ?_⟩
        rw [if_neg (by norm_num), if_pos rfl]
        subst hQc hQx hAq
        simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero,
        Finset.prod_range_zero]
        norm_num
      · rw [if_neg h5, if_neg h7]
        have hM : ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) : ℕ) : ℚ) =
            ∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1) := by
          rw [Nat.cast_prod]
          refine Finset.prod_congr rfl (fun m _ => ?_)
          rw [Nat.cast_sub Nat.one_le_two_pow]
          push_cast
          ring
        have hC : ((∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℚ) =
            ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3) := by
          rw [Nat.cast_prod]
          refine Finset.prod_congr rfl (fun j hj => ?_)
          have hj2 : 2 ≤ j := (Finset.mem_Ico.mp hj).1
          have h3 : 3 ≤ 2 ^ (j + 1) := by
            calc 3 ≤ 2 ^ 2 := by norm_num
              _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
          rw [Nat.cast_sub h3]
          push_cast
          ring
        have hd : ((2 ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
            ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3)) : ℕ) : ℚ) =
            (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) := by
          rw [Nat.cast_mul, Nat.cast_mul, hM, hC]
          push_cast
          ring
        obtain ⟨zcn, hzcn⟩ := hcnall n
        obtain ⟨zq', hzq'⟩ := hqx
        have hQxn : Qx n = ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k := by
          rw [hQx]
        have hterm : ∀ k ∈ Finset.range (n + 1), ∃ z : ℤ,
            (z : ℚ) = (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
              ((∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) := by
          intro k hk
          have hkn : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hk)
          obtain ⟨w, hw⟩ := hcore Qc hQc n k hkn
          obtain ⟨m, hm⟩ := Nat.exists_eq_add_of_le hkn
          have hexp : n * (n + 1) / 2 + k * (k - 1) / 2 = m * (m + 1) / 2 + n * k := by
            rw [hm]
            have e1 : 2 * ((k + m) * (k + m + 1) / 2) = (k + m) * (k + m + 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
            have e2 : 2 * (k * (k - 1) / 2) = k * (k - 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_pred_self _)
            have e3 : 2 * (m * (m + 1) / 2) = m * (m + 1) :=
              Nat.two_mul_div_two_of_even (Nat.even_mul_succ_self _)
            rcases k with _ | j
            · simp
            · simp only [Nat.add_sub_cancel] at e2 ⊢
              nlinarith [e1, e2, e3]
          have hpow : (2 : ℚ) ^ (n * (n + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2) =
              (2 : ℚ) ^ (m * (m + 1) / 2) * ((2 : ℚ) ^ n) ^ k := by
            rw [← pow_add, ← pow_mul, ← pow_add, hexp]
          have h2n : ((2 : ℚ) ^ n) ^ k ≠ 0 := by positivity
          refine ⟨(∏ j ∈ Finset.Ico 2 n, ((2 : ℤ) ^ (j + 1) - 3)) * w * 3 ^ k * 2 ^ (m * (m + 1) / 2), ?_⟩
          have e1 : (2 : ℚ) ^ (n * (n + 1) / 2) * ((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
              ∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) *
              ((∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) =
              (∏ j ∈ Finset.Ico 2 n, ((2 : ℚ) ^ (j + 1) - 3)) * 3 ^ k *
                (((∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℚ) ^ m - 1)) *
                  ∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                  (2 : ℚ) ^ (n * (n + 1) / 2)) / ((2 : ℚ) ^ n) ^ k := by
            rw [div_pow]
            ring
          rw [e1, ← hw, show (w : ℚ) * (2 : ℚ) ^ (k * (k - 1) / 2) * (2 : ℚ) ^ (n * (n + 1) / 2) =
            (w : ℚ) * ((2 : ℚ) ^ (n * (n + 1) / 2) * (2 : ℚ) ^ (k * (k - 1) / 2)) by ring, hpow]
          push_cast
          field_simp
        choose! g hg using hterm
        refine ⟨∑ k ∈ Finset.range (n + 1), g k +
          (∏ m ∈ Finset.Ioc (n / 2) n, ((2 : ℤ) ^ m - 1)) * zq' * zcn, ?_⟩
        rw [hd, hAq]
        beta_reduce
        push_cast
        rw [mul_add, Finset.mul_sum, Finset.sum_congr rfl hg, hzcn, hzq', ← hQxn]
        ring
  obtain ⟨zq, hzq⟩ := hqx
  refine ⟨2 ^ (n * (n + 1) / 2) * (if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ), by positivity, hb, ⟨(if n = 5 then 409045 else if n = 7 then 1298717875 else
          (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) * ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) * zq, ?_⟩, hAqint⟩
  rw [hQx]
  push_cast
  rw [hzq]
  ring
