import Mathlib
import Nodes.«erdos-1050--h1-v2--h3».Context

/-! Hole `hden` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h3 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            ∀ (n : ℕ),
              ∃ (d : ℕ),
                (0 : ℕ) < d ∧
                  (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                    (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n := by
  -- annex: 4670684d2f0db4568cdaf74d8147b2ae959ae6b3136c3eb5460dbfc117de376f
  intro Qc hQc Qx hQx Aq hAq
  -- The one hole: the annex's candidate D_n clears Qx n and Aq n (numerically for n ≤ 45).
  have clears : ∀ n : ℕ, n ≠ 5 → n ≠ 7 →
      (∃ z : ℤ, (z : ℚ) = ((2 ^ (n * (n + 1) / 2) * (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
          ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℚ) * Qx n) ∧
      ∃ z : ℤ, (z : ℚ) = ((2 ^ (n * (n + 1) / 2) * (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
          ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) : ℕ) : ℚ) * Aq n := by
    sorry
  -- Proved: D_n is positive.
  have hpos : ∀ n : ℕ, 0 < 2 ^ (n * (n + 1) / 2) * (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
      ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) := by
    intro n
    refine Nat.mul_pos (Nat.mul_pos (by positivity) ?_) ?_
    · refine Finset.prod_pos (fun m hm => ?_)
      have hm1 : 1 ≤ m := by simp only [Finset.mem_Ioc] at hm; omega
      have h2 : 2 ≤ 2 ^ m := by
        calc 2 = 2 ^ 1 := by norm_num
          _ ≤ 2 ^ m := Nat.pow_le_pow_right (by norm_num) hm1
      omega
    · refine Finset.prod_pos (fun j hj => ?_)
      have hj1 : 2 ≤ j := (Finset.mem_Ico.mp hj).1
      have h8 : 8 ≤ 2 ^ (j + 1) := by
        calc 8 = 2 ^ 3 := by norm_num
          _ ≤ 2 ^ (j + 1) := Nat.pow_le_pow_right (by norm_num) (by omega)
      omega
  -- Proved: the size bound D_n ^ 2 ≤ 2 ^ (3 n ^ 2) for n ∉ {5, 7} (by evaluation for n ≤ 9,
  -- and for n ≥ 10 from 2^m - 1 ≤ 2^m, 2^(j+1) - 3 ≤ 2^(j+1) and the sums of the exponents).
  have size : ∀ n : ℕ, n ≠ 5 → n ≠ 7 →
      (2 ^ (n * (n + 1) / 2) * (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
        ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3)) ^ 2 ≤ 2 ^ (3 * n * n) := by
    intro n h5 h7
    rcases Nat.lt_or_ge n 10 with hn | hn
    · interval_cases n <;> first | omega | decide
    · have hA : (∑ m ∈ Finset.Ioc (n / 2) n, m) * 2 + (n / 2) * (n / 2 + 1) = n * (n + 1) := by
        have h1 : Finset.Ioc (n / 2) n = Finset.Ico (n / 2 + 1) (n + 1) := by
          ext x; simp only [Finset.mem_Ioc, Finset.mem_Ico]; omega
        rw [h1]
        have h2 := Finset.sum_range_add_sum_Ico (fun m => m) (show n / 2 + 1 ≤ n + 1 by omega)
        have h3 := Finset.sum_range_id_mul_two (n + 1)
        have h4 := Finset.sum_range_id_mul_two (n / 2 + 1)
        simp only [Nat.add_sub_cancel] at h3 h4
        nlinarith [h2, h3, h4]
      have hB : (∑ j ∈ Finset.Ico 2 n, (j + 1)) * 2 + 6 = n * (n + 1) := by
        have h2 := Finset.sum_range_add_sum_Ico (fun j => j + 1) (show 2 ≤ n by omega)
        have h3 := Finset.sum_range_id_mul_two n
        have h5 : ∑ j ∈ Finset.range n, (j + 1) = ∑ j ∈ Finset.range n, j + n := by
          rw [Finset.sum_add_distrib]; simp
        have h6 : ∑ j ∈ Finset.range 2, (j + 1) = 3 := by decide
        rw [h6, h5] at h2
        have h7 : n * (n - 1) + 2 * n = n * (n + 1) := by
          cases n with
          | zero => omega
          | succ k => simp only [Nat.add_sub_cancel]; ring
        nlinarith [h2, h3, h7]
      have hE : n * (n + 1) / 2 * 2 = n * (n + 1) :=
        Nat.div_mul_cancel (Nat.even_mul_succ_self n).two_dvd
      have hP1 : ∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1) ≤ 2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) := by
        rw [← Finset.prod_pow_eq_pow_sum]
        exact Finset.prod_le_prod' (fun m _ => Nat.sub_le _ _)
      have hP2 : ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3) ≤ 2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1)) := by
        rw [← Finset.prod_pow_eq_pow_sum]
        exact Finset.prod_le_prod' (fun j _ => Nat.sub_le _ _)
      have hexp : 2 * (n * (n + 1) / 2 + ∑ m ∈ Finset.Ioc (n / 2) n, m + ∑ j ∈ Finset.Ico 2 n, (j + 1))
          ≤ 3 * n * n := by
        have hh1 : 2 * (n / 2) ≤ n := Nat.mul_div_le n 2
        have hh2 : n ≤ 2 * (n / 2) + 1 := by omega
        have hh3 : 5 ≤ n / 2 := by omega
        nlinarith [hA, hB, hE, hh1, hh2, hh3]
      calc (2 ^ (n * (n + 1) / 2) * (∏ m ∈ Finset.Ioc (n / 2) n, (2 ^ m - 1)) *
            ∏ j ∈ Finset.Ico 2 n, (2 ^ (j + 1) - 3)) ^ 2
          ≤ (2 ^ (n * (n + 1) / 2) * 2 ^ (∑ m ∈ Finset.Ioc (n / 2) n, m) *
              2 ^ (∑ j ∈ Finset.Ico 2 n, (j + 1))) ^ 2 :=
            Nat.pow_le_pow_left (Nat.mul_le_mul (Nat.mul_le_mul le_rfl hP1) hP2) 2
        _ = 2 ^ (2 * (n * (n + 1) / 2 + ∑ m ∈ Finset.Ioc (n / 2) n, m + ∑ j ∈ Finset.Ico 2 n, (j + 1))) := by
            rw [← pow_add, ← pow_add, ← pow_mul]; ring_nf
        _ ≤ 2 ^ (3 * n * n) := Nat.pow_le_pow_right (by norm_num) hexp
  intro n
  by_cases h5 : n = 5
  · subst h5 hQc hQx hAq
    refine ⟨13403586560, by norm_num, by norm_num, ⟨1338545055613790115, ?_⟩, ⟨1380067124193819576, ?_⟩⟩
    · simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero, Finset.prod_range_zero]
      norm_num
    · simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero, Finset.prod_range_zero]
      norm_num
  by_cases h7 : n = 7
  · subst h7 hQc hQx hAq
    refine ⟨348621924990976000, by norm_num, by norm_num, ⟨653756503247821948956012109840125, ?_⟩,
      ⟨674036225808261890798679141926088, ?_⟩⟩
    · simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero, Finset.prod_range_zero]
      norm_num
    · simp only [Finset.sum_range_succ, Finset.prod_range_succ, Finset.sum_range_zero, Finset.prod_range_zero]
      norm_num
  refine ⟨_, hpos n, ?_, clears n h5 h7⟩
  exact_mod_cast size n h5 h7
