import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h1».Context

open scoped ArithmeticFunction.omega

/-! Hole `hsplit` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h1 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  ∀ (N k : ℕ),
    ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
      ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
        (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k := by
  intro _ N k
  have hω : ∀ m : ℕ, ω m ≤ m := by
    intro m
    rw [ArithmeticFunction.cardDistinctFactors_apply]
    calc m.primeFactorsList.dedup.length ≤ m.primeFactorsList.length :=
          (List.dedup_sublist _).length_le
      _ ≤ m := by
        rcases Nat.eq_zero_or_pos m with rfl | hm
        · simp
        · have hprod := Nat.prod_primeFactorsList (Nat.pos_iff_ne_zero.mp hm)
          have h2 : ∀ p ∈ m.primeFactorsList, 2 ≤ p := fun p hp =>
            (Nat.prime_of_mem_primeFactorsList hp).two_le
          have hpow : 2 ^ m.primeFactorsList.length ≤ m.primeFactorsList.prod := by
            simpa using List.pow_card_le_prod _ _ h2
          exact le_trans (Nat.lt_two_pow_self).le (by omega)
  have hs : Summable (fun j : ℕ => (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) := by
    have hg : Summable (fun j : ℕ => (N + 1 : ℝ) * (1 / 2 : ℝ) ^ j + (j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j) :=
      (summable_geometric_two.mul_left _).add
        (summable_pow_mul_geometric_of_norm_lt_one 1 (by norm_num))
    refine Summable.of_nonneg_of_le (fun j => by positivity) (fun j => ?_) hg
    have h1 : (ω (N + 1 + j) : ℝ) ≤ N + 1 + j := by exact_mod_cast hω _
    have hh : (1 / 2 : ℝ) ^ j * 2 ^ j = 1 := by rw [← mul_pow]; norm_num
    have e : ((N + 1 : ℝ) * (1 / 2 : ℝ) ^ j + (j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j) * 2 ^ (j + 1)
        = 2 * (N + 1 + j) := by
      rw [pow_succ]; linear_combination (2 * (N + 1 + j) : ℝ) * hh
    rw [div_le_iff₀ (by positivity), e]
    have : (0 : ℝ) ≤ N + 1 + j := by positivity
    linarith
  rw [← hs.sum_add_tsum_nat_add k, ← tsum_div_const]
  congr 1
  congr 1
  ext j
  rw [show N + 1 + (j + k) = N + k + 1 + j by ring, show j + k + 1 = (j + 1) + k by ring,
    pow_add, div_div]

