import Mathlib

open Filter

/-! Hole `h3` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3 : (∀ (A : Finset ℕ) (m : ℕ),
    0 ∉ A →
      (∀ a ∈ A, ∀ b ∈ A, a ≤ m * a.gcd b) →
        ∀ a ∈ A, ∀ b ∈ A, ∃ u v, 0 < u ∧ u ≤ m ∧ 0 < v ∧ v ≤ m ∧ u.Coprime v ∧ a * v = b * u) →
  (∀ (A : Finset ℕ),
      0 ∉ A →
        A.Nonempty →
          (∀ (B : Finset ℕ), 0 ∉ B → B.card = A.card → B.gcd id = 1 → ∃ a ∈ B, ∃ b ∈ B, a.gcd b ≤ (a / B.card : ℚ)) →
            ∃ a ∈ A, ∃ b ∈ A, a.gcd b ≤ (a / A.card : ℚ)) →
    ∀ (A : Finset ℕ),
      0 ∉ A →
        A.Nonempty →
          A.gcd id = 1 →
            (∀ a ∈ A, ∀ b ∈ A, ∃ u v, 0 < u ∧ u ≤ A.card ∧ 0 < v ∧ v ≤ A.card ∧ u.Coprime v ∧ a * v = b * u) →
              ∃ a ∈ A, ∃ b ∈ A, a.gcd b ≤ (a / A.card : ℚ) := by
  -- Informal argument: annex f5450271cb4865766831f2e6b153cb532934219590cff79ed42bb2ff813b15ac on
  -- this node (graph PR #265, still in the merge queue when this was submitted, so not cited in
  -- the `annex:` form, which a precheck refuses as annex-pending until the annex has merged).
  -- Hole (the remaining sizes): Graham's bound for a primitive set whose size n is neither a
  -- prime nor one more than a prime, whose quotients a / gcd(a, b) are at most n, and in which
  -- every prime power dividing an element is below n. This is where Balasubramanian and
  -- Soundararajan (1996) is still needed.
  have hcomp : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ q : ℕ, q.Prime → B.card ≠ q + 1) →
      (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      ∃ a ∈ B, ∃ b ∈ B, a.gcd b ≤ (a / B.card : ℚ) := sorry
  intro _hh1 _hh2 A hA hne hg _hfarey
  by_contra hcon
  push Not at hcon
  have hn : 0 < A.card := hne.card_pos
  have hnq : (0 : ℚ) < A.card := by exact_mod_cast hn
  -- If the bound fails, every quotient a / gcd(a, b) is below n = |A|.
  have hlt : ∀ a ∈ A, ∀ b ∈ A, a < A.card * a.gcd b := by
    intro a ha b hb
    have h' : (a : ℚ) < (a.gcd b : ℚ) * A.card := (div_lt_iff₀ hnq).mp (hcon a ha b hb)
    have h'' : (a : ℚ) < ((A.card * a.gcd b : ℕ) : ℚ) := by push_cast; linarith
    exact_mod_cast h''
  -- Prime powers: since gcd A = 1 some b is prime to p, and p ^ k divides a / gcd(a, b) < n.
  have hpp : ∀ a ∈ A, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < A.card := by
    intro a ha p k hp hdvd
    obtain ⟨b, hb, hpb⟩ : ∃ b ∈ A, ¬ p ∣ b := by
      by_contra h
      push Not at h
      have h1 : p ∣ A.gcd id := Finset.dvd_gcd (fun b hb => h b hb)
      rw [hg] at h1
      exact hp.one_lt.ne' (Nat.dvd_one.mp h1)
    have ha0 : a ≠ 0 := fun h => hA (h ▸ ha)
    have hg0 : 0 < a.gcd b := Nat.gcd_pos_of_pos_left b (Nat.pos_of_ne_zero ha0)
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    have hcop : Nat.Coprime (p ^ k) (a.gcd b) := by
      apply Nat.Coprime.pow_left
      rw [Nat.Prime.coprime_iff_not_dvd hp]
      intro h
      exact hpb (h.trans (Nat.gcd_dvd_right a b))
    have hdx : p ^ k ∣ x := by
      have h1 : p ^ k ∣ a.gcd b * x := hx ▸ hdvd
      exact hcop.dvd_of_dvd_mul_left h1
    have hx0 : x ≠ 0 := by
      rintro rfl
      rw [mul_zero] at hx
      exact ha0 hx
    have hxlt : x < A.card := by
      have h2 : a.gcd b * x < a.gcd b * A.card := by
        rw [← hx, mul_comm]
        exact hlt a ha b hb
      exact Nat.lt_of_mul_lt_mul_left h2
    exact lt_of_le_of_lt (Nat.le_of_dvd (Nat.pos_of_ne_zero hx0) hdx) hxlt
  by_cases hpr : A.card.Prime
  · -- Prime size n = p: no element is divisible by p (p ^ 1 < p fails), so a ↦ a % p maps the p
    -- elements into the p - 1 non-zero residues. Two elements a ≠ b collide; with g = gcd(a, b),
    -- a = g x and b = g y where x, y < p and p ∤ g, so x ≡ y (mod p) forces x = y and a = b.
    have hnd : ∀ a ∈ A, ¬ A.card ∣ a := by
      intro a ha h
      have h1 := hpp a ha A.card 1 hpr (by rw [pow_one]; exact h)
      rw [pow_one] at h1
      exact lt_irrefl _ h1
    have hmaps : Set.MapsTo (fun a => a % A.card) (A : Set ℕ) (Finset.Icc 1 (A.card - 1) : Set ℕ) := by
      intro a ha
      have ha' : a ∈ A := ha
      have h1 : a % A.card < A.card := Nat.mod_lt a hn
      have h2 : a % A.card ≠ 0 := fun h => hnd a ha' (Nat.dvd_of_mod_eq_zero h)
      simp only [Finset.coe_Icc, Set.mem_Icc]
      omega
    have hcard : (Finset.Icc 1 (A.card - 1)).card < A.card := by
      rw [Nat.card_Icc]
      omega
    obtain ⟨a, ha, b, hb, hab, heq⟩ := Finset.exists_ne_map_eq_of_card_lt_of_maps_to hcard hmaps
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    obtain ⟨y, hy⟩ := Nat.gcd_dvd_right a b
    have hxlt : x < A.card := by
      have h2 : a.gcd b * x < a.gcd b * A.card := by
        rw [← hx, mul_comm]
        exact hlt a ha b hb
      exact Nat.lt_of_mul_lt_mul_left h2
    have hylt : y < A.card := by
      have h2 : a.gcd b * y < a.gcd b * A.card := by
        rw [← hy, mul_comm, Nat.gcd_comm]
        exact hlt b hb a ha
      exact Nat.lt_of_mul_lt_mul_left h2
    have hcopg : A.card.gcd (a.gcd b) = 1 := by
      have h1 : Nat.Coprime A.card (a.gcd b) := by
        rw [Nat.Prime.coprime_iff_not_dvd hpr]
        intro h
        exact hnd a ha (h.trans (Nat.gcd_dvd_left a b))
      exact h1
    have hmod : a.gcd b * x ≡ a.gcd b * y [MOD A.card] := by
      rw [← hx, ← hy]
      exact heq
    have hxy : x ≡ y [MOD A.card] := Nat.ModEq.cancel_left_of_coprime hcopg hmod
    have hxy' : x = y := by
      unfold Nat.ModEq at hxy
      rwa [Nat.mod_eq_of_lt hxlt, Nat.mod_eq_of_lt hylt] at hxy
    apply hab
    calc a = a.gcd b * x := hx
      _ = a.gcd b * y := by rw [hxy']
      _ = b := hy.symm
  · by_cases hq : ∃ q : ℕ, q.Prime ∧ A.card = q + 1
    · -- Size n = p + 1 with p prime. By the prime-power bound p ^ 2 divides no element. Send a to
      -- the residue mod p of a, or of a / p when p ∣ a: a non-zero residue. Two elements with the
      -- same residue are b and p * b with p ∤ b (the other cases force equality as in the prime
      -- case). p + 1 elements in p - 1 residues give two such pairs {c, p c}, {d, p d} with c ≠ d,
      -- and then (p c) / gcd(p c, d) ≤ p forces c ∣ d, and symmetrically d ∣ c.
      obtain ⟨p, hp, hn1⟩ := hq
      have hp2 : ∀ a ∈ A, ¬ p * p ∣ a := by
        intro a ha h
        have h1 := hpp a ha p 2 hp (by rw [pow_two]; exact h)
        rw [pow_two, hn1] at h1
        have := hp.two_le
        nlinarith
      have key : ∀ a b : ℕ, ¬ p ∣ a → ¬ p ∣ b → a % p = b % p →
          a < A.card * a.gcd b → b < A.card * b.gcd a → a = b := by
        intro a b hpa hpb hab hla hlb
        obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
        obtain ⟨y, hy⟩ := Nat.gcd_dvd_right a b
        have hxlt : x < A.card := by
          have h2 : a.gcd b * x < a.gcd b * A.card := by
            rw [← hx, mul_comm]
            exact hla
          exact Nat.lt_of_mul_lt_mul_left h2
        have hylt : y < A.card := by
          have h2 : a.gcd b * y < a.gcd b * A.card := by
            rw [← hy, mul_comm, Nat.gcd_comm]
            exact hlb
          exact Nat.lt_of_mul_lt_mul_left h2
        have hxp : x ≠ p := by
          rintro rfl
          exact hpa (Dvd.intro_left _ hx.symm)
        have hyp : y ≠ p := by
          rintro rfl
          exact hpb (Dvd.intro_left _ hy.symm)
        have hxlt' : x < p := by omega
        have hylt' : y < p := by omega
        have hcop : p.gcd (a.gcd b) = 1 := by
          have h1 : Nat.Coprime p (a.gcd b) := by
            rw [Nat.Prime.coprime_iff_not_dvd hp]
            intro h
            exact hpa (h.trans (Nat.gcd_dvd_left a b))
          exact h1
        have hmod : a.gcd b * x ≡ a.gcd b * y [MOD p] := by
          rw [← hx, ← hy]
          exact hab
        have hxy := Nat.ModEq.cancel_left_of_coprime hcop hmod
        have hxy' : x = y := by
          unfold Nat.ModEq at hxy
          rwa [Nat.mod_eq_of_lt hxlt', Nat.mod_eq_of_lt hylt'] at hxy
        calc a = a.gcd b * x := hx
          _ = a.gcd b * y := by rw [hxy']
          _ = b := hy.symm
      have hC : ∀ a0 b : ℕ, p * a0 ∈ A → b ∈ A → ¬ p ∣ b → a0 % p = b % p → b = a0 := by
        intro a0 b ha hb hpb hf
        have hcopb : Nat.Coprime p b := (Nat.Prime.coprime_iff_not_dvd hp).2 hpb
        have hg' : (p * a0).gcd b = a0.gcd b := Nat.Coprime.gcd_mul_left_cancel a0 hcopb
        have hla := hlt (p * a0) ha b hb
        have hlb := hlt b hb (p * a0) ha
        rw [hg', hn1] at hla
        rw [Nat.gcd_comm, hg', hn1] at hlb
        obtain ⟨u, hu⟩ := Nat.gcd_dvd_left a0 b
        obtain ⟨v, hv⟩ := Nat.gcd_dvd_right a0 b
        have hu1 : u = 1 := by
          have h2 : a0.gcd b * (p * u) < a0.gcd b * (p + 1) := by
            calc a0.gcd b * (p * u) = p * (a0.gcd b * u) := by ring
              _ = p * a0 := by rw [← hu]
              _ < (p + 1) * a0.gcd b := hla
              _ = a0.gcd b * (p + 1) := by ring
          have h3 := Nat.lt_of_mul_lt_mul_left h2
          rcases u with _ | _ | u
          · exfalso
            rw [mul_zero] at hu
            rw [hu, mul_zero] at ha
            exact hA ha
          · rfl
          · have := hp.two_le
            nlinarith
        have e1 : a0.gcd b = a0 := by
          rw [hu1, mul_one] at hu
          exact hu.symm
        have hvlt : v < p + 1 := by
          have h2 : a0.gcd b * v < a0.gcd b * (p + 1) := by
            calc a0.gcd b * v = b := hv.symm
              _ < (p + 1) * a0.gcd b := hlb
              _ = a0.gcd b * (p + 1) := by ring
          exact Nat.lt_of_mul_lt_mul_left h2
        have hvp : v ≠ p := by
          rintro rfl
          exact hpb (Dvd.intro_left _ hv.symm)
        have hvlt' : v < p := by omega
        have hcopg : p.gcd (a0.gcd b) = 1 := by
          have h1 : Nat.Coprime p (a0.gcd b) := by
            rw [Nat.Prime.coprime_iff_not_dvd hp]
            intro h
            exact hpb (h.trans (Nat.gcd_dvd_right a0 b))
          exact h1
        have hmod : a0.gcd b * 1 ≡ a0.gcd b * v [MOD p] := by
          rw [mul_one, ← hv, e1]
          exact hf
        have hv1 := Nat.ModEq.cancel_left_of_coprime hcopg hmod
        have hv1' : v = 1 := by
          unfold Nat.ModEq at hv1
          rw [Nat.mod_eq_of_lt hp.one_lt, Nat.mod_eq_of_lt hvlt'] at hv1
          exact hv1.symm
        rw [hv, hv1', mul_one, e1]
      have hL : ∀ a ∈ A, ∀ b ∈ A, a ≠ b →
          (if p ∣ a then a / p else a) % p = (if p ∣ b then b / p else b) % p →
          ∃ c, ¬ p ∣ c ∧ (c = a ∨ c = b) ∧ (p * c = a ∨ p * c = b) := by
        intro a ha b hb hab hfab
        by_cases hpa : p ∣ a <;> by_cases hpb : p ∣ b
        · exfalso
          have hla := hlt a ha b hb
          have hlb := hlt b hb a ha
          obtain ⟨a0, rfl⟩ := hpa
          obtain ⟨b0, rfl⟩ := hpb
          have ha0 : ¬ p ∣ a0 := fun h => hp2 _ ha (Nat.mul_dvd_mul_left p h)
          have hb0 : ¬ p ∣ b0 := fun h => hp2 _ hb (Nat.mul_dvd_mul_left p h)
          rw [if_pos (dvd_mul_right p a0), if_pos (dvd_mul_right p b0),
            Nat.mul_div_cancel_left a0 hp.pos, Nat.mul_div_cancel_left b0 hp.pos] at hfab
          rw [Nat.gcd_mul_left] at hla hlb
          have hla' : a0 < A.card * a0.gcd b0 := by
            have h2 : p * a0 < p * (A.card * a0.gcd b0) := by
              calc p * a0 < A.card * (p * a0.gcd b0) := hla
                _ = p * (A.card * a0.gcd b0) := by ring
            exact Nat.lt_of_mul_lt_mul_left h2
          have hlb' : b0 < A.card * b0.gcd a0 := by
            have h2 : p * b0 < p * (A.card * b0.gcd a0) := by
              calc p * b0 < A.card * (p * b0.gcd a0) := hlb
                _ = p * (A.card * b0.gcd a0) := by ring
            exact Nat.lt_of_mul_lt_mul_left h2
          exact hab (by rw [key a0 b0 ha0 hb0 hfab hla' hlb'])
        · obtain ⟨a0, rfl⟩ := hpa
          rw [if_pos (dvd_mul_right p a0), if_neg hpb, Nat.mul_div_cancel_left a0 hp.pos] at hfab
          have e := hC a0 b ha hb hpb hfab
          exact ⟨b, hpb, Or.inr rfl, Or.inl (by rw [e])⟩
        · obtain ⟨b0, rfl⟩ := hpb
          rw [if_neg hpa, if_pos (dvd_mul_right p b0), Nat.mul_div_cancel_left b0 hp.pos] at hfab
          have e := hC b0 a hb ha hpa hfab.symm
          exact ⟨a, hpa, Or.inl rfl, Or.inr (by rw [e])⟩
        · exfalso
          rw [if_neg hpa, if_neg hpb] at hfab
          exact hab (key a b hpa hpb hfab (hlt a ha b hb) (hlt b hb a ha))
      have cross : ∀ c d : ℕ, c ∈ A → d ∈ A → p * c ∈ A → ¬ p ∣ d → c ∣ d := by
        intro c d hc hd hpc hpd
        have h := hlt (p * c) hpc d hd
        rw [Nat.Coprime.gcd_mul_left_cancel c ((Nat.Prime.coprime_iff_not_dvd hp).2 hpd), hn1] at h
        obtain ⟨u, hu⟩ := Nat.gcd_dvd_left c d
        have h2 : c.gcd d * (p * u) < c.gcd d * (p + 1) := by
          calc c.gcd d * (p * u) = p * (c.gcd d * u) := by ring
            _ = p * c := by rw [← hu]
            _ < (p + 1) * c.gcd d := h
            _ = c.gcd d * (p + 1) := by ring
        have h3 := Nat.lt_of_mul_lt_mul_left h2
        have hc0 : c ≠ 0 := fun h0 => hA (h0 ▸ hc)
        have hu1 : u = 1 := by
          rcases u with _ | _ | u
          · rw [mul_zero] at hu
            exact absurd hu hc0
          · rfl
          · have := hp.two_le
            nlinarith
        rw [hu, hu1, mul_one]
        exact Nat.gcd_dvd_right c d
      have hmaps : Set.MapsTo (fun a => (if p ∣ a then a / p else a) % p) (A : Set ℕ)
          (Finset.Icc 1 (p - 1) : Set ℕ) := by
        intro a ha
        have ha' : a ∈ A := ha
        have hlt' : (if p ∣ a then a / p else a) % p < p := Nat.mod_lt _ hp.pos
        have hne0 : (if p ∣ a then a / p else a) % p ≠ 0 := by
          by_cases hpa : p ∣ a
          · rw [if_pos hpa]
            obtain ⟨a0, rfl⟩ := hpa
            rw [Nat.mul_div_cancel_left a0 hp.pos]
            intro h
            exact hp2 _ ha' (Nat.mul_dvd_mul_left p (Nat.dvd_of_mod_eq_zero h))
          · rw [if_neg hpa]
            intro h
            exact hpa (Nat.dvd_of_mod_eq_zero h)
        simp only [Finset.coe_Icc, Set.mem_Icc]
        generalize (if p ∣ a then a / p else a) % p = r at hlt' hne0 ⊢
        omega
      have hcard1 : (Finset.Icc 1 (p - 1)).card < A.card := by
        rw [Nat.card_Icc, hn1]
        omega
      obtain ⟨a1, ha1, b1, hb1, hab1, heq1⟩ :=
        Finset.exists_ne_map_eq_of_card_lt_of_maps_to hcard1 hmaps
      obtain ⟨c1, hc1p, hc1, hpc1⟩ := hL a1 ha1 b1 hb1 hab1 heq1
      have hc1A : c1 ∈ A := by
        rcases hc1 with h | h <;> rw [h] <;> assumption
      have hpc1A : p * c1 ∈ A := by
        rcases hpc1 with h | h <;> rw [h] <;> assumption
      have hcard2 : (Finset.Icc 1 (p - 1)).card < (A.erase (p * c1)).card := by
        rw [Finset.card_erase_of_mem hpc1A, Nat.card_Icc, hn1]
        have := hp.two_le
        omega
      have hmaps2 : Set.MapsTo (fun a => (if p ∣ a then a / p else a) % p)
          ((A.erase (p * c1)) : Set ℕ) (Finset.Icc 1 (p - 1) : Set ℕ) :=
        fun a ha => hmaps (Finset.mem_of_mem_erase ha)
      obtain ⟨a2, ha2, b2, hb2, hab2, heq2⟩ :=
        Finset.exists_ne_map_eq_of_card_lt_of_maps_to hcard2 hmaps2
      obtain ⟨c2, hc2p, hc2, hpc2⟩ :=
        hL a2 (Finset.mem_of_mem_erase ha2) b2 (Finset.mem_of_mem_erase hb2) hab2 heq2
      have hc2A : c2 ∈ A := by
        rcases hc2 with h | h <;> rw [h]
        · exact Finset.mem_of_mem_erase ha2
        · exact Finset.mem_of_mem_erase hb2
      have hpc2E : p * c2 ∈ A.erase (p * c1) := by
        rcases hpc2 with h | h <;> rw [h] <;> assumption
      have hpc2A : p * c2 ∈ A := Finset.mem_of_mem_erase hpc2E
      have hne12 : c2 ≠ c1 := by
        rintro rfl
        exact (Finset.mem_erase.mp hpc2E).1 rfl
      exact hne12 (Nat.dvd_antisymm (cross c2 c1 hc2A hc1A hpc2A hc1p)
        (cross c1 c2 hc1A hc2A hpc1A hc2p))
    · push Not at hq
      obtain ⟨a, ha, b, hb, hle⟩ :=
        hcomp A hA hne hg hpr hq (fun a ha b hb => (hlt a ha b hb).le) hpp
      exact absurd hle (not_le.mpr (hcon a ha b hb))
