import Defs.IsPrime
import Mathlib.Tactic

/-! Declared dependencies (D-4 step 8): `variant-2a7919a9--h1`, `variant-2a7919a9--h2`. -/

/-! Hole `bound` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_2a7919a9__h1 : ∀ (l : List ℕ), ∀ x ∈ l, x ≤ l.sum := by
  sorry


/-! Hole `euclid` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_2a7919a9__h2 : ∀ (l : List ℕ), (∀ x ∈ l, x ≤ l.sum) → ∃ p, l.sum < p ∧ Opn.IsPrime p := by
  sorry
