import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-1094--h3--h1--h1`, `erdos-1094--h3--h1--h2`. -/

open scoped Nat

/-! Hole `h_keven` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3__h1__h1 : ∃ (K₁ : ℕ),
  ∀ (n k : ℕ),
    K₁ < k → (2 : ℕ) * k ≤ n → n < k * k → k % (2 : ℕ) = (0 : ℕ) → ∃ (p : ℕ), Nat.Prime p ∧ p ≤ k ∧ n % p < k % p := by
  sorry


open scoped Nat

/-! Hole `h_odd` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3__h1__h2 : ∃ (K₂ : ℕ),
  ∀ (n k : ℕ),
    K₂ < k →
      (2 : ℕ) * k ≤ n →
        n < k * k → k % (2 : ℕ) = (1 : ℕ) → n % (2 : ℕ) = (1 : ℕ) → ∃ (p : ℕ), Nat.Prime p ∧ p ≤ k ∧ n % p < k % p := by
  sorry
