import Mathlib
import Nodes.«erdos-1094--h3».Context

open scoped Nat

/-! Hole `h_small_n` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1094__h3 : ∃ (K : ℕ), ∀ (n k : ℕ), (0 : ℕ) < k → (2 : ℕ) * k ≤ n → n < k * k → (n.choose k).minFac > k → k ≤ K := by
  sorry
