import Mathlib

/-! Declared dependencies (D-4 step 8): `erdos-69--h1`, `erdos-69--h2`. -/

open scoped ArithmeticFunction.omega

/-! Hole `h_lambert` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h1 : ∑' (n : ℕ), ↑(ω n) / 2 ^ n = ∑' (p : Nat.Primes), 1 / (2 ^ ↑p - 1) := by
  sorry


open scoped ArithmeticFunction.omega

/-! Hole `h_irr` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2 : ∑' (n : ℕ), ↑(ω n) / 2 ^ n = ∑' (p : Nat.Primes), 1 / (2 ^ ↑p - 1) → Irrational (∑' (p : Nat.Primes), 1 / (2 ^ ↑p - 1)) := by
  sorry
