import Defs.IsPrime
import Mathlib.Tactic

/-! Hole `bound` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_2a7919a9__h1 : ∀ (l : List ℕ), ∀ x ∈ l, x ≤ l.sum := by
  intro l x hx
  exact List.single_le_sum (fun _ _ => Nat.zero_le _) x hx
