/-! Hole `h₂` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem variant_93e79cb5__h2 : ∀ (p q : Prop), p ∧ q → q ∧ p → q ∧ p → p := by
  sorry
