import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h1».Context

open scoped ArithmeticFunction.omega

/-! Hole `hsplit` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h1 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  ∀ (N k : ℕ),
    ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
      ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
        (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k := by
  intro _ N k
  have hle : ∀ n : ℕ, ((ω : ℕ → ℕ) n : ℝ) ≤ (n : ℝ) + 1 := by
    intro n
    have h1 : n.primeFactorsList.dedup ⊆ List.range (n+1) := by
      intro p hp
      rw [List.mem_dedup] at hp
      rw [List.mem_range]
      have := Nat.le_of_mem_primeFactorsList hp
      omega
    have h2 := List.Subperm.length_le ((List.nodup_dedup _).subperm h1)
    simp only [List.length_range] at h2
    have h3 : (ω : ℕ → ℕ) n ≤ n + 1 := by
      rw [ArithmeticFunction.cardDistinctFactors_apply]; exact h2
    exact_mod_cast h3
  have hg : Summable (fun j : ℕ => ((j : ℝ) + ((N : ℝ) + 2)) * (1 / 2 : ℝ) ^ j) := by
    have a := summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) 1 (r := 1 / 2) (by norm_num)
    have b := (summable_geometric_two).mul_left ((N : ℝ) + 2)
    simpa [add_mul, pow_one] using a.add b
  have hsum : Summable (fun j : ℕ => (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) := by
    refine Summable.of_nonneg_of_le (fun j => by positivity) (fun j => ?_) hg
    have hj := hle (N + 1 + j)
    push_cast at hj
    have hp : (0 : ℝ) < 2 ^ j := by positivity
    rw [div_le_iff₀ (by positivity), one_div, inv_pow, pow_succ]
    field_simp
    nlinarith
  rw [← Summable.sum_add_tsum_nat_add k hsum]
  congr 1
  rw [← tsum_div_const]
  congr 1
  ext i
  rw [show N + 1 + (i + k) = N + k + 1 + i by ring]
  rw [div_div, ← pow_add]
  congr 2
  ring

