import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h2».Context

open scoped ArithmeticFunction.omega

/-! Hole `hpos` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h2 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  (∀ (N k : ℕ),
      ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
        ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
          (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k) →
    ∀ (M : ℕ), (0 : ℝ) < ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) := by
  intro _ _ M
  have hbound : ∀ n : ℕ,
      (ω n : ℝ) / 2 ^ n ≤ (n : ℝ) ^ 1 * (1 / 2 : ℝ) ^ n + (1 / 2 : ℝ) ^ n := by
    intro n
    have h1 : ω n ≤ n + 1 := by
      rw [ArithmeticFunction.cardDistinctFactors_apply]
      calc n.primeFactorsList.dedup.length = n.primeFactors.card := rfl
        _ ≤ (Finset.range (n + 1)).card :=
            Finset.card_le_card (fun p hp =>
              Finset.mem_range.2 (Nat.lt_succ_of_le (Nat.le_of_mem_primeFactors hp)))
        _ = n + 1 := Finset.card_range _
    have h2 : (ω n : ℝ) ≤ (n : ℝ) + 1 := by exact_mod_cast h1
    have h4 : (0 : ℝ) ≤ ((2 : ℝ) ^ n)⁻¹ := by positivity
    rw [pow_one, one_div, inv_pow, div_eq_mul_inv]
    nlinarith [mul_le_mul_of_nonneg_right h2 h4]
  have hsum : Summable (fun n : ℕ => (ω n : ℝ) / 2 ^ n) := by
    refine Summable.of_nonneg_of_le (fun n => by positivity) hbound ?_
    exact (summable_pow_mul_geometric_of_norm_lt_one 1 (by norm_num [Real.norm_eq_abs])).add
      (summable_geometric_of_lt_one (by norm_num) (by norm_num))
  have hshift : Summable (fun j : ℕ => (ω (j + (M + 1)) : ℝ) / 2 ^ (j + (M + 1))) :=
    hsum.comp_injective (add_left_injective (M + 1))
  have hs : Summable (fun j : ℕ => (ω (M + 1 + j) : ℝ) / 2 ^ (j + 1)) := by
    refine (hshift.mul_left ((2 : ℝ) ^ M)).congr (fun j => ?_)
    have e : j + (M + 1) = M + 1 + j := by omega
    have e2 : (2 : ℝ) ^ (M + 1 + j) = 2 ^ M * 2 ^ (j + 1) := by
      rw [← pow_add]; congr 1; omega
    have h2 : (2 : ℝ) ^ M ≠ 0 := by positivity
    simp only [e, e2]
    rw [← mul_div_assoc, mul_div_mul_left _ _ h2]
  have hpos : (0 : ℝ) < (ω (M + 1 + 1) : ℝ) / 2 ^ (1 + 1) := by
    have hne : (M + 1 + 1).primeFactors.Nonempty := Nat.nonempty_primeFactors.2 (by omega)
    have hc : 0 < ω (M + 1 + 1) := by
      rw [ArithmeticFunction.cardDistinctFactors_apply]
      show 0 < (M + 1 + 1).primeFactors.card
      exact Finset.card_pos.2 hne
    have : (0 : ℝ) < (ω (M + 1 + 1) : ℝ) := by exact_mod_cast hc
    positivity
  exact hs.tsum_pos (fun j => by positivity) 1 hpos
