import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h2».Context

open scoped ArithmeticFunction.omega

/-! Hole `hpos` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h2 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  (∀ (N k : ℕ),
      ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
        ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
          (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k) →
    ∀ (M : ℕ), (0 : ℝ) < ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) := by
  intro _ hs M
  have hω : 0 < ((ω : ℕ → ℕ) (M + 1 + 1)) := by
    rw [ArithmeticFunction.cardDistinctFactors_apply]
    apply List.length_pos_of_mem (a := (M + 1 + 1).minFac)
    rw [List.mem_dedup]
    exact (Nat.mem_primeFactorsList (by omega)).2 ⟨Nat.minFac_prime (by omega), Nat.minFac_dvd _⟩
  have hT : (0 : ℝ) ≤ ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + 2 + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) :=
    tsum_nonneg (fun j => by positivity)
  rw [hs M 2]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add]
  have : (0 : ℝ) < (↑((ω : ℕ → ℕ) (M + 1 + 1)) : ℝ) := by exact_mod_cast hω
  positivity

