import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h3».Context

open scoped ArithmeticFunction.omega

/-! Hole `hbound` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h3 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  (∀ (N k : ℕ),
      ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
        ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
          (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k) →
    (∀ (M : ℕ), (0 : ℝ) < ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) →
      ∀ (M : ℕ),
        ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) ≤
          Real.logb (2 : ℝ) ((↑M : ℝ) + (1 : ℝ)) + (1 : ℝ) := by
  intro _ _ _ M
  have hbound : ∀ n : ℕ,
      (ω n : ℝ) / 2 ^ n ≤ (n : ℝ) ^ 1 * (1 / 2 : ℝ) ^ n + (1 / 2 : ℝ) ^ n := by
    intro n
    have h1 : ω n ≤ n + 1 := by
      rw [ArithmeticFunction.cardDistinctFactors_apply]
      calc n.primeFactorsList.dedup.length = n.primeFactors.card := rfl
        _ ≤ (Finset.range (n + 1)).card :=
            Finset.card_le_card (fun p hp =>
              Finset.mem_range.2 (Nat.lt_succ_of_le (Nat.le_of_mem_primeFactors hp)))
        _ = n + 1 := Finset.card_range _
    have h2 : (ω n : ℝ) ≤ (n : ℝ) + 1 := by exact_mod_cast h1
    have h4 : (0 : ℝ) ≤ ((2 : ℝ) ^ n)⁻¹ := by positivity
    rw [pow_one, one_div, inv_pow, div_eq_mul_inv]
    nlinarith [mul_le_mul_of_nonneg_right h2 h4]
  have hsum : Summable (fun n : ℕ => (ω n : ℝ) / 2 ^ n) := by
    refine Summable.of_nonneg_of_le (fun n => by positivity) hbound ?_
    exact (summable_pow_mul_geometric_of_norm_lt_one 1 (by norm_num [Real.norm_eq_abs])).add
      (summable_geometric_of_lt_one (by norm_num) (by norm_num))
  have hs : ∀ N : ℕ, Summable (fun j : ℕ => (ω (N + 1 + j) : ℝ) / 2 ^ (j + 1)) := by
    intro M
    have hshift : Summable (fun j : ℕ => (ω (j + (M + 1)) : ℝ) / 2 ^ (j + (M + 1))) :=
      hsum.comp_injective (add_left_injective (M + 1))
    refine (hshift.mul_left ((2 : ℝ) ^ M)).congr (fun j => ?_)
    have e : j + (M + 1) = M + 1 + j := by omega
    have e2 : (2 : ℝ) ^ (M + 1 + j) = 2 ^ M * 2 ^ (j + 1) := by
      rw [← pow_add]; congr 1; omega
    have h2 : (2 : ℝ) ^ M ≠ 0 := by positivity
    simp only [e, e2]
    rw [← mul_div_assoc, mul_div_mul_left _ _ h2]
  have hpow : ∀ n : ℕ, 0 < n → 2 ^ ω n ≤ n := by
    intro n hn
    rw [ArithmeticFunction.cardDistinctFactors_apply]
    change 2 ^ n.primeFactors.card ≤ n
    calc 2 ^ n.primeFactors.card ≤ ∏ p ∈ n.primeFactors, p :=
          Finset.pow_card_le_prod _ _ _ (fun p hp => (Nat.prime_of_mem_primeFactors hp).two_le)
      _ ≤ n := Nat.le_of_dvd hn (Nat.prod_primeFactors_dvd n)
  have hle : ∀ j : ℕ, (ω (M + 1 + j) : ℝ) ≤ Real.logb 2 ((M : ℝ) + 1) + j := by
    intro j
    have h1 : 2 ^ ω (M + 1 + j) ≤ (M + 1) * 2 ^ j := by
      calc 2 ^ ω (M + 1 + j) ≤ M + 1 + j := hpow _ (by omega)
        _ ≤ (M + 1) * (1 + j) := by nlinarith
        _ ≤ (M + 1) * 2 ^ j := by
          apply Nat.mul_le_mul_left
          have := Nat.lt_two_pow_self (n := j)
          omega
    have h1' : (2 : ℝ) ^ (ω (M + 1 + j) : ℝ) ≤ ((M : ℝ) + 1) * 2 ^ (j : ℝ) := by
      rw [Real.rpow_natCast, Real.rpow_natCast]
      exact_mod_cast h1
    have hMpos : (0 : ℝ) < (M : ℝ) + 1 := by positivity
    have := (Real.le_logb_iff_rpow_le (by norm_num : (1 : ℝ) < 2) (by positivity)).2 h1'
    rwa [Real.logb_mul hMpos.ne' (by positivity), Real.logb_rpow (by norm_num) (by norm_num)] at this
  set L := Real.logb 2 ((M : ℝ) + 1)
  have hg1 : Summable (fun j : ℕ => (1 / 2 : ℝ) ^ j) :=
    summable_geometric_of_lt_one (by norm_num) (by norm_num)
  have hg2 : Summable (fun j : ℕ => (j : ℝ) * (1 / 2 : ℝ) ^ j) := by
    have h := summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) 1 (r := 1 / 2)
      (by norm_num [Real.norm_eq_abs])
    exact h.congr (fun j => by rw [pow_one])
  have hrhs : ∀ j : ℕ, (L + j) / 2 ^ (j + 1) = (L / 2) * (1 / 2 : ℝ) ^ j + (1 / 2) * ((j : ℝ) * (1 / 2 : ℝ) ^ j) := by
    intro j
    rw [pow_succ, one_div_pow]
    field_simp
  have hsr : Summable (fun j : ℕ => (L + j) / 2 ^ (j + 1)) := by
    simp only [hrhs]
    exact (hg1.mul_left _).add (hg2.mul_left _)
  have hlhs : Summable (fun j : ℕ => (ω (M + 1 + j) : ℝ) / 2 ^ (j + 1)) := by
    refine Summable.of_nonneg_of_le (fun j => by positivity) (fun j => ?_) hsr
    exact div_le_div_of_nonneg_right (hle j) (by positivity)
  calc ∑' j : ℕ, (ω (M + 1 + j) : ℝ) / 2 ^ (j + 1)
      ≤ ∑' j : ℕ, (L + j) / 2 ^ (j + 1) :=
        hlhs.tsum_le_tsum (fun j => div_le_div_of_nonneg_right (hle j) (by positivity)) hsr
    _ = L + 1 := by
      simp only [hrhs]
      rw [(hg1.mul_left _).tsum_add (hg2.mul_left _), tsum_mul_left, tsum_mul_left,
        tsum_geometric_two, tsum_coe_mul_geometric_of_norm_lt_one (by norm_num [Real.norm_eq_abs])]
      norm_num

