import Mathlib

/-! Hole `descent` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_412__h1 : ∀ (m : ℕ),
  3 ≤ m →
    (¬∃ x, 2 ≤ x ∧ x < m ∧ ∃ k, (⇑(σ 1))^[k] x = m) → ∃ m', 2 ≤ m' ∧ m' < m ∧ ∃ i j, (⇑(σ 1))^[i] m = (⇑(σ 1))^[j] m' := by
  sorry
