import Mathlib
import Nodes.«erdos-69--h2-v2--h1-v2--h3».Context

open scoped ArithmeticFunction.omega

/-! Hole `hbound` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_69__h2_v2__h1_v2__h3 : ∑' (n : ℕ), (↑((ω : ℕ → ℕ) n) : ℝ) / (2 : ℝ) ^ n = ∑' (p : Nat.Primes), (1 : ℝ) / ((2 : ℝ) ^ (↑p : ℕ) - (1 : ℝ)) →
  (∀ (N k : ℕ),
      ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) =
        ∑ j ∈ Finset.range k, (↑((ω : ℕ → ℕ) (N + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) +
          (∑' (j : ℕ), (↑((ω : ℕ → ℕ) (N + k + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) / (2 : ℝ) ^ k) →
    (∀ (M : ℕ), (0 : ℝ) < ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) →
      ∀ (M : ℕ),
        ∑' (j : ℕ), (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ)) ≤
          Real.logb (2 : ℝ) ((↑M : ℝ) + (1 : ℝ)) + (1 : ℝ) := by
  intro _ _ _ M
  have hω2 : ∀ m : ℕ, 0 < m → 2 ^ ω m ≤ m := by
    intro m hm
    rw [ArithmeticFunction.cardDistinctFactors_apply]
    have hprod := Nat.prod_primeFactorsList (Nat.pos_iff_ne_zero.mp hm)
    have h2 : ∀ p ∈ m.primeFactorsList, 2 ≤ p := fun p hp =>
      (Nat.prime_of_mem_primeFactorsList hp).two_le
    have hpow : 2 ^ m.primeFactorsList.length ≤ m.primeFactorsList.prod := by
      simpa using List.pow_card_le_prod _ _ h2
    calc 2 ^ m.primeFactorsList.dedup.length ≤ 2 ^ m.primeFactorsList.length :=
          Nat.pow_le_pow_right (by norm_num) (List.dedup_sublist _).length_le
      _ ≤ m := by omega
  have hω : ∀ m : ℕ, ω m ≤ m := fun m => by
    rcases Nat.eq_zero_or_pos m with rfl | hm
    · simp
    · exact le_trans (Nat.lt_two_pow_self).le (hω2 m hm)
  have hs : Summable (fun j : ℕ => (↑((ω : ℕ → ℕ) (M + (1 : ℕ) + j)) : ℝ) / (2 : ℝ) ^ (j + (1 : ℕ))) := by
    have hg : Summable (fun j : ℕ => (M + 1 : ℝ) * (1 / 2 : ℝ) ^ j + (j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j) :=
      (summable_geometric_two.mul_left _).add
        (summable_pow_mul_geometric_of_norm_lt_one 1 (by norm_num))
    refine Summable.of_nonneg_of_le (fun j => by positivity) (fun j => ?_) hg
    have h1 : (ω (M + 1 + j) : ℝ) ≤ M + 1 + j := by exact_mod_cast hω _
    have hh : (1 / 2 : ℝ) ^ j * 2 ^ j = 1 := by rw [← mul_pow]; norm_num
    have e : ((M + 1 : ℝ) * (1 / 2 : ℝ) ^ j + (j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j) * 2 ^ (j + 1)
        = 2 * (M + 1 + j) := by
      rw [pow_succ]; linear_combination (2 * (M + 1 + j) : ℝ) * hh
    rw [div_le_iff₀ (by positivity), e]
    have : (0 : ℝ) ≤ M + 1 + j := by positivity
    linarith
  obtain ⟨L, hL⟩ : ∃ L : ℝ, L = Real.logb (2 : ℝ) ((↑M : ℝ) + (1 : ℝ)) := ⟨_, rfl⟩
  rw [← hL]
  have hterm : ∀ j : ℕ, (ω (M + 1 + j) : ℝ) ≤ L + j := by
    intro j
    have hn : 2 ^ ω (M + 1 + j) ≤ (M + 1) * 2 ^ j := by
      have a := hω2 (M + 1 + j) (by omega)
      have b : j < 2 ^ j := Nat.lt_two_pow_self
      have c : 1 ≤ 2 ^ j := Nat.one_le_two_pow
      calc 2 ^ ω (M + 1 + j) ≤ M + 1 + j := a
        _ ≤ M * 2 ^ j + 2 ^ j := by
          have : M ≤ M * 2 ^ j := Nat.le_mul_of_pos_right M c
          omega
        _ = (M + 1) * 2 ^ j := by ring
    have hr : (2 : ℝ) ^ ((ω (M + 1 + j) : ℝ) - j) ≤ (M : ℝ) + 1 := by
      rw [Real.rpow_sub (by norm_num), Real.rpow_natCast, Real.rpow_natCast,
        div_le_iff₀ (by positivity)]
      exact_mod_cast hn
    have := (Real.le_logb_iff_rpow_le (by norm_num) (by positivity)).mpr hr
    rw [hL]
    linarith
  have hg : Summable (fun j : ℕ => L / 2 * (1 / 2 : ℝ) ^ j + 1 / 2 * ((j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j)) :=
    (summable_geometric_two.mul_left (L / 2)).add
      ((summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) (r := 1 / 2) 1 (by norm_num)).mul_left (1 / 2))
  calc _ ≤ ∑' j : ℕ, (L / 2 * (1 / 2 : ℝ) ^ j + 1 / 2 * ((j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j)) := by
        refine Summable.tsum_le_tsum (fun j => ?_) hs hg
        have e : L / 2 * (1 / 2 : ℝ) ^ j + 1 / 2 * ((j : ℝ) ^ 1 * (1 / 2 : ℝ) ^ j)
            = (L + j) / 2 ^ (j + 1) := by
          rw [one_div_pow]; field_simp; ring
        rw [e]
        exact div_le_div_of_nonneg_right (hterm j) (by positivity)
    _ = L + 1 := by
        rw [Summable.tsum_add (summable_geometric_two.mul_left (L / 2))
          ((summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) (r := 1 / 2) 1 (by norm_num)).mul_left (1 / 2)),
          Summable.tsum_mul_left (L / 2) summable_geometric_two,
          Summable.tsum_mul_left (1 / 2) (summable_pow_mul_geometric_of_norm_lt_one (R := ℝ) (r := 1 / 2) 1 (by norm_num)),
          tsum_geometric_two]
        simp only [pow_one]
        rw [tsum_coe_mul_geometric_of_norm_lt_one (𝕜 := ℝ) (r := 1 / 2) (by norm_num)]
        norm_num

